src/Relation/Binary/HeterogeneousEquality.agda
src/Relation/Binary/PropositionalEquality.agda

I added the simplified inspect to Relation.Binary.HeterogeneousEquality too.

Added simplified inspect.

---

README.md

 Fix link to source in html for 2.4.2.1

---

CHANGELOG
README.agda
src/Data/List/Properties.agda

This is the equivalent of the pre-existing `length-gfilter` property

Added length-filter property 

---

src/Data/Stream.agda

Should be a fairly simple change, bringing `Stream` into line with `List`, `Colist`, &c. I don't know whether I pushed to the right branch, but this file doesn't seem to have changed recently.

Make Stream universe-polymorphic

---

CHANGELOG.md
src/Data/Container.agda
src/Data/Container/Combinator.agda

This is #123, hopefully fixed. All Data.Container.* compile. I still can't run GenerateEverything, but `runhaskell GenerateEverything.hs` finishes within a second without output or error. Is there another way to check that I haven't broken anything else?

Data.Container, second try

---

CHANGELOG.md
src/Data/Fin.agda
src/Data/Fin/Properties.agda
src/Data/List/Countdown.agda

These functions are already used privately in `Data.List.Countdown`. They are also useful for [a concise proof of the pigeonhole principle](https://github.com/byorgey/labelled-structures/blob/master/agda-old/Pigeonhole.agda) which I'll be trying to push later.
I've removed the private implementation of said functions in `Data.List.Countdown`.

Added functions punchIn and punchOut to Data.Fin with associated properties. 

---

src/Data/List/Any/Membership/Propositional.agda

[ scope ] Privatising M to avoid scope pollution

---

CHANGELOG.md
src/Data/Sum.agda

This functions can be quite useful and match the existing from-just for Data.Maybe

Add from-inj₁ and from-inj₂ to Data.Sum

---

CHANGELOG.md
src/Data/Covec.agda

Noticed this was not level polymorphic whilst working on #174

[ generalize ] Level-polymorphic covec

---

CHANGELOG.md
src/Data/AVL.agda
src/Data/Bin.agda
src/Data/Cofin.agda
src/Data/Colist.agda
src/Data/Conat.agda
src/Data/Covec.agda
src/Data/List/Properties.agda
src/Data/Maybe/Base.agda
src/Data/Nat/Properties.agda
src/Data/Plus.agda
src/Data/Product.agda
src/Data/ReflexiveClosure.agda
src/Data/Star/Properties.agda
src/Data/Sum.agda
src/Data/Vec/Properties.agda
src/Data/W.agda

[ new ] constructor injectivity lemmas

---

CHANGELOG.md
src/Data/W.agda

Noticed there wasn't much in `Data.W` whilst I was working on #177 so I defined basic traversals. Now that I think about it, we seem to be missing `induction` in quite a lot of places (e.g. `Data.List.Base`). Might be a good thing to add to the todo list.

[ new ] some functions acting on W types

---

CHANGELOG.md
src/Data/Bool/Properties.agda
src/Data/Container/Any.agda
src/Data/Fin/Properties.agda
src/Data/Integer/Properties.agda
src/Data/List/All/Properties.agda
src/Data/List/Any/BagAndSetEquality.agda
src/Data/List/Any/Membership/Propositional/Properties.agda
src/Data/Nat/Properties.agda
src/Data/Product.agda
src/Data/Product/Properties.agda
src/Data/Rational/Properties.agda
src/Data/Sum.agda
src/Data/Sum/Properties.agda
src/Data/Vec/All/Properties.agda
src/Data/Vec/Properties.agda
src/Relation/Binary/PropositionalEquality.agda

Generalised the notion of proof irrelevance as per @gallais's suggestion in #176.
I've added proofs for the most commonly used predicates and relations. If I've left any major ones out then please do give me a shout.
I've also standardised the naming of existing proofs of irrelevant relations across the library.

Generalised proof irrelevance

---

CHANGELOG.md
src/Data/Nat/Divisibility.agda

I was having [a bit of fun](https://github.com/gallais/potpourri/blob/846de27674989c78b77e479e35e137417c03341e/agda/papers/fibonacci/Fib.agda) with divisibility so I figured I'd throw in the lemmas
I have found to be missing.

Divisibility facts

---

CHANGELOG.md
src/Relation/Binary/HeterogeneousEquality.agda

From issue https://github.com/agda/agda-stdlib/issues/274

Add indexed functions in `Relation.Binary.HeterogeneousEquality`

---

CHANGELOG.md
src/Data/Vec.agda
src/Data/Vec/Properties.agda

Also add associated properties

Add insert and remove to Data.Vec

---

src/Data/Fin/Properties.agda

The remodeled sort system (https://github.com/agda/agda/pull/3042) requires this one small change in the library.

Make library work with remodeled sort system

---

CHANGELOG.md
src/Data/List/NonEmpty.agda

Purging the `Utils` module I built up on tonight's formalization

[ new ] fromList : List A → Maybe (List⁺ A)

---

CHANGELOG.md
src/Data/String/Base.agda

Purging the `Utils` module I built up on tonight's formalization

[ new ] functions in Data.String

---

CHANGELOG.md
src/Data/Star/Decoration.agda
src/Data/Star/Pointer.agda

Sorry about the multiple commits, I'm still figuring out the best way to deal with git and make PRs with a single thing in them. But this should be clean. Part of #295 .

Make Data.Start.Decoration and .Pointer more level polymorphic

---

src/Reflection.agda

(part of #295 ). Not very useful right now as Agda.Builtin.Reflection is not level polymorphic. But one day...

Make various pieces in Reflection more level polymorphic 

---

src/Record.agda

Make Label in Record be more level polymorphic.

---

CHANGELOG.md
src/Data/List/All/Properties.agda
src/Data/Vec/All/Properties.agda

[ refactor ] improved name consistency in `All.Properties` files

---

src/Data/Fin.agda
src/Data/Fin/Dec.agda
src/Data/Fin/Subset.agda
src/Data/Fin/Substitution.agda
src/Data/Fin/Substitution/Example.agda
src/Data/Fin/Substitution/Lemmas.agda
src/Data/Fin/Substitution/List.agda

Issue #295.  These are all related, which is why they are all together.

increase Level polymorphism of many things under Data.Fin

---

README.md

(amends commit a1a10b39d35b8fc40e87723a89f5682252d46380)

Fixup Updated CHANGELOG, README etc for release

---

CHANGELOG.md
src/Data/Sum/Base.agda

Now that I'm used to have them for Product, I miss them in Sum.

[ new ] map1 and map2 for Sum

---

CHANGELOG.md
src/Codata/Delay.agda
src/Data/Maybe/Base.agda

Today it seems I have decided to submit a patch for every single function I wish I
had whilst writing my program...

[ new ] fromMaybe : A -> Maybe A -> A

---

CHANGELOG.md
src/Data/String/Base.agda

[ new ] fromList⁺ : List⁺ Char → String

---

CHANGELOG.md
src/Data/Vec/All/Properties.agda
src/Data/Vec/Membership/Propositional/Properties.agda
src/Data/Vec/Properties.agda
src/Data/Vec/Relation/Pointwise/Inductive.agda

Emptying out the `Vec` directory from my own library.

Added some more `Vec` properties

---

CHANGELOG.md
src/Codata/Colist.agda
src/Codata/Conat.agda
src/Codata/Covec.agda
src/Codata/Stream.agda

Following discussions on the mailing lists. For once these should not be squashed
(or we should find a proper description of the two contributions)

Codata: toMusical & guarded append

---

CHANGELOG.md
src/Data/List/Relation/Sublist/Inductive.agda
src/Data/List/Relation/Sublist/Inductive/Solver.agda

Thinking about Matthew's solvers, I realised `_\sub=_` was decidable so thought I'd add the result.
And then I also threw in a solver for problems of the form `xs \sub= ys`.

[ new ] Sublist Order is decidable if equality is

---

src/Data/List/Relation/Permutation/Inductive/Properties.agda

This adds the converse to the existing function `↭⇒~bag`, namely a
conversion `~bag⇒↭` from `_∼[ bag ]_` equality to inductive permutations.
Both functions are moved to the bottom of the file in order to keep them
grouped together, while allowing to call functions defined elsewhere in
the file.
By the way, I noticed that `↭⇒~bag` contains a tilde, unlike the `_∼[_]_` operator, so I used a tilde as well. Perhaps, for consistency, it could be renamed to use a \sim.

[ new ] conversion from bag equality to Permutation

---

CHANGELOG.md
src/Algebra.agda

I haven't added `RawBand` as mentioned in the original issue as it's exactly the same as `RawSemigroup`.

[ fix #425 ] Added more raw algebras

---

src/Data/List/Relation/Sublist/Inductive.agda
src/Data/List/Relation/Sublist/Inductive/Properties.agda

Using this opportunity to put the Properties in their own module.

[ new ] OPEs properties wrt list functions

---

CHANGELOG.md
src/Relation/Binary/Lattice.agda
src/Relation/Binary/Properties/DistributiveLattice.agda
src/Relation/Binary/Properties/HeytingAlgebra.agda

Added distributive lattice, Heyting algebra and Boolean algebra in order
theoretic settings.
I would probably enrich further in the future. However, I can see lots of work is done for Boolean algebra as an algebra. Not sure what to do with that.
I am also not sure what I should name the extra operator from Heyting algebra. I usually call it exponential, but it's a term borrowed from category theory. Sometimes I see implication, but it's not a very good name as well, because implication is a logical term. If you have better suggestions I would like to learn about it.
c.f. #439

[ new ] implemented more order theories

---

src/Data/List/Relation/Sublist/Extensional/Propositional/Properties.agda
src/Data/List/Relation/Sublist/Extensional/Setoid/Properties.agda

Just trying to contribute; please c.f. #310.

Realised nad's issue for removing an instance of module ⊆-Reasoning. 

---

CHANGELOG.md
src/Data/List/Properties.agda

[ deprecation ] deprecated old `mapIsFold` style names

---

CHANGELOG.md
src/Data/Nat/Properties.agda

Deprecate `≤+≢⇒<` in favour of `≤∧≢⇒<`

---

CHANGELOG.md
src/Algebra/FunctionProperties/Consequences.agda
src/Algebra/FunctionProperties/Consequences/Propositional.agda
src/Data/Integer/Properties.agda
src/Data/Nat/Properties.agda

Also made the module type argument implicit.

[ refactor ] moved `sel⇒idem` to `Algebra.FunctionProperties.Consequences.Propositional`

---

CHANGELOG.md
src/Relation/Binary/Construct/NaturalOrder/Left.agda
src/Relation/Binary/Construct/NaturalOrder/Right.agda

Once #535 has been merged in, this can be used to simplify `Algebra.Properties.Lattice`

[ new ] added left and right natural orders

---

CHANGELOG.md
src/Algebra/FunctionProperties.agda
src/Algebra/Properties/AbelianGroup.agda
src/Algebra/Properties/BooleanAlgebra.agda
src/Algebra/Properties/CommutativeMonoid.agda
src/Algebra/Properties/DistributiveLattice.agda
src/Algebra/Properties/Group.agda
src/Algebra/Properties/Lattice.agda
src/Algebra/Properties/Ring.agda
src/Algebra/Structures.agda

A couple of tools to strip out all the useless `refl`s from algebraic proofs.

[ new ] added left and right congruence properties to algebraic structures

---

CHANGELOG.md
src/Relation/Binary/Construct/Intersection.agda
src/Relation/Binary/Construct/Union.agda

[ fix #473 ] Added intersection and union binary relation constructs

---

CHANGELOG.md
src/Data/Nat/Properties.agda

Clearing out some lemmas from my own code

[ new ] added new max/min properties for Nat

---

src/Data/List/First.agda
src/Data/List/First/Properties.agda

Inspired by our work on Prefix and Suffix: a view for First.

[ new ] view corresponding to First

---

README.agda
README/Inspect.agda

Use case, equivalent auxiliary definitions, analysis of the implementation.

[ re #595 ] Documentation for the inspect idiom

---

CHANGELOG.md
notes/style-guide.md
src/Data/List/Relation/Unary/All/Properties.agda

[ fix #601 ] Deprecated names of all filter properties

---

README.agda
README/Interleaving.agda

[ doc ] interleaving

---

CHANGELOG.md
src/Codata/Musical/Colist/Infinite-merge.agda
src/Induction/WellFounded.agda

[ fix #610 ] Removed hyphens from names of WellFounded submodules

---

CHANGELOG.md
src/Algebra/FunctionProperties/Consequences.agda
src/Algebra/FunctionProperties/Consequences/Core.agda
src/Algebra/FunctionProperties/Consequences/Propositional.agda

[ fix #665 ] Generalised the sel-idem proof in `Algebra.FunctionProperties.Consequences`

---

src/Data/Fin/Substitution/Lemmas.agda

The fix of https://github.com/agda/agda/issues/3650 required a change to the splitting strategy of Agda, however this changes the case tree for the `lookup` function which in turn produces unsolved constraints in Data.Fin.Substitution.Lemmas. This PR adds the necessary implicit arguments to make the file also check with the alternative splitting strategy.

Update library to work after fix of #3650

---

.travis.yml

I should have used a PR originally...

[ travis ] fix build

---

src/Data/List/Base.agda
src/Data/List/Properties.agda

An experiment with the new `variable` key word informed by the discussion in #697. This was enormously satisfying to do :smile: Comments welcome.

[ refactor ] Experimenting with variables in `Data.List`

---

CHANGELOG.md
src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda

Something @pigworker just mentioned.

[ new ] concat⁺ for the sublist relation

---

src/Relation/Binary/HeterogeneousEquality.agda
src/Relation/Binary/HeterogeneousEquality/Core.agda

I use this to have travis check if the changes in het.eq. break code in the library.
Fixes #646.

[ Fix #646 ] Generalize Heterogeneous Equality.

---

src/Relation/Binary/Reasoning/MultiSetoid.agda

Fixes #715 by re-implementing `Reasoning.MultiSetoid` on it's own terms rather than going through `Reasoning.Setoid`. 
I think this fixes the problems, at least I can't seem to break it. @JLimperg could you give it a whirl and let me know?

[ #715 ] Fixed the bug in `Reasoning.MultiSetoid` reasoning by reimplementing it.

---

CHANGELOG.md
src/Data/Word.agda
src/Data/Word/Base.agda
src/Data/Word/Properties.agda

Word prop: Define the induced relations, prove some of their properties

---

HACKING.md

Mostly opening the PR for visibility. :)
I finally looked into it and it turns out it's a lot easier than I anticipated!

[ hacking ] documenting git pre-commit hooks

---

.travis.yml
GNUmakefile

Following @WolframKahl's advice on the mailing list, this speeds up type checking by 20-25% on my laptop.

[ close #416 ] Adding RTS options

---

CHANGELOG.md
src/Data/List/Relation/Binary/Permutation/Homogeneous.agda
src/Data/List/Relation/Binary/Permutation/Setoid.agda
src/Reflection.agda

Added List permutation relation for setoid equalities

---

CHANGELOG.md
src/Level.agda

Also few typos fixed in CHANGELOG.md.

Export Setω in Level

---

CHANGELOG.md
README.agda
README/Text.agda
src/Data/String/Base.agda
src/Text/Format.agda
src/Text/Printf.agda

[ fix #767 ] Format strings and Printf

---

CHANGELOG.md
src/Data/Fin/Base.agda

Added some constants to `Data.Fin.Base`

---

CHANGELOG.md
src/Data/List/Categorical.agda
src/Data/List/NonEmpty/Categorical.agda
src/Data/Maybe/Categorical.agda
src/Data/Product/Categorical/Left.agda
src/Data/Product/Categorical/Right.agda
src/Data/Sum/Categorical/Left.agda
src/Data/Sum/Categorical/Right.agda
src/Data/These/Categorical/Left.agda
src/Data/These/Categorical/Right.agda
src/Data/Vec/Categorical.agda

Name `Traversable` modules in `Data.X.Categorical`

---

CHANGELOG.md
src/Algebra/Properties/Group.agda
src/Algebra/Properties/Ring.agda

Please let me know if there is a better name for `ε⁻¹≈ε`.

Add `ε⁻¹≈ε` and cancellative properties to `Algebra.Properties.Group`

---

src/Data/List/Relation/Binary/Sublist/Heterogeneous/Core.agda
src/Data/List/Relation/Unary/AllPairs.agda
src/Data/List/Relation/Unary/AllPairs/Core.agda
src/Data/List/Relation/Unary/Unique/Setoid.agda

This is a possible fix for #718 adopting the same strategy we used in the Sublist case.

[ fix #718 ] Fix unsolved metas in propositional uniqueness

---

src/Function/Nary/NonDependent.agda

Reviewer asked whether it was provable, may as well throw it in!

[ new ] congAt : a = b -> f vs a ws = f vs b ws

---

CHANGELOG.md
src/Level.agda

this can make definitions involving universe polymorphism easier.

add a function `levelOf`

---

.travis.yml

Fast forward to a commit where Arg is level polymorphic.

[ travis ] bump dev version of Agda

---

README.md

[ fix #859 ] Add a link to the index to the front-page

---

CHANGELOG.md
src/Data/List/Relation/Unary/All.agda
src/Data/List/Relation/Unary/All/Properties.agda
src/Data/Vec/Properties.agda

Made updateAt of List.All analogous to updateAt of Data.Vec.

[ List.All ] points-to relation and props of updateAt modelled after Vec

---

CHANGELOG.md
src/Data/String.agda
src/Data/String/Base.agda
src/Reflection/Argument/Relevance.agda
src/Reflection/Argument/Visibility.agda
src/Reflection/Definition.agda
src/Reflection/Literal.agda
src/Reflection/Pattern.agda
src/Reflection/Term.agda

I found having some show functions around very useful for debugging when playing around with tactics, so thought I would share my utility.
There's plenty of design decisions to discuss, I'm sure.

Show functions for reflection things

---

CHANGELOG.md
src/Data/Nat/Properties.agda

Clearing out my own `Data.Nat.Properties` again. Fixes #834.

Added some more properties to Data.Nat.Properties

---

CHANGELOG.md
GenerateEverything.hs
src/Foreign/Haskell.agda
src/Foreign/Haskell/Coerce.agda
src/Foreign/Haskell/Either.agda

I need `Either` for my sized IO library.

[ fix #903 ] Adding Foreign.Haskell.Either

---

src/Reflection/Pattern.agda

Building my tactic (more about the tools I had to implement in the near future)
was a lot easier thanks to @fredrikNordvallForsberg's show functions. I spotted
that small bug in the process.

[ fix ] lack of space between two patterns

---

CHANGELOG.md
src/Data/Nat/Binary/Properties.agda
src/Data/Nat/Properties.agda
src/Relation/Binary/Morphism.agda
src/Relation/Binary/Morphism/RawOrder.agda
src/Relation/Binary/Morphism/RawRelation.agda

also refactored `Data.Nat.Binary` to use them. Haven't refactored `Data.Rational` yet, that's coming.

Add homomorphisms over binary relations 

---

CHANGELOG.md
src/Relation/Binary/Structures.agda

Fix missing exports in `Relation.Binary.Structures`

---

CHANGELOG.md
src/Data/List/Properties.agda

Added more filter lemmas

---

CHANGELOG.md
src/Algebra/Bundles.agda
src/Algebra/Solver/Ring.agda
src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
src/Algebra/Solver/Ring/Lemmas.agda
src/Algebra/Solver/Ring/NaturalCoefficients.agda

Added equality relation to `RawRing`

---

CHANGELOG.md
src/Data/Fin/Base.agda
src/Data/Fin/Patterns.agda

Moved patterns in `Data.Fin.Base` to `Data.Fin.Patterns`

---

CHANGELOG.md
src/Data/Fin/Base.agda
src/Data/Fin/Permutation/Components.agda
src/Data/Fin/Properties.agda
src/Data/Nat/DivMod.agda

Fixes #862. Let me know if anyone's aware of any that I've missed...
As discussed in the #862 I've left irrelevance in for `Data.Rational` as losing propositional equality over Q is not a sacrifice I'm willing to make!

Remove unnecessary uses of irrelevance

---

CHANGELOG.md
src/Data/BoundedVec.agda
src/Data/BoundedVec/Inefficient.agda

Deprecate `Data.BoundedVec`

---

CHANGELOG.md
src/Codata/Stream.agda

Give `Codata.Stream.tail` a more general type

---

src/Data/Unit/Polymorphic/Properties.agda

Make levels explicit in `Data.Unit.Polymorphism.Properties`

---

CHANGELOG.md
src/Data/Bool/Properties.agda
src/Data/Fin/Subset.agda
src/Data/Fin/Subset/Induction.agda
src/Data/Fin/Subset/Properties.agda

Sorry if this is not notable enough changes. I needed to use well-founded induction over the subsets in my project for which I needed to define subset relationship and I decided to attempt to upstream my attempt (I haven't ported the well-founded relationship yet). I'm still learning AGDA so I'm sorry if code is unidiomatic et.c
I added `⊂′` as well to mirror the relation definition though I founded it more difficult to prove properties of.

Proper subset relations

---

src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
src/Data/List/Relation/Unary/Any/Properties.agda

Add implicit arguments required after fix of agda/agda#4174

---

LICENCE
README.agda

Have authored enough bits to add myself to the author lists.

---

CHANGELOG.md
src/Data/List/Relation/Unary/All/Properties.agda

Fix naming inconsistency in Data.List.Relation.Unary.Any.Properties

---

README.md

Minor correctness check and more salient, decriptive links.
Here are some standard [guidelines on writing hyperlinks](https://www.nngroup.com/articles/writing-links/), maybe an excerpt about how to write usable links could be included in the style guide?

[minor] checked punctuation, grammar, descriptive links

---

CHANGELOG.md
src/Relation/Binary/Bundles.agda
src/Relation/Binary/Structures.agda

Fixes various missing things in the `Eq` modules.

Standardised Eq modules in `Relation.Binary` hierarchy

---

CHANGELOG.md
src/Data/Fin/Properties.agda

lift-injective : ∀ {m n} (f : Fin m → Fin n) →
(∀ {x y} → f x ≡ f y → x ≡ y) →
∀ k {x y} → lift k f x ≡ lift k f y → x ≡ y

Add property lift-injective to Data.Fin.Properties.

---

CHANGELOG.md
README.agda
README/Text/Tree.agda
src/Data/List/Base.agda
src/Data/Tree/Rose.agda
src/Data/Tree/Rose/Properties.agda
src/Text/Tree/Linear.agda

We should be able to embed any other finite tree into a rose tree
so this is highly reusable.

[ new ] pretty printing of rose trees

---

CHANGELOG.md
src/Data/List/Relation/Binary/Permutation/Setoid.agda
src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
src/Data/Nat/Properties.agda

These are some extremely unpleasant lemmas to prove. I'm sure they can probably be optimised further, particularly `drop-mid` but I think it's more important to save other people the pain and get them in as is.

Generalised some permutation lemmas from propositional to setoid equality

---

CHANGELOG.md
src/Algebra/Morphism/Definitions.agda
src/Relation/Binary/Morphism/Definitions.agda

Tidied up types in morphism definitions

---

CHANGELOG.md
src/Function/Bundles.agda
src/Function/Structures.agda

New records BiEquivalence and BiInverse in Function.Bundles
New record IsBiInverse in Function.Structures
#1055

inclusion of Function.Structures.BiInverse

---

notes/style-guide.md

Lots of additions to the style guide that I've been saving up. Comments and feedback welcome! Hopefully nothing to controversial :worried:

Various additions to the style guide

---

CHANGELOG.md
src/Data/List/Relation/Binary/Permutation/Propositional.agda

Smarter trans for propositional permutations

---

CHANGELOG.md
src/Reflection.agda
src/Reflection/TypeChecking/MonadSyntax.agda
src/Tactic/MonoidSolver.agda
src/Tactic/RingSolver.agda

Minor refactor to make way for making the suggestions in #1106 in v1.4.

Rename Reflection.TCMonadSyntax to Reflection.TypeChecking.MonadSyntax

---

CHANGELOG/v1.4.md
src/Data/Tree/Binary.agda
src/Data/Tree/Binary/Properties.agda
src/Data/Tree/Binary/Relation/Unary/All.agda
src/Data/Tree/Binary/Relation/Unary/All/Properties.agda
src/Data/Tree/Binary/Zipper.agda
src/Data/Tree/Binary/Zipper/Properties.agda
src/Text/Pretty/Core.agda

Merged leaf based and node based binary trees into one then added zippers
attempt number 2 at #1123 
cc @gallais 
~~wip as I would like to add functions to add to a zipper (like _++l_ and _++r_ in the list zipper file)~~

Tree zippers attempt 2

---

CHANGELOG.md
src/Data/Fin/Induction.agda

Added `<-wellFounded` in `Data.Fin.Induction`

---

CHANGELOG.md
src/Data/Nat/Base.agda
src/Data/Nat/Properties.agda

Change definition of `pred` to `n ∸ 1`

---

README.agda
README/Design/Decidability.agda
README/Design/Hierarchies.agda

This attempt at improving the explanation of how the different record hierarchies are laid out has been sitting on a local branch for at least the past 9 months. Finally got around to tidying it up a bit. 
I'm sure there are a ton of inaccuracies or places where it could be improved, so feedback welcome!

Updated the documentation for the record hierarchies

---

src/Data/Nat/Properties.agda

Fix 2 incorrect deprecation warnings in `Data.Nat.Properties`

---

CHANGELOG/v1.4.md
src/Data/Product/Properties.agda
src/Data/Product/Properties/WithK.agda

Moved some proofs from Data.Product.Properties.WithK to Data.Product.Properties. Probably needs a changelog entry

Decidablity of dependent products

---

CHANGELOG.md
src/Data/Nat/Binary/Properties.agda
src/Data/Nat/Properties.agda
src/Data/Nat/Solver.agda
src/Data/Nat/Tactic/RingSolver.agda

Deprecate *-+- algebraic structures/bundles in favour of +-*-

---

.travis.yml
src/Reflection/Pattern.agda
src/Reflection/Show.agda
src/Reflection/Term.agda

This PR includes the required changes to the standard library that should be made together with https://github.com/agda/agda/pull/4722

Update decidable equality of reflected syntax

---

CHANGELOG.md

Changelog for #1226

---

CHANGELOG.md
src/Text/Format.agda
src/Text/Format/Generic.agda
src/Text/Printf.agda
src/Text/Printf/Generic.agda

Part 2 of printf generalization.
On top of #1234, can rebase when that's merged.

Generalize printf

---

CHANGELOG.md
src/Reflection/TypeChecking/Format.agda
src/Reflection/TypeChecking/Monad.agda

Now using generic printf from #1235.

Printf for reflection type errors

---

src/Function/Related/TypeIsomorphisms.agda

Fixes problem reported by @nad on the comments in that PR.

fix problem reported on PR #1204

---

CHANGELOG.md
src/Data/List/Properties.agda
src/Data/List/Relation/Unary/Any/Properties.agda

Add proofs reverse-injective, reverse⁺ and reverse⁻

---

CHANGELOG.md
src/Data/Vec/Properties.agda

Add proofs take-step and lookup-inject≤-take

---

src/Induction/Nat.agda

Hide Data.Fin.Induction.<-wellFounded in Induction.Nat

---

CHANGELOG.md
src/Data/List/Countdown.agda
src/Data/List/Membership/DecSetoid.agda
src/Data/List/Relation/Unary/All.agda
src/Data/List/Relation/Unary/AllPairs.agda
src/Data/List/Relation/Unary/Any.agda
src/Data/List/Relation/Unary/Grouped.agda
src/Data/Vec/Membership/DecSetoid.agda
src/Data/Vec/Relation/Unary/All.agda
src/Data/Vec/Relation/Unary/AllPairs.agda
src/Data/Vec/Relation/Unary/Any.agda

Rename all and any to all? and any? for consistency

---

CHANGELOG.md
src/Data/Tree/Binary/Properties.agda

I was looking for these when working on `categories-examples`.

Add more properties to Data.Tree.Binary.Properties

---

CHANGELOG.md
src/Category/Applicative/Indexed.agda
src/Category/Applicative/Predicate.agda
src/Data/Product.agda
src/Data/Sum/Base.agda
src/Data/These.agda
src/Function/Base.agda
src/Function/Definitions.agda

This pull request proposes the addition of the composition of a binary function with two unary functions, a features which was missing, although very useful. It is defined using the composition of three binary functions, and allows a new definition of the composition of a binary function with a unary function.

Additional compositions with binary functions

---

CHANGELOG.md

Addressing https://github.com/agda/agda-stdlib/pull/1109#discussion_r478589695.

[ changelog ] document new functions in Data.Product

---

CHANGELOG.md
src/Reflection/DeBruijn.agda
src/Reflection/Traversal.agda

Using it to implement weakening, strengthening and free variable check.
This is the `Agda-2.6.1` version of #1294 suitable for `master`.

Generic traversals of reflected terms

---

CHANGELOG.md
src/Algebra/Bundles.agda
src/Algebra/Morphism/Structures.agda

Part of issue #1297. Work in progress. Feedback most appreciated (as picky as you want!).

(Near)Semiring & Lattice morphisms

---

CHANGELOG.md
src/Reflection/Universe.agda

Preparation for annotated reflected terms as defined here: [wenkokke/schmitty: Reflection.Annotated](https://github.com/wenkokke/schmitty/blob/master/src/Reflection/Annotated.agda)
Part 2: #1325

Add Reflection.Universe

---

CHANGELOG.md
src/Algebra/Construct/Zero.agda
src/Algebra/Module/Construct/Zero.agda

Level polymorphism for Algebra.Construct.Zero and Algebra.Module.Construct.Zero

---

src/Data/List/Relation/Unary/All.agda

Add `All.lookup` over setoid membership

---

CHANGELOG.md
src/Data/Product.agda

By analogy with the sigma syntax

Add infix declartions to exists syntax

---

CHANGELOG.md
src/Data/Sign/Properties.agda

I was surprised they didn't exist. I was looking for them while writing my modular arithmetic library.

Add opposite lemmas to Data.Sign

---

CHANGELOG.md
src/Data/List/Base.agda
src/Data/String/Base.agda

Fix for https://github.com/agda/agda-stdlib/commit/eb338fd27861f8c9db1359fda6e0ad24df555ae0#r44894245

[ fix ] lines should not drop empty lines

---

CHANGELOG.md
GenerateEverything.hs
src/System/Exit.agda
src/System/Exit/Primitive.agda

Continuing on my quest to write executables in Agda.

[ new ] bindings for Haskell's System.Exit

---

GNUmakefile

[ fixed #1383 ] Removed v1-commands.

---

CHANGELOG.md
src/Data/List/Base.agda
src/Data/List/Extrema.agda
src/Data/List/Membership/DecPropositional.agda
src/Data/List/Membership/DecSetoid.agda
src/Data/List/Membership/Propositional/Properties.agda
src/Data/List/Membership/Setoid/Properties.agda
src/Data/List/Relation/Binary/Sublist/Setoid.agda
src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
src/Data/List/Relation/Unary/Any/Properties.agda
src/Data/List/Relation/Unary/Unique/DecPropositional.agda
src/Data/List/Relation/Unary/Unique/DecPropositional/Properties.agda
src/Data/List/Relation/Unary/Unique/DecSetoid.agda
src/Data/List/Relation/Unary/Unique/DecSetoid/Properties.agda
src/Data/List/Relation/Unary/Unique/Setoid.agda
src/Relation/Binary/PropositionalEquality/Core.agda

Clearing out my own development of various bits and pieces about lists.

Add various lemmas about list relations

---

CHANGELOG.md
src/Data/Nat/PseudoRandom/LCG.agda

After looking at #1365, I had another idea possibly related to
efficiency and decided I wanted to benchmark the patch. I had
to copy/paste this which convinced me I may as well put in the
stdlib.

[ new ] pseudo random generators

---

CHANGELOG.md
src/Data/List/Relation/Binary/Equality/Setoid.agda
src/Data/List/Relation/Binary/Pointwise.agda
src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda

Also took the opportunity to replace a lot of the anonymous modules with variables.

Added new proofs about `Pointwise` relation for `List`s

---

CHANGELOG.md
src/Algebra/Solver/Ring/NaturalCoefficients/Default.agda
src/Algebra/Solver/Ring/Simple.agda
src/Data/Bin.agda
src/Data/Bin/Properties.agda
src/Data/List/Relation/Binary/Lex/Strict.agda
src/Data/Nat/Binary/Properties.agda
src/Data/Product/Relation/Binary/Lex/NonStrict.agda
src/Data/Product/Relation/Binary/Lex/Strict.agda
src/Data/Star/Vec.agda
src/Data/Vec/Relation/Binary/Lex/Strict.agda
src/Relation/Binary/Consequences.agda
src/Relation/Binary/Construct/StrictToNonStrict.agda
src/Relation/Binary/HeterogeneousEquality.agda
src/Relation/Binary/Properties/TotalOrder.agda
src/Relation/Binary/Structures.agda

Replaced uses of ⟶ with ⇒ in names in `Relation.Binary.Consequences`

---

CHANGELOG.md
src/Data/Nat/DivMod.agda
src/Data/Nat/Divisibility/Core.agda
src/Data/Nat/GCD.agda
src/Data/Nat/Properties.agda
src/Data/Rational/Base.agda
src/Data/Rational/Properties.agda
src/Data/Rational/Unnormalised/Properties.agda
src/Relation/Binary/Morphism/OrderMonomorphism.agda

Various improvements to ℚ and ℤ

Add min/max/absolute value for ℚ

---

CHANGELOG.md
src/Codata/Stream.agda

Came across this cute `cantor` function while formalising Liam's paper in
Idris so thought I'd see how it fairs with sized codata.
Also threw in `interleave⁺` which is very easy 	to define with sized types :)

[ new ] more interleaving functions in Codata.Stream

---

CHANGELOG.md
src/Relation/Binary/Reasoning/Base/Partial.agda
src/Relation/Binary/Reasoning/Base/Single.agda
src/Relation/Binary/Reasoning/PartialSetoid.agda
src/Relation/Binary/Reasoning/Setoid.agda

Closes #1446 
one nice thing about this modification is that no change to use sites is required.

readjust reasoning APIs

---

CHANGELOG.md
src/Function/Properties/Equivalence.agda
src/Function/Properties/Inverse.agda

Fixes agda/agda-stdlib#1460

---

CHANGELOG.md
src/Data/List/Relation/Unary/Enumerates/Setoid.agda
src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda

Renamed new `Complete` list predicate to `IsEnumeration`

---

GenerateEverything.hs

Everything has a rational explanation, even this haunting, but I won't bother to get to the bottom of this...

[ Fix #1510 ] Work around GHC bug introduced in 8.2

---

.github/workflows/ci-ubuntu.yml

I wrote some doc for https://github.com/agda/agda-categories/pull/285
so we may as well have some in the stdlib repo too!

[ ci ] doc for the actions script

---

CHANGELOG.md
src/Function/Construct/Symmetry.agda
src/Function/Properties/Bijection.agda
src/Function/Properties/Equivalence.agda
src/Function/Properties/Inverse.agda

These don't exist in the old hierarchy so this isn't progress towards closing #759, but they've been floating around in my own library.

Added some basic properties of bijections (new function hierarchy)

---

src/Data/Nat/Properties.agda

I don't see any benefit to the definition with transitivity and reflexivity.

Simplify definition of Data.Nat.Properties.<⇒≤

---

CHANGELOG.md
src/Relation/Unary/Polymorphic.agda

polymorphic versions of empty and universal sets

---

CHANGELOG.md
src/Data/List/Properties.agda

Data.List.Properties: rename zipWith-identity to zipWith-zero

---

CHANGELOG.md
src/Algebra.agda
src/Algebra/Consequences/Setoid.agda
src/Algebra/Structures/Biased.agda

Re-export `Algebra.Structures.Biased` from `Algebra` and tidy up

---

notes/style-guide.md

I have:
- Corrected some minor typos, and improved grammar for clarity
- Added some extra guidelines to reflect comments made on #1585, which weren't previously stated in the style guide.

Minor improvements to style guide

---

CHANGELOG.md
src/Relation/Binary/PropositionalEquality/Properties.agda

I'm not at all sure about the names, so feel free to make a suggestion. I'll write the changelog once we've agreed on the names. Also let me know if there's other similar properties that you'd like to have.

Add a couple of missing equality operators

---

.github/workflows/ci-ubuntu.yml
agda-stdlib-utils.cabal

First attempt at fixing issue #1618 (not linked so as to avoid closing it).

Bump cabal file package upper bounds

---

CHANGELOG.md
src/Data/List/Fresh/NonEmpty.agda

Data.List.Fresh.NonEmpty

---

CHANGELOG.md
src/Data/Vec/Relation/Binary/Equality/Setoid.agda
src/Relation/Binary/Lattice/Properties/BoundedJoinSemilattice.agda
src/Relation/Binary/Lattice/Properties/BoundedLattice.agda
src/Relation/Binary/Lattice/Properties/BoundedMeetSemilattice.agda
src/Relation/Binary/Lattice/Properties/DistributiveLattice.agda
src/Relation/Binary/Lattice/Properties/JoinSemilattice.agda
src/Relation/Binary/Lattice/Properties/Lattice.agda
src/Relation/Binary/Lattice/Properties/MeetSemilattice.agda
src/Relation/Binary/Properties/BoundedJoinSemilattice.agda
src/Relation/Binary/Properties/BoundedLattice.agda
src/Relation/Binary/Properties/BoundedMeetSemilattice.agda
src/Relation/Binary/Properties/DistributiveLattice.agda
src/Relation/Binary/Properties/HeytingAlgebra.agda
src/Relation/Binary/Properties/JoinSemilattice.agda
src/Relation/Binary/Properties/Lattice.agda
src/Relation/Binary/Properties/MeetSemilattice.agda

Move Relation.Binary.Properties.XLattice to Relation.Binary.Lattice.Properties.XLattice

---

CHANGELOG.md
src/Algebra/Module.agda

Create  Algebra.Module summary module 

---

CHANGELOG.md
src/Algebra/Properties/CommutativeSemigroup.agda

Also improved formatting in the file (so ignore the whitespace changes).

Added interchange property for commutative semigroups

---

CHANGELOG.md
src/Algebra/Definitions/RawSemiring.agda

Correct definition of Prime in `Algebra.Definitions.RawSemiring`

---

CHANGELOG.md
src/Data/Integer/Properties.agda
src/Data/Rational/Properties.agda
src/Data/Rational/Unnormalised/Properties.agda

More instance argument fiddling and added some proofs of how the signed predicates relate to the operations over unnormalised rationals.

Fixed #1646 and added more proofs to `Data.Rational.Unnormalised.Properties`

---

CHANGELOG.md
src/Data/Fin/Permutation.agda
src/Data/Fin/Permutation/Components.agda
src/Data/Fin/Properties.agda
src/Data/Graph/Acyclic.agda

Deprecate `reverse` in `Data.Fin.Permutation.Components`

---

src/Data/Maybe/Categorical.agda

With this modification, variables will be at the top like in most files of this repository.

private variable in Maybe

---

CHANGELOG.md
src/Data/Nat/Primality.agda

Add definitions of compositeness

---

CHANGELOG.md
src/Data/Fin/Permutation.agda

I defined this in the progress of proving that there's an isomorphism between `Fin (n !)` and `Pemutation m n` but I haven't finished that yet.

Add insert to Data.Fin.Permutations as rough inverse to remove

---

CHANGELOG.md
README/Tactic/Cong.agda
src/Tactic/Cong.agda

Renamed Tactic.Rewrite to Tactic.Cong

---

.github/workflows/haskell-ci.yml
.gitignore
src/Data/Nat/Tactic/RingSolver.agda
src/Reflection/Term.agda

Will Fix #1649  , and  #1651 
Will fix a part of #1380 
For #1523 the CICD says "Unable to locate package ghc-8.10.5"

Minor fixes  `#1649` ,` #1523` , and  `#1651` 

---

CHANGELOG.md
src/Data/List/NonEmpty/Base.agda
src/Data/List/NonEmpty/Properties.agda

add properties of nonempty list

---

CHANGELOG.md
notes/style-guide.md
src/Data/List/Properties.agda

Today I felt a need for this small lemma and thought it would be worthwhile to share.
This is my first contribution to stdlib. I'm open to all kinds of suggestions! :-)

Add small lemma relating ∷ʳ and ++

---

src/Algebra/Construct/DirectProduct.agda
src/Algebra/Structures.agda

Add congruence property to IsInvertibleMagma

---

src/Data/Digit.agda
src/Data/Integer/DivMod.agda
src/Data/Integer/Properties.agda
src/Data/List/Properties.agda
src/Data/List/Relation/Binary/Infix/Heterogeneous/Properties.agda
src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda
src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
src/Data/List/Relation/Unary/All/Properties.agda
src/Data/List/Relation/Unary/Any/Properties.agda
src/Data/List/Relation/Unary/Linked/Properties.agda
src/Data/List/Relation/Unary/Sorted/TotalOrder/Properties.agda
src/Data/List/Sort/MergeSort.agda
src/Data/Rational/Properties.agda
src/Data/Rational/Unnormalised/Properties.agda

These are some loose ends from `#1709`. No changes to record in `CHANGELOG`.

Pr#1709 bis

---

src/Algebra/Morphism/Construct/Composition.agda
src/Algebra/Morphism/Construct/Identity.agda
src/Algebra/Morphism/Structures.agda

I forgot to make changes in new branch. Hopefully this gets merged quickly :)

Morphism identity and composition construction for RingWithoutOne

---

src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda

@gallais Will these be unified after the change in #1761? If so, I could base my PR onto yours if you wish.

List.Permutation: simplify ++-comm proofs

---

CHANGELOG.md
src/Data/Rational/Base.agda
src/Data/Rational/Properties.agda
src/Data/Rational/Unnormalised/Base.agda
src/Data/Rational/Unnormalised/Properties.agda

Closes #1753. Haven't addressed the problem with integer multiplication.

Try to improve reduction behaviour of rationals using Andreas's suggestion

---

.github/workflows/ci-ubuntu.yml

It should hopefully fix #1774
It seems to be working for schmitty: https://github.com/wenkokke/schmitty/blob/master/.github/workflows/ci-ubuntu.yml

[ ci ] bump version numbers

---

CHANGELOG.md
src/IO/Base.agda

Add IO.Base.untilRight

---

src/Algebra/Bundles.agda
src/Algebra/Construct/DirectProduct.agda
src/Algebra/Properties/CommutativeSemigroup.agda
src/Algebra/Properties/Semigroup.agda
src/Algebra/Structures.agda

In this PR
- Add missing fixity
- Use superscript for semimedial and alternative
Sorry for missing this in previous PR :)

Use superscript and add missing fixity

---

CHANGELOG.md
src/Algebra/Lattice/Properties/BooleanAlgebra.agda
src/Algebra/Properties/CommutativeMonoid/Sum.agda
src/Algebra/Properties/Lattice.agda
src/Data/List/NonEmpty.agda
src/Data/List/Relation/Unary/Grouped/Properties.agda
src/Data/Vec/N-ary.agda
src/Effect/Monad/Partiality.agda
src/Relation/Binary/Reflection.agda

change some dependencies to use the new function hierarchy

---

CHANGELOG.md
src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda
src/Data/List/Relation/Unary/Any/Properties.agda

Remove remaining map-with-∈  names

---

.github/workflows/ci-ubuntu.yml
agda-stdlib-utils.cabal
src/Data/Float/Base.agda
src/Data/Float/Properties.agda

Required changes for agda/agda#6156. The issue is agda/agda#6093.
**THIS SHOULD NOT BE MERGED INTO `master`**, but it seems `experimental` is not up to date?

primFloatToWord64 now returns a Maybe

---

CHANGELOG.md
src/Algebra/Properties/Magma/Divisibility.agda

in `Algebra.Properties.Magma.Divisibility`

Fix #1535 by re-exporting additional divisibility definitions

---

CHANGELOG.md
src/Data/Parity/Properties.agda

Hopefully this is now a clean version... third time is the charm?

[fixes #1894] parity is a semiring homomorphism

---

CHANGELOG.md
src/Data/Tree/AVL.agda
src/Data/Tree/AVL/Indexed/Relation/Unary/Any/Properties.agda
src/Data/Tree/AVL/IndexedMap.agda
src/Data/Tree/AVL/Map.agda
src/Data/Tree/AVL/Map/Membership.agda
src/Data/Tree/AVL/Map/Membership/Propositional.agda
src/Data/Tree/AVL/Map/Membership/Propositional/Properties.agda
src/Data/Tree/AVL/Sets.agda
src/Data/Tree/AVL/Sets/Membership.agda
src/Data/Tree/AVL/Sets/Membership/Properties.agda

- Prove lemmas about singleton, insert, and lookup

Define membership relation for Data.Tree.AVL

---

CHANGELOG.md
src/Data/List/Membership/Propositional/Properties.agda
src/Data/List/Membership/Setoid/Properties.agda

This was suggested following a question in the Zulip chat (https://agda.zulipchat.com/#narrow/stream/259644-newcomers/topic/Trying.20to.20prove.20a.20proposition.20about.20lists)

Add proofs for List mapWith∈

---

CHANGELOG.md
src/Data/Nat/Binary/Properties.agda

I also moved `suc≢0` upward in the file slightly because it felt like a more appropriate place to me

Add suc-injective to Data.Nat.Binary.Properties

---

CHANGELOG.md
src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda

* Added new function to ↭-reverse of List.
```agda
↭-reverse : (xs : List A) → reverse xs ↭ xs
```

Added reverse permutation

---

CHANGELOG.md
src/Data/List/Properties.agda

Add lemmas `take-[]` and `drop-[]`  to std library. In Data.List.Properties.

add take-[] and drop-[] to stdl Data/List/Properties.agda

---

CHANGELOG.md
src/Data/Bool/Properties.agda

(plus tidies up some typos in `CHANGELOG`)

fixes #2046

---

src/Reflection/AST/Abstraction.agda
src/Reflection/AST/AlphaEquality.agda
src/Reflection/AST/Argument.agda
src/Reflection/AST/Argument/Information.agda
src/Reflection/AST/Argument/Modality.agda
src/Reflection/AST/Argument/Quantity.agda
src/Reflection/AST/Argument/Relevance.agda
src/Reflection/AST/Argument/Visibility.agda
src/Reflection/AST/Definition.agda
src/Reflection/AST/Literal.agda
src/Reflection/AST/Meta.agda
src/Reflection/AST/Name.agda
src/Reflection/AST/Show.agda
src/Reflection/AST/Term.agda
src/Reflection/AST/Traversal.agda

Refine imports in `Reflection.AST`

---

CHANGELOG.md

But is this the occasion to address anything else about `CHANGELOG` that 's easy to fix right now?

fixes #1990

---

CHANGELOG.md
src/Data/Fin/Permutation.agda
src/Function/Construct/Composition.agda
src/Function/Properties/Inverse.agda
src/Function/Related/Propositional.agda

Fixes https://github.com/agda/agda-stdlib/issues/2105

Fix argument order of composition operators

---

LICENCE

As per @jamesmckinna's request

[ fix ] missing name in LICENCE file

---

CHANGELOG.md

Well that was painful! It's only 3784 lines long now down from 4000 :sweat_smile:

Tidy up CHANGELOG in preparation for release candidate

---

CHANGELOG.md

Apologies for the `revert`, I found myself working on `master` by accident. Cherry-picking the first commit should suffice!

v2.0-rc1 spellcheck

---

src/Relation/Binary/Definitions.agda

Connex allows both relations to hold, so the old comment was wrong.

fix Connex comment

---

CHANGELOG.md
src/Data/Vec/Properties.agda

Mea culpa! I am the author of this typo.

fix toList-replicate's statement about vectors

---

CHANGELOG.md
src/Data/List/Properties.agda

It's nice to show that the two lists have the same actual contents, just in a different order

Some properties of upTo and downFrom

---

.github/workflows/whitespace.yml

Run `fix-whitespace --check` on PRs and pushes.
Triggers (`on`)  copied from main CI.
This is a very cheap workflow, should finish in seconds.
It currently finds some violations, but these will be fixed by:
- #2325

Github action to check for whitespace violations

---

src/Data/Container/FreeMonad.agda

I assume that was the intention -- sorry if not!

mark variables private in Data.Container.FreeMonad

---

src/Algebra/Morphism.agda

Tiny PR that fixes a silly bug.

fix warning: it was pointing to a record that did not exist.

---

src/Algebra/Solver/Monoid.agda
src/Axiom/UniquenessOfIdentityProofs.agda
src/Data/Bool/Properties.agda
src/Data/Char/Properties.agda
src/Data/List/Membership/DecPropositional.agda
src/Data/List/Membership/Propositional/Properties.agda
src/Data/List/Relation/Binary/Equality/DecPropositional.agda
src/Data/List/Relation/Binary/Sublist/DecPropositional.agda
src/Data/List/Relation/Binary/Sublist/DecPropositional/Solver.agda
src/Data/Maybe/Properties.agda
src/Data/Nat/Binary/Properties.agda
src/Data/Record.agda
src/Data/String/Properties.agda
src/Data/Sum/Properties.agda
src/Data/These/Properties.agda
src/Data/Unit/Polymorphic/Properties.agda
src/Data/Unit/Properties.agda
src/Data/Vec/Membership/DecPropositional.agda
src/Data/Vec/Relation/Binary/Equality/DecPropositional.agda
src/Effect/Monad/Partiality.agda
src/Reflection/AST/Term.agda
src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
src/Relation/Binary/PropositionalEquality/Properties.agda

Addresses [comment](https://github.com/agda/agda-stdlib/pull/2345#discussion_r1555854588) in #2345
No `CHANGELOG` required!

Systematise use of `Relation.Binary.Definitions.DecidableEquality`

---

CHANGELOG/v1.7.3.md

Added missing v1.7.3 CHANGELOG

---

CHANGELOG.md
src/Data/List/Relation/Binary/Equality/Setoid/Properties.agda

Refactored from #2350 : fixes #2360
Outstanding `library-design` issue (from #2360 ): where should this live?
Downstream issues: what else belongs here (or wherever this ends up)?

Add the `Setoid`-based `Monoid` on `(List, [], _++_)`

---

CHANGELOG.md
src/Data/Vec/Properties.agda

Preparing next year's coursework and I'll need this. :)

[ new ] map-concat

---

CHANGELOG.md
src/Algebra/Properties/CommutativeMagma/Divisibility.agda

Fixes #2245 .
Tightens `import`s.

Rename+deprecate in `Algebra.Properties.CommutativeMagma.Divisibility`

---

doc/release-guide.txt

Spotted in the course of #2473

fix typo in `release-guide`

---

CHANGELOG.md

See [this comment](https://github.com/agda/agda-stdlib/pull/2418#discussion_r1742704532) *et seq.*

fix `CHANGELOG` after #2418

---

CHANGELOG.md
src/Relation/Nullary/Recomputable.agda

Fixes #2495 using @fredrikNordvallForsberg 's solution there.

Add `Relation.Nullary.Recomputable.irrelevant-recompute`

---

CHANGELOG.md
src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda

Add sum-↭ to Data.List.Relation.Binary.Permutation.Propositional.Properties

---

CHANGELOG.md
src/Data/List/Relation/Unary/First/Properties.agda

This follows up #2507 by adding the fourth, de Morgan dual, property, and tidies up the `CHANGELOG`.

[ add ] de Morgan dual of #2507

---

src/Data/List/Properties.agda

A purely cosmetic refactoring in terms of what is already there; no `CHANGELOG` required.

[ refactor ] `Data.List.Properties` of `concatMap`

---

doc/style-guide.md

Following a [suggestion from @Taneb ](https://github.com/agda/agda-stdlib/pull/2338/files/c836675361df459218dfcdb7f51d6849720c2736#r1893793022)

[ add ] layout + boilerplate for deprecation warnings

---

CHANGELOG.md

[ fix ] tidy up alphabetical ordering in `CHANGELOG`

---

CHANGELOG.md
src/Data/List/Properties.agda

I was really surprised I couldn't find this...

Add properties relating upTo/downFrom and map

---

src/Data/DifferenceVec.agda
src/Data/Digit.agda
src/Debug/Trace.agda
src/Effect/Applicative.agda
src/Effect/Applicative/Indexed.agda
src/Effect/Applicative/Predicate.agda
src/Effect/Comonad.agda
src/Effect/Empty.agda
src/Effect/Foldable.agda
src/Effect/Functor.agda
src/Effect/Functor/Predicate.agda
src/Effect/Monad.agda
src/Effect/Monad/Indexed.agda
src/Effect/Monad/Partiality/All.agda
src/Effect/Monad/Reader/Indexed.agda
src/Effect/Monad/State/Indexed.agda
src/Effect/Monad/State/Transformer/Base.agda
src/Effect/Monad/Writer/Indexed.agda
src/Effect/Monad/Writer/Transformer/Base.agda

This update refines import statements across multiple modules, enhancing readability and maintaining consistency in the codebase.

[Import] `Effect`

---

src/Relation/Binary/Construct/Add/Extrema/Equality.agda
src/Relation/Binary/Construct/Add/Extrema/NonStrict.agda
src/Relation/Binary/Construct/Add/Extrema/Strict.agda
src/Relation/Binary/Construct/Add/Infimum/NonStrict.agda
src/Relation/Binary/Construct/Add/Infimum/Strict.agda
src/Relation/Binary/Construct/Add/Point/Equality.agda
src/Relation/Binary/Construct/Add/Supremum/NonStrict.agda
src/Relation/Binary/Construct/Add/Supremum/Strict.agda
src/Relation/Binary/Construct/Closure/Equivalence/Properties.agda
src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda
src/Relation/Binary/Construct/Closure/Reflexive/Properties/WithK.agda
src/Relation/Binary/Construct/Closure/ReflexiveTransitive/Properties.agda
src/Relation/Binary/Construct/Closure/Transitive.agda
src/Relation/Binary/Construct/Composition.agda
src/Relation/Binary/Construct/Constant/Core.agda
src/Relation/Binary/Construct/Flip/EqAndOrd.agda
src/Relation/Binary/Construct/Flip/Ord.agda
src/Relation/Binary/Construct/Interior/Symmetric.agda
src/Relation/Binary/Construct/NaturalOrder/Left.agda
src/Relation/Binary/Construct/NaturalOrder/Right.agda
src/Relation/Binary/Construct/Subst/Equality.agda

Update import statements across multiple modules

[Import] `Relation.Binary.*`

---

src/Relation/Binary/Construct/Composition.agda
src/Relation/Binary/Construct/Constant.agda
src/Relation/Binary/Construct/Intersection.agda
src/Relation/Binary/Construct/Never.agda
src/Relation/Binary/Construct/NonStrictToStrict.agda
src/Relation/Binary/Construct/On.agda
src/Relation/Binary/Construct/StrictToNonStrict.agda
src/Relation/Binary/Construct/Union.agda
src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda
src/Relation/Binary/Indexed/Heterogeneous/Bundles.agda
src/Relation/Binary/Indexed/Heterogeneous/Construct/At.agda
src/Relation/Binary/Indexed/Heterogeneous/Construct/Trivial.agda
src/Relation/Binary/Indexed/Heterogeneous/Core.agda
src/Relation/Binary/Indexed/Heterogeneous/Definitions.agda
src/Relation/Binary/Indexed/Heterogeneous/Structures.agda
src/Relation/Binary/Indexed/Homogeneous/Bundles.agda
src/Relation/Binary/Indexed/Homogeneous/Construct/At.agda
src/Relation/Binary/Indexed/Homogeneous/Core.agda
src/Relation/Binary/Indexed/Homogeneous/Definitions.agda
src/Relation/Binary/Indexed/Homogeneous/Structures.agda

Update import statements across multiple modules to use specific components

[import] `Relation.Construct.*`...`Relation.Index.Homogeneous`

---

src/Relation/Binary/Bundles.agda
src/Relation/Binary/Definitions.agda
src/Relation/Binary/HeterogeneousEquality.agda
src/Relation/Binary/PropositionalEquality.agda
src/Relation/Binary/PropositionalEquality/Core.agda
src/Relation/Binary/PropositionalEquality/Properties.agda
src/Relation/Binary/PropositionalEquality/TrustMe.agda
src/Relation/Binary/PropositionalEquality/WithK.agda
src/Relation/Binary/Reasoning/Base/Triple.agda
src/Relation/Binary/Reasoning/PartialSetoid.agda
src/Relation/Binary/Reasoning/Syntax.agda
src/Relation/Binary/Structures.agda
src/Relation/Binary/Structures/Biased.agda
src/Relation/Nullary/Decidable.agda
src/Relation/Nullary/Decidable/Core.agda
src/Relation/Nullary/Indexed/Negation.agda
src/Relation/Nullary/Negation/Core.agda
src/Relation/Nullary/Recomputable.agda
src/Relation/Nullary/Universe.agda

This update improves the organization of import statements across Binary and Nullary modules

[Import] `Relation.Binary`...`Relation.Nullary`

---

src/Foreign/Haskell.agda
src/Foreign/Haskell/Either.agda
src/Foreign/Haskell/List/NonEmpty.agda
src/Foreign/Haskell/Maybe.agda
src/Foreign/Haskell/Pair.agda
src/Function/Consequences/Propositional.agda
src/Function/Consequences/Setoid.agda
src/Function/Construct/Composition.agda
src/Function/Construct/Constant.agda
src/Function/Construct/Identity.agda
src/Function/Construct/Symmetry.agda
src/Function/Endo/Propositional.agda
src/Function/Endo/Setoid.agda
src/Function/Endomorphism/Propositional.agda
src/Function/Identity/Effectful.agda
src/Function/Metric/Nat/Bundles.agda
src/Function/Metric/Nat/Core.agda
src/Function/Metric/Nat/Definitions.agda
src/Function/Metric/Nat/Structures.agda

Update import statements across multiple modules to use specific functions and types

[Import] `Foreign.Haskell`...`Foreign.Function`

---

src/Relation/Binary/Indexed/Homogeneous/Bundles.agda
src/Relation/Binary/Indexed/Homogeneous/Construct/At.agda
src/Relation/Binary/Indexed/Homogeneous/Definitions.agda
src/Relation/Binary/Indexed/Homogeneous/Structures.agda
src/Relation/Binary/Lattice/Bundles.agda
src/Relation/Binary/Lattice/Definitions.agda
src/Relation/Binary/Lattice/Properties/BoundedJoinSemilattice.agda
src/Relation/Binary/Lattice/Properties/BoundedLattice.agda
src/Relation/Binary/Lattice/Properties/BoundedMeetSemilattice.agda
src/Relation/Binary/Lattice/Properties/DistributiveLattice.agda
src/Relation/Binary/Lattice/Properties/HeytingAlgebra.agda
src/Relation/Binary/Lattice/Properties/JoinSemilattice.agda
src/Relation/Binary/Lattice/Properties/Lattice.agda
src/Relation/Binary/Lattice/Properties/MeetSemilattice.agda
src/Relation/Binary/Lattice/Structures.agda

This update reorganizes and optimizes import statements across various lattice-related modules.

[Import] `Relation.Binary.Indexed ... .Lattice`

---

src/Algebra/Bundles/Raw.agda

[ fix ] remove redundant `import`

---

CHANGELOG.md
src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda

Add some properties of zipWith w.r.t. Pointwise for `Data.Vec`

[add] properties of zipWith to Pointwise (Data.Vec)

---

src/Reflection/TCM/Utilities.agda
src/Tactic/Cong.agda

Refactor import statements in the Cong and Utilities modules.

Update imports in Cong and Utilities modules

---

src/Data/Fin/Permutation.agda
src/Data/Fin/Permutation/Components.agda

Fixes #2743 
No `CHANGELOG` required (v2.0 version had already recorded the correct deprecations!)

[ fix] issue #2743
