notes/future-version.txt, src/Data/Bool/Base.agda, src/Data/Colist.agda, src/Data/List/Base.agda, src/Data/Nat/Base.agda, src/Data/Vec/N-ary.agda, src/Foreign/Haskell.agda, src/IO/Primitive.agda
Adds all the necessary pragmas to use the stdlib with the UHC backend. Does not break typechecking or compilation with MAlonzo, no matter if the UHC backend is enabled or not.
Any objections to me merging this?
=> Support for UHC Backend

CHANGELOG, src/Algebra/FunctionProperties.agda, src/Data/Nat/Properties.agda
Added the Selectivity property for operators. Useful when working with "choice" operators such as "min" or "max".
Obviously being selective implies the operator is idempotent as well. As this is my first contribution I'm a bit hesitant about adding this proof to FunctionProperties.agda as there are no other "properties of properties" proofs so to speak. However looking around I don't think there's any other suitable places... I'm happy to listen to advice!
=> Added the Selectivity property to FunctionProperties

CHANGELOG, src/Relation/Binary/Product/StrictLex.agda
Added an alternative (non-degenerative) proof for totality in Relation.Binary.Product.StrictLex as well as cleaning up the file somewhat.
The original proof only handles the degenerative case (if the first ordering is total then the second ordering isn't used).
=> New totality proof for strict lexicographic products of binary relations

CHANGELOG, src/Data/Vec/All.agda, src/Data/Vec/All/Properties.agda, src/Data/Vec/Properties.agda
This adds some extra support for vectors, in particular
* some `zip`/`unzip`-related properties in `Data.Vec.Properties`, and
* an `All` predicate (similar to `Data.List.All`) and related properties for `Data.Vec`.
=> Add some extra properties and an All predicate for Data.Vec

CHANGELOG.md, src/Algebra/Properties/Lattice.agda, src/Relation/Binary/Lattice.agda, src/Relation/Binary/Properties/BoundedJoinSemilattice.agda, src/Relation/Binary/Properties/BoundedMeetSemilattice.agda, src/Relation/Binary/Properties/JoinSemilattice.agda, src/Relation/Binary/Properties/Lattice.agda, src/Relation/Binary/Properties/MeetSemilattice.agda, src/Relation/Binary/Properties/Poset.agda, src/Relation/Binary/Properties/Preorder.agda
This adds various order-theoretic lattice structures extending `Relation.Binary.Poset`, namely
* join/meet semilattices
* bounded join/meet semilattices
* lattices and bounded lattices
along with related properties, in particular conversions between order-theoretic and algebraic lattices (i.e. instances of `Algebra.Lattice`).
=> Add order-theoretic lattices and some related properties.

CHANGELOG, src/Algebra/FunctionProperties.agda
In my opinion these aliases have three advantages over the existing solution of `_Preserves₂_⟶ _ ⟶ _`
1. More meaningful name
2. Much shorter and therefore cleaner code (`_∙_ Preserves₂ _≈_ ⟶ _≈_ ⟶ _≈_` takes up nearly half a line)
3. More intuitively placed for new-comers to the library who are using the `Algebra` modules. For a property so vital during algebraic reasoning, I personally don't find it obvious that in order to find it (well actually a generalisation of it) it's necessary to look in `Relation.Binary.Core`.
As for uses in the library, this would replace the uses of `_Preserves₂_⟶ _ ⟶ _` throughout the `Algebra` modules. As an added bonus, most of the algebraic records which require this property already call it `cong`.
=> Add `Congruent₁` and `Congruent₂` to Algebra.FunctionProperties

src/Data/Fin.agda
This matches the definition of `_≤_` above.
Warning: this was tested with an Agda no newer than 77d6478f0670943665f6eb1673fafe614043dd77.
```
$ agda --version
Agda version 2.4.3
```
=> Add _≤?_ decision procedure for Data.Fin

CHANGELOG, src/Data/Bool/Properties.agda
Moved useful lemmas and properties in the Data.Bool.Properties file that were previously in private scope, either explicitly or within records, into public scope.
=> Deprivatised properties in Data.Bool.Properties

CHANGELOG, src/Data/Fin/Properties.agda
Moved useful lemmas and properties in the Data.Fin.Properties file that were previously in private scope, either explicitly or within records, into public scope.
=> Deprivatised properties in Data.Fin.Properties

CHANGELOG, src/Data/Integer/Properties.agda
Moved useful lemmas and properties in the Data.Integer.Properties file that were previously in private scope, either explicitly or within records, into public scope.
=> Deprivatised properties in Data.Integer.Properties

CHANGELOG, src/Data/Integer/Addition/Properties.agda
Moved useful lemmas and properties in the Data.Integer.Addition.Properties file that were previously in private scope, either explicitly or within records, into public scope.
=> Deprivatised properties in Data.Integer.Addition.Properties

CHANGELOG, src/Data/Integer/Multiplication/Properties.agda
Moved useful lemmas and properties in the Data.Integer.Multiplication.Properties file that were previously in private scope, either explicitly or within records, into public scope.
=> Deprivatised properties in Data.Integer.Multiplication.Properties

src/Data/Container.agda
Reverts agda/agda-stdlib#123
You need to at least make sure that the `Data.Container.*` modules compile before issuing a PR.
=> Revert "Added parameter to Container" #123 (Re #1210

CHANGELOG.md, src/Data/Fin/Properties.agda
For some of these the equivalent property from the orderings over `Data.Nat` can be applied immediately, however for most this is not the case.
I've also reorganised the file a tiny bit under headings in the style of other `Properties` files.
=> Added additional equality and ordering properties in Data.Fin.Properties

GNUmakefile
I altered `GNUmakefile` slightly so that it will work even if someone is building the project in a cabal sandbox. It should still work for global installs. Requires cabal 1.18 or later.
=> Have makefile compatible with cabal sandboxes

CHANGELOG.md, src/Data/Vec/All.agda, src/Data/Vec/All/Properties.agda
The new `All₂` definition is very useful but the current implementation has two problems:
1) Not sufficiently generic with respect to levels and types
2) Unable to pattern match directly on terms of type `All₂ P xs ys` because of its definition as the `zip` of two lists (see the old version of lemma `All₂-map`).
This patch fixes these two problems by adding a native, more generic implementation of `All₂`. Due to the aliasing of the new constructors, while proofs of properties about it may need updating, actual usage and construction of terms of that type should be mostly compatible.
=> Abstracting and adding a native definition of `All₂`

CHANGELOG.md, src/Data/Product.agda
Is there any particular reason these weren't added years ago? I might have missed some particular discussion about this.
=> Added syntax for existential quantifiers.

CHANGELOG.md, src/Data/Nat/Properties.agda, src/Data/Nat/Properties/Simple.agda
Moved many of the proofs hidden in private scope and records in `Data.Nat.Properties` out into public scope. Also rearranged the more messy bits of the file so that they're more logically ordered and hence easier to manually search. The proofs are now in the order:
1. Equality
2. Orderings
3. Addition and multiplication
4. Min and max
5. Subtraction
6. Other
Also added the proofs `<-irrefl` and `<-asym` to `Data.Nat.Properties` and `+-left-identity` and `*-left-zero` to `Data.Nat.Properties.Simple`.
These changes should be entirely backwards compatible. `Data.Nat.Properties` exports everything it used to export with no names changes. I've run `make test` in the std-lib and manually gone through the commit to check that I haven't lost any properties in my rearrangement of the file.
=> Deprivatised Data.Nat.Properties and added a few simple lemmas.

CHANGELOG.md, src/Data/Fin/Dec.agda, src/Relation/Nullary/Negation.agda
This addresses #118 by moving the problematic lemma back to `Data.Fin.Dec`. Hopefully it's relatively uncontroversial (?) that any lemma concerning `Fin n` indexed functions doesn't belong in `Relation.Nullary.Negation`....
=> Moved ¬∀⟶∃¬ from Relation.Nullary.Negation to Data.Fin.Dec

src/Data/Nat/GCD.agda
I found this function useful for my me-em project, and it seems curiously missing from this file. I'm not sure what the criteria is for adding stuff to the standard library, but I suspect this may be of occasional use to others.
=> Add a decider for GCD

CHANGELOG.md, src/Data/Vec/All/Properties.agda
Removed `All` and `_++` lemmas from private scope.
Also added some additional lemmas relating `All` and `All₂` to `_++_` and `concat` as well as tidied up some of the overly long types.
=> Deprivatising Data.Vec.All.Properties

src/Data/Container/Indexed.agda
This PR implements a minor generalisation of `Data.Container.Indexed.setoid`: The underlying equality need not be at level `c ⊔ r`, as it is currently, but can be at an arbitrary level. I need this for a use case where the equality is at level `c ⊔ r ⊔ o`.
(I don't follow the protocol outlined in `HACKING.md` because I didn't find the branches for Agda 2.5.* and 2.6.*. Sorry if I'm misunderstanding the process.)
=> Data.Container.Indexed.setoid: Generalise levels

CHANGELOG.md, src/Data/List/All.agda, src/Data/List/Base.agda
In particular `List` versions of the very useful `tabulate` and `allFin` from `Data.Vec` have been added.
There was a pre-existing version of `downFrom` which used some unique internal data-types and the `unfold` operation. This has been changed to a much simpler version not relying on `unfold`, as the current version is incredibly difficult to reason about.
=> Added sequence-generating functions to Data.List

CHANGELOG.md, src/Data/Empty/Irrelevant.agda
In separate module `Irrelevant` under `Data.Empty`, as discussed in #115.
=> Added irrelevant version of bot-elim

CHANGELOG.md, src/Data/Bin.agda, src/Data/Bin/Properties.agda
... and moved the relevant proofs from `Data.Bin` to `Data.Bin.Properties`
=> Added a properties file for Data.Bin

CHANGELOG.md, src/Algebra/FunctionProperties/Consequences.agda, src/Algebra/Properties/BooleanAlgebra.agda, src/Data/Integer/Properties.agda, src/Data/Nat/Properties.agda
Fed up of proving certain basic relations between algebraic properties over and over again. Many of these proofs already have many copies floating around the library at the moment (e.g. `Data.Nat.Properties`, `Data.Integer.Properties`, `Algebra.Properties.BooleanAlgebra`, `Algebra.Properties.DistributiveLattice`). These are just the basic ones, the file can be updated with more when people come across them.
If no one has any objections, I'll start cleaning up their occurrences in the rest of the library some time towards the end of the week.
=> Adding `Algebra.FunctionProperties.Consequences`

CHANGELOG.md, src/Relation/Binary/StrictPartialOrderReasoning.agda
Previously using `_<⟨_⟩_` StrictPartialOrderReasoning required a value of the sum of the less-than and equal-to relations. With this change the `<` case and `≈` case are accessible via the appropriately named operators.
The existing `_≈⟨_⟩_` already handles the equality
case and after this change `_∼⟨_⟩_` remains available
for the odd-case where the sum-behavior is desired.
This fix is inspired from the following use-case.
(Incidentally I'd love to have from-left and from-right added to Data.Sum in the style of Data.Maybe.from-just.)
```agda
example : ∀ {a} {A : Set a} (f : A → A) (x : A) (xs : List A) →
xs ≢ x ∷ x ∷ map f xs
example f x xs =
irref-ord List-ord
$ from-left
$ begin List-ord                xs  ≈⟨ map-ord f xs ⟩
List-ord (        map f xs) <⟨ [ lt₁ tt ] ⟩
List-ord (    x ∷ …
```
=> Fix _<⟨_⟩_ to take a proof of less-than

CHANGELOG.md, src/Function.agda, src/Strict.agda
Agda.Builtin.Strict was introduced in February 2016 but we
somehow missed it and it's not part of the standard library.
This fixes this issue.
Also, I've taken the opportunity to introduce ticked version
of various apply functions which, just like the ticked
composition operator, expect their function *not* to be a
dependent function. This makes type-inference a lot easier
and is usefull to make unsolved metas go away!
=> [ new ] Support for Agda.Builtin.Strict

CHANGELOG.md, src/Data/BoundedVec.agda
In gallais/agda-sizedIO, I need `BoundedVec` to be level polymorphic
for the [`take`](https://github.com/gallais/agda-sizedIO/blob/master/src/Sized/Colist.agda#L36) function on `Colist` to be as general as possible.
So I implemented the change.
I was also surprised by the lack of conversion function between the
inefficient representation and the efficient one so I threw that in at
the same time.
=> Boundedvec: Level polymorphism + conversion functions

CHANGELOG.md, README/AVL.agda, README/Nat.agda, src/Data/Char.agda, src/Data/Integer/Properties.agda, src/Data/List/Any/Membership/Propositional/Properties.agda, src/Data/Nat/Coprimality.agda, src/Data/Nat/DivMod.agda, src/Data/Nat/Divisibility.agda, src/Data/Nat/GCD/Lemmas.agda, src/Data/Nat/InfinitelyOften.agda, src/Data/Nat/LCM.agda, src/Data/Nat/Properties.agda, src/Data/Nat/Properties/Simple.agda
This pull request fixes the main instances of inconsistent naming in the `Data.Nat.Properties` file. Currently the inconsistencies mean that its difficult to use the file without looking up each lemma individually. This change should make the names of the standard properties nearly entirely predictable.
This pull request should be entirely backwards compatible with existing code as I have left the old deprecated names in at the bottom of the file. The changes since the last release of the library are (old name -> new name):
```
+-right-identity = +-identityʳ
*-right-zero     = *-zeroʳ
distribʳ-*-+     = *-distribʳ-+
*-distrib-∸ʳ     = *-distribʳ-∸
cancel-+-left    = +-cancelˡ-≡
cancel-+-left-≤  = +-cancelˡ-≤
cancel-*-right   = *-cancelʳ-≡
cancel-*-right-≤ = *-cancelʳ-≤
strictTotalOrder …
```
=> Fixing library naming conventions in Data.Nat.Properties

CHANGELOG.md, src/Relation/Unary.agda
Typical use case: silently threading a context and patching it
up on the fly. For instance, this definition of the well-scoped
untyped lambda-calculus:
data Tm : Nat → Set where
var : ∀[ Fin      ⇒ Tm ]
lam : ∀[ suc ⊢ Tm ⇒ Tm ]
app : ∀[ Tm ⇒ Tm  ⇒ Tm ]
=> [ new ] Predicate Update & syntax for Universal

CHANGELOG.md, src/Algebra.agda, src/Algebra/Morphism.agda, src/Algebra/RingSolver/AlmostCommutativeRing.agda, src/Algebra/Structures.agda, src/Data/Nat/Properties.agda
This is a breaking change for `Algebra.Morphism` but I very much doubt that anyone relied heavily on it. I had to put `setoid` as a definition provided by `IsEquivalence` which changes quite a few `open (...) public` but the exported things are exactly the same in the end.
=> Structure homomorphisms + example _^_

CHANGELOG.md, README/Container/FreeMonad.agda, src/Data/Container/FreeMonad.agda, src/Data/Container/Indexed/FreeMonad.agda
In `Data.Container.FreeMonad` and `Data.Container.Indexed.FreeMonad`.
We're adding proper do-notation to Agda which makes 'do' a keyword.
I'm not sure about the new name. The function is the constructor of the fixed point, and this is often called `in`, but maybe there's a better name in this context.
=> renamed 'do' -> 'inn' in FreeMonad modules

CHANGELOG.md, src/Data/Word.agda, src/Reflection.agda
This PR does minimal work to make the standard library work with `Word64`. It doesn't define word arithmetic.
=> Update for new builtin Word64 type

CHANGELOG.md, README/AVL.agda, src/Data/AVL.agda, src/Data/AVL/Height.agda, src/Data/AVL/Indexed.agda, src/Data/AVL/IndexedMap.agda, src/Data/AVL/Key.agda, src/Data/AVL/Sets.agda
This is a common pain-point as witnessed by the following SO
questions:
https://stackoverflow.com/questions/21369719/functor-instance-for-data-avl
https://stackoverflow.com/questions/47367747/data-avl-map-that-changes-value-type
This does not introduce anything new, it mostly splits up Data.AVL
into submodules Data.AVL.(Key|Height|Indexed) which are parameterised
by nothing more than what they need.
The type of `map` changes from `(forall k. V k -> Vk) -> Tree -> Tree`
to `(forall k. V k -> W k) -> Tree V -> Tree W`. We require 1 extra
type annotation in README.AVL
=> [ refactor ] Data.AVL's map should be polymorphic

CHANGELOG.md, src/Relation/Binary/PropositionalEquality/TrustMe.agda
I added a short description of what POSTULATE[_↦_] does, and renamed it to lowercase as suggested.
=> Add postulate[_↦_] trick by Alan Jeffrey to TrustMe (closes #57)

CHANGELOG.md, src/Relation/Binary/HeterogeneousEquality.agda, src/Relation/Binary/PropositionalEquality.agda
Given that they were deprecated in version 0.10 it's probably about time. Shout if they're still crucial!
=> Removed deprecated inspect modules

CHANGELOG.md, src/Data/List/Relation/Lex/Core.agda, src/Data/List/Relation/NonStrictLex.agda, src/Data/List/Relation/StrictLex.agda, src/Relation/Binary/List/NonStrictLex.agda, src/Relation/Binary/List/StrictLex.agda
Achieves:
- increasing the level polymorphism as per #180 
- moves the content shared by `StrictLex` and `NonStrictLex` into `Lex.Core`
- standardised the notation used within the modules. Now uses `_≼_` for the base relation and `_<_` and `_≤_` for the resulting lexicographic
- added a few extra proofs
Hopefully everyone agrees that this makes the files far easier to read.
EDIT: definitely backwards compatible as everything is re-exported from the deprecated `Relation.Binary.List.(Non)StrictLex`
=> Tidying up lexicographic orderings over lists

CHANGELOG.md, src/Data/Char.agda, src/Data/Char/Base.agda
Not sure if Data.Char should be exporting all those is* checks. Also I moved the import of primCharEquality to Data.Char where it is actually used.
=> Add missing bindings to Char functions

CHANGELOG.md, src/Algebra/Monoid-solver.agda, src/Data/List/All.agda, src/Data/List/Base.agda, src/Data/List/Countdown.agda, src/Data/Table.agda, src/Data/Table/Base.agda, src/Data/Table/Properties.agda, src/Data/Table/Relation/Equality.agda, src/Data/Vec/Properties.agda
Continuing from #212.
> - Move swapFin from Data.Fin.Properties to Data.Fin, rename it swap and provide an explanation of what it does. It should be implemented via pattern matching instead of if_then_else_. This will then allow you to delete the if-dec-true and if-dec-false lemmas.
> - Move the swap-lem₁ and swap-lem₂ in Data.Fin.Properties out of public scope and give them more meaningful names.
> - Remove the permutation lemmas from Data.Fin.Properties from the PR
I've just removed all of these since I realised they're not actually used by any of the `Data.Table` code.
> - Move all the private lemmas in Data.Table (that do not rely on SigmaPropositional) into Data.Table.Properties as well as the proof of isomorphisms with Vec and Table.
I can't prove isomorphism with lists without …
=> Purer `Data.Table`

CHANGELOG.md, src/Relation/Nullary.agda
See https://github.com/agda/agda/issues/2992
I decided against the `Unique` requirement since it just amounted to an unused parameter, even though I still think from a pragmatic standpoint it only makes sense to recompute unique proofs.
=> Add recompute

CHANGELOG.md, src/Algebra.agda, src/Algebra/CommutativeMonoidSolver.agda, src/Algebra/CommutativeMonoidSolver/Example.agda, src/Algebra/FunctionProperties.agda, src/Algebra/FunctionProperties/Consequences.agda, src/Algebra/IdempotentCommutativeMonoidSolver.agda, src/Algebra/IdempotentCommutativeMonoidSolver/Example.agda, src/Algebra/Monoid-solver.agda, src/Algebra/Morphism.agda, src/Algebra/Operations.agda, src/Algebra/Properties/AbelianGroup.agda, src/Algebra/Properties/BooleanAlgebra.agda, src/Algebra/Properties/Group.agda, src/Algebra/Properties/Ring.agda, src/Algebra/RingSolver/Lemmas.agda, src/Algebra/Structures.agda, src/Data/Bool/Properties.agda, src/Data/Fin.agda, src/Data/Integer/Properties.agda, src/Data/Nat/Properties.agda
Some changes that I've wanted to make for a long time. All 100% backwards compatible:
- You can now provide the equality as a module parameter to `Algebra.Structures`, just like `Algebra.FunctionProperties`, and so if you're only using a single equality you no longer need to mention it every time for every structure (e.g. see changes to `Data.Bool.Properties`).
- The structure records now export the left and right versions of things like `identity`, `zero`, `inverse`, `distributivity` etc. This can be used to remove the various `proj`s scattered throughout many algebraic proofs, and increases readability.
- Added a few extra missing algebraic structures to `Data.(Nat/Bool).Properties`
=> Parameterising `Algebra.Structures` by equality

src/Data/List/Base.agda
No need to use this deep pattern to reconstruct it immediately
afterwards in the recursive call.
=> [ refactor ] intersperse

CHANGELOG.md, src/Data/Vec/Properties.agda
Concatenation is an injective function iff the length of the vectors are the same.
My last pull request was a very nice experience, so I'll try again! This time I could not find anything on the mailing list talking about this, so the only known need for these proofs are my own. Still, I think it is quite a natural thing to have in the standard library.
=> Add injectivity proofs for `_++_` in `Data.Vec.Properties`

CHANGELOG.md, src/Data/Vec/Properties.agda
Associativity of `_++_`. The function and data-type are indexed, so I don't think it's possible to use `Associative` from `Algebra.FunctionProperties`.
=> Add proof of associativity of `_++_` in `Data.Vec.Properties`

src/Data/Table/Base.agda
* using `head t` instead of `lookup t zero`
* defining `uncons : Table A (suc n) -> A * Table A n`
* grouping functor / applicative combinators
* using anonymous modules to clean up types
There's also the question of using `List`-style foldr and foldl rather than the
[`Vec`-style ones](https://agda.github.io/agda-stdlib/Data.Vec.html#foldr)
=> [ refactor ] Data.Table

CHANGELOG.md, src/Data/Product.agda
After seeing quite a lot of `Product.map` used with `id` in [`Data.Graph.Acyclic`](https://agda.github.io/agda-stdlib/Data.Graph.Acyclic.html),
I figured it was worth having names for these. I've used numbers as subscripts
to follow `proj₁` / `proj₂`.
=> [ new ] Product.map for fst/snd component only

CHANGELOG.md, src/Data/List/Reverse.agda
This has been bothering me since I looked into `Data.List.Reverse` because of #295 
No need to repeatedly call `initLast` to build `Reverse xs`:
* we first `Reverse (reverse xs)`
* and then use the fact that `reverse (reverse xs) = xs`
=> [ refactor ] structural definition of reverseView

CHANGELOG.md
Looks like a whitespace issue snuck in on 'master'.
=> fix-agda-whitespace

src/Function/Related/TypeIsomorphisms.agda
in level, just to show that it doesn't matter. Overkill, but why not? Still part of #295.
=> Make test in Function.Related.TypeIsmorphisms more polymorphic

CHANGELOG.md, src/Algebra.agda, src/Algebra/Structures.agda
Pretty self-explanatory. Going to be used for a future pull request for left and right natural orders.
I'd dearly like to re-define `IsLattice` in terms of two `IsSemilattice`s, but backwards compatibility and all that jazz...
=> [ new ] add `Band` and `Semilattice` algebraic structures

CHANGELOG.md, src/Data/List/Any/Properties.agda, src/Data/List/Membership/Propositional/Properties.agda, src/Data/List/Membership/Setoid/Properties.agda, src/Data/List/Relation/Permutation/Inductive.agda, src/Data/List/Relation/Permutation/Inductive/Properties.agda
implement permutation over lists in two different flavors. these two different flavors are very useful when verifying algorithms over lists. I do know there is another definition lives in `Data.Fin.Permutation`, but I don't think this would work sufficiently handy in some situations.
=> add different definitions of permutation

CHANGELOG.md, src/Data/Fin/Dec.agda, src/Data/Fin/Subset.agda, src/Data/Fin/Subset/Properties.agda, src/Data/List/All.agda, src/Data/List/All/Properties.agda, src/Data/List/Any.agda, src/Data/Vec.agda, src/Data/Vec/All.agda, src/Data/Vec/All/Properties.agda, src/Data/Vec/Any.agda, src/Data/Vec/Membership/Propositional.agda, src/Data/Vec/Membership/Propositional/Properties.agda, src/Data/Vec/Properties.agda
Currently the implementation of membership for vectors is much more barebones than the implementation for lists. Now that we have the structure for list membership finally sorted out, this PR implements vec membership in a similar way. This means that going forward from v1.0, we can flesh it out in a backwards compatible fashion. See CHANGELOG for full details.
As always, comments welcome.
=> Adding `Data.Vec.Any` and standardising `Vec` membership

CHANGELOG.md, README/Case.agda, src/Algebra/CommutativeMonoidSolver.agda, src/Algebra/IdempotentCommutativeMonoidSolver.agda, src/Algebra/Monoid-solver.agda, src/Data/Maybe/Base.agda, src/Data/Sum.agda
Made the `Set` argument implicit in `Data.Maybe.Base`'s `From-just`
to be consistent with the definition of `Data.Sum`'s `From-injₙ`
=> Make From-just & From-injₙ's types consistent

src/Codata/Stream.agda
I don't know why I went with the worse version to begin with...
=> [ fix ] inlining the map in iterate

CHANGELOG.md, src/Codata/Colist.agda, src/Codata/Conat.agda, src/Codata/Covec.agda, src/Codata/Stream.agda
This allows us to convert from old-style coinduction to new-style
one. This is particularly useful when using the legacy IO module
that produce old-style values.
=> [ new ] fromMusical coercions

CHANGELOG.md, src/Data/Fin/Properties.agda, src/Data/Nat/DivMod.agda, src/Data/Nat/DivMod/Core.agda, src/Data/Nat/Divisibility.agda
This attempts to build a more practical modular arithmetic library than currently exists. In particular it defines a new modulus operator `_%_` which returns a `ℕ` instead of the old `_mod_` which returns a `Fin divisor`. This new operator is **much** easier to  write arithmetic expressions with and prove properties of.
This was inspired by the problems caused by `_mod_` in #143. Namely the unsafe `_mod_` pollutes a large section of the `Data.Nat` hierarchy. Consequently I've adjusted `Data.Nat.Divisibility` to use `_%_` rather than `_mod_`. This has massively cleaned up several proofs. 
Accordingly `_mod_` and `_divMod_` can now be relegated to `Data.Nat.DivMod.Unsafe` in some future PR.
Outstanding questions:
* Naming convention for proofs about `_%_`. Obviously the proofs require the …
=> [ new ] useful modular arithmetic

CHANGELOG.md, src/Data/List/Countdown.agda, src/Data/Nat/Base.agda, src/Data/Nat/InfinitelyOften.agda, src/Function/Related/TypeIsomorphisms.agda, src/Level.agda, src/Level/Literals.agda
An extension to the `ℓ` naming convention for levels that's used throughout the library. In a lot of places we write `Level.zero` or `zero`. The former is verbose and requires `as Level` in the header and the latter is sometimes confusing when dealing with numeric datatypes.
Thoughts? Is `ℓ` used for anything else that I'm forgetting?
=> [ new ] synonym for Level.zero

CHANGELOG.md, src/Data/Container/Any.agda, src/Data/List/Any/Properties.agda, src/Data/List/Relation/BagAndSetEquality.agda, src/Data/Product/Relation/Pointwise/Dependent.agda, src/Data/Product/Relation/Pointwise/NonDependent.agda, src/Data/Sum/Relation/Pointwise.agda, src/Function/Related.agda, src/Function/Related/TypeIsomorphisms.agda
Some of the proofs in `Function.Related` that are needed to finish off #400 are currently hidden in private scope. This makes them public and attempts to come with a consistent naming scheme. The `K` stands for `Kind` and `SK` for `SymmetricKind`. 
@gallais I changed your `↔-preorder` as `_↔_` is actually the equivalence relation, not the preorder relation and therefore I think the new name is more consistent with the rest of the library.
Feel free to suggest alternative names. I also considering `Kˢ` instead of `SK` and am undecided about which is better.
=> Deprivatising `Function.Related`

CHANGELOG.md, src/Category/Functor.agda
Noticed we were missing <&>. Picked the [same fixity as Haskell's](https://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Functor.html#v:-60--38--62-)
=> [ new ] flipped version of <$>

CHANGELOG.md, src/Data/Nat/Coprimality.agda, src/Data/Nat/GCD.agda, src/Data/Nat/GCD/Lemmas.agda, src/Data/Nat/InfinitelyOften.agda, src/Data/Nat/Primality.agda, src/Data/Nat/Properties.agda
Various tidying up of proofs. The only major change is to deprecate `im≡jm+n⇒[i∸j]m≡n` and `i∸k∸j+j∸k≡i+j∸k` in `Data.Nat.Properties`. Both of them are far too specific to have in `Data.Nat.Properties`. The latter was never used in the library, the former only used in `Data.Nat.GCD.Lemmas` which is full of similarly specific proofs.
=> [ refactor ] deprecated im≡jm+n⇒[i∸j]m≡n and i∸k∸j+j∸k≡i+j∸k in Data.Nat.Properties

src/Codata/Cofin.agda, src/Codata/Colist.agda, src/Codata/Colist/Properties.agda, src/Codata/Conat.agda, src/Codata/Covec.agda, src/Codata/Covec/Properties.agda, src/Codata/Delay.agda, src/Codata/Delay/Properties.agda, src/Codata/M.agda, src/Codata/Stream.agda, src/Codata/Stream/Properties.agda, src/Codata/Thunk.agda
Note that we can't define instances for RawFunctor & RawComonad because Thunk is a
functor in Set^Size, not Set.
=> [ refactor, new ] Thunks and functions acting on them 

GenerateEverything.hs, HACKING.md
This PR containing ~~two~~ one fix~~es~~:
1. I find that the produced error message when forgetting to add library header is not very clear. It just says the file is malformed, but does not mention how to fix it.
2. ~~I do not find `cabal install` in the makefile is necessary. Once I forgot to work in a sandbox and it ended up copying `GenerateEverything` to be global cabal folder. Please let me know there are better fixes for that.~~
I removed changes to `GNUmakefile`.
=> [ new ] try to make formatting issue from new modules clearer

src/Codata/Thunk.agda
This adds a syntax declaration for `Thunk`s. It mimics the syntax declarations for `Σ`. I found myself using a lot of sized types where the size parameter was implicit, or where it wasn't the last parameter, and this syntax would make things a little easier to read. Take this example of a coinductive non-empty list:
With syntax:
```agda
record NonEmpty {i : Size} {a} (A : Set a) : Set a where
coinductive
field
head : A
tail : Maybe (Thunk[ j < i ] NonEmpty {j} A)
```
Without syntax:
```agda
record NonEmpty {i : Size} {a} (A : Set a) : Set a where
coinductive
field
head : A
tail : Maybe (Thunk (λ j → NonEmpty {j} A) i)
```
=> Added thunk-syntax to mimic syntax for products etc

CHANGELOG.md, src/Algebra/Solver/IdempotentCommutativeMonoid.agda, src/Algebra/Solver/Ring.agda, src/Algebra/Solver/Ring/NaturalCoefficients.agda, src/Algebra/Solver/Ring/NaturalCoefficients/Default.agda, src/Algebra/Solver/Ring/Simple.agda, src/Data/Bool.agda, src/Data/Bool/Base.agda, src/Data/Bool/Properties.agda, src/Data/Fin/Subset/Properties.agda, src/Function/Related/TypeIsomorphisms/Solver.agda, src/Relation/Binary/Consequences.agda, src/Relation/Binary/Core.agda
(See #507)
This replaces the `Decidable` module parameter in `Algebra.Solver.Ring`
by a new predicate `WeaklyDecidable`. It only provides a subset of those
equality proofs that `Decidable` can provide, and does not provide
inequality proofs.
As a result, ring solvers can now be used in more general situations in
which decidable equality is not available. For this, a new module
`Algebra.Solver.Ring.NaturalCoefficients.Default` was added which
instantiates the natural coefficients solver for any
`CommutativeSemiring`, such as `×-⊎-commutativeSemiring` in
`Function.Related.TypeIsomorphisms.Solver`.
---
Any comments are appreciated. Is naming and location of the two new modules `Algebra.Solver.Ring.WeaklyDecidable` and `Algebra.Solver.Ring.NaturalCoefficients.Default` appropriate or are there …
=> Relax decidability module parameter of Algebra.Solver.Ring

.travis.yml
Now "installplan.txt" is used throughout `.travis.yml`.
=> .travis.yml: "intallplan.txt" -> "installplan.txt"

CHANGELOG.md, src/Codata/Stream.agda, src/Codata/Stream/Properties.agda
* Instead of stacking `map` after `map` on top of each other, we
use `unfold`'s internal state to carry the updated seed value.
* Because `unfold`'s argument is of type `A → A × A`, we could easily
introduce a bug here so we also prove a correction lemma for the
refactored version.
=> [ refactor ] Stream's iterate

CHANGELOG.md, src/Algebra.agda, src/Algebra/Properties/BooleanAlgebra.agda, src/Algebra/Properties/BooleanAlgebra/Expression.agda, src/Algebra/Properties/DistributiveLattice.agda, src/Algebra/Properties/Lattice.agda, src/Algebra/Structures.agda, src/Data/Bool/Properties.agda, src/Data/Fin/Subset/Properties.agda, src/Data/Integer/Properties.agda, src/Data/List/Properties.agda, src/Data/List/Relation/BagAndSetEquality.agda, src/Data/List/Relation/Permutation/Inductive/Properties.agda, src/Data/Maybe/Properties.agda, src/Data/Nat/Properties.agda, src/Data/Sign/Properties.agda, src/Function/Related/TypeIsomorphisms.agda, src/Relation/Binary/Properties/Lattice.agda
This "corrects" the fields for `IsSemigroup` and `IsLattice` as discussed in #456. This is a little painful but I think better to nip this in the bud in v1.0 than to leave it be and have it cause even more problems in the long term.
=> [ refactor ] straightening out the Algebra hierarchy

CHANGELOG.md, src/Algebra.agda, src/Algebra/Properties/BooleanAlgebra.agda, src/Algebra/Properties/BooleanAlgebra/Expression.agda, src/Algebra/Properties/Lattice.agda, src/Algebra/Properties/Semilattice.agda, src/Algebra/Structures.agda, src/Data/Bool/Properties.agda, src/Data/Fin/Subset/Properties.agda, src/Data/Nat/Properties.agda, src/Relation/Binary/Properties/JoinSemilattice.agda, src/Relation/Binary/Properties/Lattice.agda, src/Relation/Binary/Properties/MeetSemilattice.agda
...and update dependencies.
I noticed that algebraic semilattices are now defined as a structure in the `Algebra` module, so I thought it might be nice to also add a `Algebra.Properties` module for them (similar to that for lattices).
I moved some of the properties from `Algebra.Properties.Lattice` to `Algebra.Properties.Semilattice` and updated the former so as not to break dependencies.
=> Add properties of algebraic semilattices

src/Algebra/Properties/Semilattice.agda, src/Relation/Binary/Construct/NaturalOrder/Left.agda, src/Relation/Binary/Construct/NaturalOrder/Right.agda
Using the new constructions to replace the old code in `Algebra.Properties.Semilattice`. Had to reverse the definition of the orders to get it to match the existing code.
=> [ refactor ] use left natural order to refactor semilattice properties

src/Data/Vec/Membership/DecPropositional.agda, src/Data/Vec/Membership/DecSetoid.agda, src/Data/Vec/Membership/Propositional.agda, src/Data/Vec/Membership/Setoid.agda
Adds the following modules:
* `Data.Vec.Membership.Setoid`
* `Data.Vec.Membership.DecSetoid`
* `Data.Vec.Membership.DecPropositional`
Refactors `Data.Vec.Membership.Propositional` to be an alias for `Data.Vec.Membership.Setoid`.  This is basically copied from `Data.List.Membership.*` with slight changed to accommodate vectors. 
**Discussion:**
I preserved the signature of `_∈_`:
```haskell
_∈_ : A → ∀ {n} → Vec A n → Set _
```
However, this forces `_∈?_` to have a more clumsy signature (I chose: `_∈?_ : ∀ x {n} (xs : Vec A n) → Dec (x ∈ xs)`). Instead it could be done by placing `{n}` first:
```haskell
_∈_ : ∀ {n} → A → Vec A n → Set _
_∈?_ : ∀ {n} → Decidable (_∈_ {n})
```
Which gives a nicer signature for `_∈?_` but induces a *technically-unnecessary* dependency in `_∈_`.
=> Generic Vec membership (fix #486)

CHANGELOG.md, src/Relation/Binary/Core.agda
`_Respects*_` can be given a more general type for the ˡ or ʳ versions, to support heterogeneous relations. Of course, `_Respects₂_` still unifies these into a homogeneous relation.
=> Give Respectsˡ/Respectsʳ more general signature (REL instead of Rel)

CHANGELOG.md, src/Algebra/Construct/NaturalChoice/Max.agda, src/Algebra/Construct/NaturalChoice/Min.agda
Addresses #430. Used a total order which I think is more natural than using decidability. Without the total ordering axioms, it's not the case that not being less than or equal to something is equivalent to being greater than or equal to it. Counter-arguments welcome though!
Although the downside is that it's not directly definable from a `StrictTotalOrder`...
=> [ fix #430 ] add generic min/max operations

CHANGELOG.md, src/Data/Product/Relation/Pointwise/NonDependent.agda, src/Data/Sum/Relation/Pointwise.agda
Adding some combinators I happened to need when using the × setoid. `_×-⟶_` could also be changed to be written in the combinator style if wanted (and maybe `mapₛ` would be a better name).
=> [ new ] combinators for pointwise setoids

CHANGELOG.md, src/Data/Vec/Any/Properties.agda
Fixes #546. Transferred most of the properties from `Data.List.Any` into `Data.Vec.Any`. Implementation mostly the same. I'm having trouble implementing this inverse:
```agda
×↔ : ∀ {n m} {xs : Vec A n} {ys : Vec B m} →
(Any P xs × Any Q ys) ↔ Any (λ x → Any (λ y → P x × Q y) ys) xs
×↔ = inverse Any-×⁺ Any-×⁻ {!!} {!!}
```
=> More Data.Vec.Any properties (fix #546)

CHANGELOG.md, src/Data/Bool/Properties.agda, src/Data/Fin/Properties.agda, src/Data/Integer/Properties.agda, src/Data/List/First/Properties.agda, src/Data/Nat/Properties.agda, src/Data/Rational/Properties.agda, src/Data/Vec/Properties.agda, src/Data/Vec/Properties/WithK.agda, src/Relation/Binary/HeterogeneousEquality.agda, src/Relation/Binary/HeterogeneousEquality/Quotients.agda, src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda, src/Relation/Binary/PropositionalEquality/WithK.agda
=> [ fix #485 ] Deprecated the name `irrelevance` in favour of `irrelevant`

CHANGELOG.md, src/Data/List/Relation/Pointwise.agda, src/Data/List/Relation/Suffix/Heterogeneous.agda, src/Data/List/Relation/Suffix/Heterogeneous/Properties.agda
Hello, new Agda contributor, so please let me know if I have made any major style violations or anything like that.
Here is an implementation of a heterogeneous `Suffix` property, to go along with `Prefix` (#522). Many of the Prefix theorems are mirrored here, except for those that don't apply easily to suffixes (e.g. `zipWith`, `inits`, ...).
Considerations before merging:
* The data constructor names `here`/`there` may not be appropriate, maybe something like `skip`/`stop` is more accurate since `here` does not refer to a single element, like in the case of `Any`.
* I've defined a number of `Pointwise` lemmas that probably deserve to be moved into the `Pointwise` module.
=> Some work on formalizing Suffix (re: #517)

CHANGELOG.md, src/Data/List/Base.agda, src/Data/List/Properties.agda
I also wrote ```lookup\'``` which removes a length type dependency that makes proofs harder.
=> Added some List tabulate-lookup properties.

CHANGELOG.md, src/Algebra/Properties/AbelianGroup.agda, src/Algebra/Properties/BooleanAlgebra.agda, src/Data/List/Relation/Binary/BagAndSetEquality.agda, src/Data/List/Relation/Binary/Permutation/Inductive.agda, src/Data/List/Relation/Binary/Permutation/Inductive/Properties.agda, src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda, src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda, src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda, src/Relation/Binary/Reasoning/Base/Double.agda, src/Relation/Binary/Reasoning/Base/Single.agda, src/Relation/Binary/Reasoning/Base/Triple.agda, src/Relation/Binary/Reasoning/MultiSetoid.agda, src/Relation/Binary/Reasoning/Setoid.agda
Added symmetric reasoning combinators. They hopefully help strip out the noise of `sym` being included in every other line in reasoning proofs. I've updated the proofs in `Algebra.Properties.AbelianGroup` to demonstrate this.
=> [ fix #344 ] Symmetric reasoning combinators

CHANGELOG.md, src/Algebra/FunctionProperties.agda, src/Data/List/Properties.agda, src/Data/Nat/Properties.agda
Fixes #392 as a present for @andreasabel as #540 may not make it in for v1.0.
Note I'm trying a new style for left and right operators, where we write the type explicitly to help aid readability. We then use the shorthand notation when combining the two. This ensures that we get both readability and that we get the type right. Obviously the style isn't applicable to properties that don't have left and right versions.
=> [ fix #392] Added cancellative and conical properties for _++_

CHANGELOG.md, src/Data/List/Relation/Binary/Permutation/Inductive/Properties.agda, src/Data/Vec/Relation/Binary/Pointwise/Extensional.agda, src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda, src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda
Fixes #428. I have changed "~" to "\sim" everywhere where they were being used inconsistently. 
This leaves "\sim" being used everywhere except in `Relation.Unary` which uses "~" for the negation operation. I haven't changed this to "\sim" because I'm unsure what the correct symbol to use is semantically, and "\sim" doesn't seem right. Anyone have any strong opinions?
=> [ fix #428 ] Increased the consistency of where "\sim" is used vs "~"

CHANGELOG.md, src/Axiom/DoubleNegationElimination.agda, src/Axiom/ExcludedMiddle.agda, src/Axiom/Extensionality/Heterogeneous.agda, src/Axiom/Extensionality/Propositional.agda, src/Axiom/UIP.agda, src/Axiom/UIP/WithK.agda, src/Axiom/UniquenessOfIdentityProofs.agda, src/Axiom/UniquenessOfIdentityProofs/WithK.agda, src/Data/Container/Combinator/Properties.agda, src/Data/Container/Indexed/Combinator.agda, src/Data/Container/Indexed/WithK.agda, src/Data/Container/Relation/Binary/Pointwise.agda, src/Data/Container/Relation/Binary/Pointwise/Properties.agda, src/Data/List/Relation/Unary/All/Properties.agda, src/Data/Nat/Properties.agda, src/Function/Related/TypeIsomorphisms.agda, src/Relation/Binary/HeterogeneousEquality.agda, src/Relation/Binary/HeterogeneousEquality/Core.agda, src/Relation/Binary/PropositionalEquality.agda, src/Relation/Binary/PropositionalEquality/WithK.agda, src/Relation/Nullary/Negation.agda
Trying to sneak one more thing in before v1.0. I've moved the existing axioms out of their old places in `Relation.Binary.PropositionalEquality` and `Relation.Nullary.Negation` and into new `Axiom` modules.
@gallais I'd appreciate a review in case I've written anything silly! Also is the hierarchy deep enough? I know you said you want to add implicit extensionality in #184 and uninformative excluded middle?
=> [ re #184 ] Add additional axiom modules

README/Case.agda
re #595 
Note that the comment
> Note that some natural uses of case are rejected by the termination checker:
did not hold anymore. Does anyone have a suggestion for another "natural use case"
which is rejected by the termination checker?
=> [ doc ] expanding README.Case

README.agda, README/List.agda
Re #595 this attempts to create some very rough documentation for the `List` class. @alhassy and @EdNutting perhaps you could provide some feedback? Would this have been useful for you?
@gallais I know you're a warnings person! Do you know of anyway of turning the `MissingDefinition` warning off? I've read the [documentation](https://agda.readthedocs.io/en/latest/tools/command-line-options.html) and tried this:
{-# OPTIONS --safe --warning noMissingDefinitions #-}
but it actually makes it worse as instead of turning it off, it turns it into an error.
=> [ re #595] Added documentation for `List`

CHANGELOG.md, src/Category/Monad/Reader.agda
Closes #690 
EDIT: now it is properly universe polymorphic
```agda
module Category.Monad.Reader {r} (R : Set r) (a : Level) where
IReaderT : ∀ {ℓ} {I : Set ℓ} → IFun I (r ⊔ a) → IFun I (r ⊔ a)
IReaderT M i j A = R → M i j A
ReaderT : (Set (r ⊔ a) → Set (r ⊔ a)) → Set (r ⊔ a) → Set (r ⊔ a)
ReaderT M A = R → M A
Reader : Set (r ⊔ a) → Set (r ⊔ a)
Reader A = R → A
record RawIMonadReader {ℓ} {I : Set ℓ} (M : IFun I (r ⊔ a))
: Set (ℓ ⊔ suc (r ⊔ a)) where
field
monad  : RawIMonad M
reader : ∀ {i A} → (R → A) → M i i A
local  : ∀ {i j A} → (R → R) → M i j A → M i j A
```
=> Implement Reader monad (transformer)

src/Foreign/Haskell.agda
It seems to me like the `Unit` in `Foreign.Haskell` was added at least as early as 2009, and since then, a change was committed that makes the `⊤` type from `Data.Unit` actually map to Haskell’s `()` (from `Agda.Builtin.Unit`), which renders the `Unit` type useless.
=> deprecate `Foreign.Haskell.Unit`

CHANGELOG.md, README/List.agda, README/Trie/NonDependent.agda, src/Data/Char.agda, src/Data/Char/Base.agda, src/Data/Char/Properties.agda, src/Data/String.agda, src/Data/String/Base.agda, src/Data/String/Properties.agda
In Data.(Char/String).Properties we should be using more explicit
names.
=> [ fix #724 ] rename setoid and order results

CHANGELOG.md, src/Data/Product/Properties.agda, src/Data/Product/Properties/WithK.agda, src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda
These lemmas are easier to find than those in the Pointwise module. They are basically the same as the WithK variants under the same name, but since they are for non-dependent products, they do not require K.
closes #755
=> ,-injectiveʳ and ≡-dec for non-dependent product

src/Reflection.agda
Use generalised variables in `Reflection` so that it is forward-compatible with universe polymorphism (see agda/agda#3793). 
The only exceptions are the `Args` and `map-Arg`, `map-Abs`, and `map-Args` which need explicit arguments so generalised variables cannot save us. They will be patched later.
=> [ new ] use generalised variable

notes/installation-guide.md
Trying to fix #743. The problem with downloading the .tar is that Github automatically gives the contents an ugly name. So when I extract from `agda-stdlib.tar` in step 3. I get a folder called `agda-agda-stdlib-c226a9b` rather than `agda-stdlib`.
Anyone know any bash hackery to get around having to have a release specific `mv agda-agda-stdlib-c226a9b agda-stdlib` command?
=> Update installation instructions to download the .tar file

CHANGELOG.md, src/Data/Product/Nary/NonDependent.agda, src/Function/Nary/NonDependent.agda, src/Function/Nary/NonDependent/Base.agda, src/Relation/Binary/PropositionalEquality.agda, src/Relation/Nary.agda
I got tired of writing `uncurry (cong₂ _∷_)` and invoking `_×-dec_` in #799
so here we go.
=> n-ary decidable equality transformer

CHANGELOG.md, src/Relation/Binary/Reasoning/Base/Double.agda, src/Relation/Binary/Reasoning/Base/Triple.agda
The infix precedence of the generic order reasoning combinators (`_∼⟨_⟩_`, `_≈⟨_⟩_`, etc.) in `Relation.Binary.Reasoning.Base.{Double,Triple}` were lowered when implementing new style reasoning (issue #185).  This lead to inconsistencies in modules that add custom combinators (e.g. `StarReasoning` from `Relation.Binary.Construct.Closure.ReflexiveTransitive.Properties`) using the original fixity (see issue #814 for details).
This PR restores the old fixity.
=> [ fix #814 ] fix inconsistent fixity of reasoning combinators

src/Relation/Binary/PropositionalEquality.agda
Now that n-ary congruence and substitution have been moved out, we
can lose the dependency on Data.Nat.Base. Which happens to make
stdlib compatible with plfa again!
=> [ cleanup ] Relation.Binary.PropositionalEquality

src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid.agda
Gives better jump-to-definition behavior in Emacs.
By using `open M arg renaming (foo to bar)` instead `bar = M.foo arg` I am hoping for better UX.
=> [ Sublist/Setoid ] use open instead of alias for ⊆-refl etc.

src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
I have been needing the category laws for sublists whenever I use them as renamings in formalizations of STLC.
I only added them for the propositional case.  There are generalizations, like for the Setoid-sublist they hold if the Setoid is actually a Category, e.g. having `trans refl = id`.  
In some future, when we have a proper concept of Category in the standard library, we might want such a generalization.
=> [ Sublist.Propositional ] category laws, plus functor laws for All and Any

src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid.agda
OPE does not have proper pushouts.
For weak pushouts, we would need a groupoid rather than a setoid.
However, we can still have raw pushout diagrams without any proven properties.
I plan to extend this PR to weak pushouts in case of Sublist.Propositional.
=> [ Sublist.Setoid ] RawPushout for merging two extensions of a list

src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
Were probably present due to a cut-and-paste error.
=> [ Sublist.Setoid.Properties ] removed spurious module parameters

src/Data/Integer/Properties.agda, src/Relation/Binary/Construct/Add/Infimum/NonStrict.agda, src/Relation/Binary/Construct/Add/Supremum/NonStrict.agda
See agda/agda#3903. Previously Agda sometimes picked the wrong place to move a forced pattern to, resulting (in the worst case) in segfaulting or badly behaved compiled code. Now the forcing translation gives up when it's not sure, and this happens in a small number of places in the standard library. The workaround is to move the match manually to the correct non-forced position.
=> Work-arounds for failing forcing translation

CHANGELOG.md, src/Function/Construct/Composition.agda, src/Function/Construct/Identity.agda, src/Function/Packages.agda, src/Function/Structures.agda
Transferred across the identity and composition constructs to the new function hierarchy. Seems to work pretty well! 
The only major change is that the packages didn't previously export the equality proofs so I've added two modules `Eq₁` and `Eq₂` that contains the equalities for the domain and codomain in the same way that `Eq` does for the binary relation hierarchy.
Comments welcome as always!
=> Proofs about identity and composition for the new function hierarchy

CHANGELOG.md, src/Data/AVL/Map.agda
Implements the simple interface for maps in module `Data.AVL.Map`. Fixes #868 .
I kept the same order of the functions as in the `Data.AVL` module.
Let me know if something needs to be changed.
=> [ fix #868 ] Add Data.AVL.Map

.travis.yml, GenerateEverything.hs, README/Foreign/Haskell.agda, src/Data/Maybe/Base.agda, src/Foreign/Haskell/Coerce.agda, src/Foreign/Haskell/Maybe.agda, src/Foreign/Haskell/Pair.agda
To cross FFI boundaries easily, we can use `coerce` to convert
between the FFI-friendly types and the ones actually use in the
core library with all the functions we know and love.
Note that I had to swap Data.Maybe.Base's constructors so that
they would appear in the same order as the ones for Maybe as
defined in ghc's base.
=> [ fix #826 ] Coercible type class

CHANGELOG.md, src/Algebra/Properties/Semilattice.agda, src/Relation/Binary/Consequences.agda, src/Relation/Binary/Construct/NonStrictToStrict.agda, src/Relation/Binary/Properties/DecTotalOrder.agda, src/Relation/Binary/Properties/Poset.agda, src/Relation/Binary/Properties/Preorder.agda, src/Relation/Binary/Properties/StrictTotalOrder.agda, src/Relation/Binary/Properties/TotalOrder.agda
Started off as an attempt to simply add a few proofs to `Relation.Binary.Construct.NonStrictToStrict` but morphed into fixing the hierarchy in the following properties files:
```
Relation.Binary.Properties.Preorder
Relation.Binary.Properties.Poset
Relation.Binary.Properties.TotalOrder
Relation.Binary.Properties.DecTotalOrder
```
=> Improved inheritance in binary relation properties files

src/Data/Bin/Properties.agda
To do with the new telescope syntax and also #840, as far as I know.
=> Remove invalid brackets in function arguments

CHANGELOG.md, src/Function/Construct/Composition.agda, src/Function/Construct/Identity.agda, src/Function/Packages.agda
It's always annoyed me that there was no corresponding symbol for the right inverse propositional package. The right version of the left-inverse symbol is already used for surjection, so I've taken advantage of the new function hierarchy to re-assign left-inverse to the new symbol `↩` and right inverse now has `↪`.
=> Changed symbol for left-inverse package and added symbol for right-inverse

src/Data/Empty.agda
Commit 907540c55c55d41ffa53330d2f3af16e1ed83899 added it, but it seems to not actually be needed or used. (Maybe I’m missing something, though — apologies in that case.)
=> remove `Level` import from `Data.Empty`

CHANGELOG.md, src/Data/List/Base.agda, src/Data/List/Properties.agda, src/Data/List/Relation/Binary/Equality/Setoid.agda, src/Data/List/Relation/Binary/Pointwise.agda, src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda, src/Data/List/Relation/Ternary/Interleaving/Properties.agda
The properties are much easier to prove for the generalization of
reverse to reverse-append.
Should be backwards compatible.
In the future, we could deprecate `reverseAcc` in favor of `_ʳ++_` (reverse-append).
=> [ Data.List ] function reverse-append _ʳ++_, simplify proofs about reverse

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Properties.agda, src/Data/Vec.agda, src/Data/Vec/Functional.agda, src/Data/Vec/Functional/Relation/Binary/Pointwise.agda, src/Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda, src/Data/Vec/Functional/Relation/Unary/All.agda, src/Data/Vec/Functional/Relation/Unary/All/Properties.agda, src/Data/Vec/Functional/Relation/Unary/Any.agda
Motivation: #870
This pull request introduces vectors defined by index notation. That is, it defines vectors to be functions from `Fin n` to `A`. Assuming function extensionality, this is equivalent to `Vec A n`, but prioritises introduction and elimination via `tabulate` and `lookup`, rather than `[]`/`_∷_` and induction, respectively. This is the same as `Data.Table`, except for not having the unnecessary record wrapper (see #870 and the linked blog post for why it is unnecessary).
I'd like to have a somewhat complete collection of definitions and lemmas before this is merged. This should match use cases for functional vectors, rather than being a copy of what we have for inductive vectors. Remaining issues are as follows:
An important use case is vector/matrix calculus.
=> Functional vectors

src/Data/List/Fresh.agda
Turns out `map` does make sense for fresh lists too as long as a (potentially
new) notion of freshness is respected.
=> [ new ] map for fresh lists

src/Relation/Nullary/Decidable/Core.agda
Undo the recent deprecation of  ⌊_⌋.
=> [ #917 ] Do not deprecate ⌊_⌋, the traditional name of isYes.

src/Data/Nat/Properties.agda
The original `∸-+-assoc` does pattern matching over `m`, `n` and `o`, which seems not necessary. I guess a simpler program/proof is preferred. 
This PR suggests a version that only destructs `m` and `n`, and just uses a rewrite and recursive invocation.
=> Simplify ∸-+-assoc

CHANGELOG.md, src/Data/Bool/Base.agda, src/Relation/Nullary.agda, src/Relation/Nullary/Reflects.agda
This pull request contains the first steps of #929. It introduces `Reflects` and the module `Relation.Nullary.Reflects`, which at the moment just contains lemmas converting between `Reflects P b` and `if b then P else ¬ P`. It redefines `Dec` to contain a boolean value and a `Reflects` proof of it. There are patterns `yes` and `no`, which have behaviour similar to the old constructors of `Dec`. The rest of the library checks without modification. Finally, a bit about all of this has been added to the changelog.
I think with this new set of names (in particular `_because_` and `does`), breaking changes should not be necessary. Some of the existing names may look a bit strange (`isYes`, `True`, `toWitness`, and the corresponding negative definitions are more special-purpose than their names …
=> Add `Reflects` and define `Dec` in terms of it

CHANGELOG.md, README/Dec.agda, src/Relation/Nullary/Decidable/Core.agda, src/Relation/Nullary/Implication.agda, src/Relation/Nullary/Negation.agda, src/Relation/Nullary/Product.agda, src/Relation/Nullary/Reflects.agda, src/Relation/Nullary/Sum.agda
This pull request addresses points 1 and 2 of the plan laid out in #932. The key changes are as follows.
1. `map′` now has definition
```agda
map′ : (P → Q) → (Q → P) → Dec P → Dec Q
does  (map′ P→Q Q→P p?) = does p?
proof (map′ P→Q Q→P ( true because  [p])) = ofʸ (P→Q (invert [p]))
proof (map′ P→Q Q→P (false because [¬p])) = ofⁿ (invert [¬p] ∘ Q→P)
```
This is maximally non-strict, and the `does` half is branch-free. Additionally (I don't know whether this is good or bad) when `b` is a value, `proof (map′ id id (b because r))` will reduce to `of (invert r)`. This is a form of η-expansion. If we wanted to avoid this, the proof of `map′` would pattern match on `[p]` and `[¬p]`, instead of using `invert` below the `ofʸ` and `ofⁿ` constructors.
2. `isYes` (with alias `⌊_⌋`) has definition …
=> Redo Dec-related lemmas in the `Relation.Nullary` hierarchy

src/Function.agda, src/Function/Construct/Composition.agda, src/Function/Construct/Identity.agda
Just realised that agda/agda#4057 is worse than I thought :cry: We can't have the equality relations as module parameters for `Function` as it means that the modules automatically generated from the records, e.g. `IsInjection`, `Injection` etc. get incorrectly parameterised by them when they're not provided.
Really upsetting!
=> Removed module parameters from `Function`

CHANGELOG.md, src/Induction/WellFounded.agda
`Fixpoint.wfRecFixp` proves that `All.wfRec` yields a fixpoint. This is especially useful when defining a type family (in contrast to proving a theorem) using well-founded induction.
=> Added fixpoint proof for well-founded induction

CHANGELOG.md, src/Data/Fin/Subset/Properties.agda, src/Data/Nat/Properties.agda
The proofs that were renamed (x∈s⇒x∉∁s etc.) have been added since v1.2 so no need to deprecate them.
=> Add some more properties to `Data.Fin.Subset.Properties`

CHANGELOG.md, README.agda, README/Tactic/RingSolver.agda, src/Data/Fin/Reflection.agda, src/Data/Nat/Reflection.agda, src/Data/String/Base.agda, src/Data/Word/Base.agda, src/Reflection.agda, src/Reflection/Argument.agda, src/Reflection/Argument/Relevance.agda, src/Reflection/Argument/Visibility.agda, src/Reflection/Definition.agda, src/Reflection/Literal.agda, src/Reflection/Meta.agda, src/Reflection/Name.agda, src/Reflection/Pattern.agda, src/Reflection/Show.agda, src/Reflection/Term.agda, src/Tactic/MonoidSolver.agda, src/Tactic/RingSolver.agda, src/Tactic/RingSolver/Core/ReflectionHelp.agda
This is mostly renaming, shuffling of things about and adding additional comments as I go through and try and get my head around reflection.
The one thing I'm not sure about is whether reflection utilities for specific data types should go in `Data.Nat.Reflection` or `Reflection.Data.Nat`? The former is much more standard, i.e. we have `Data.List.Relation` / `Data.Nat.Induction` / `Data.Nat.Tactic`, but maybe reflection is suitably "meta" that it deserves to be all grouped together...
=> Refactor reflection in new RingSolver and MonoidSolver

src/Algebra/Operations/CommutativeMonoid.agda, src/Algebra/Properties/CommutativeMonoid.agda
Whilst trying to improve #1078 I've run into several other outstanding issues:
- (#759) it uses the old function hierarchy via `Data.Fin.Permutation` which we also want to deprecate.
- (#1099) we want to prove most of these lemmas over some `Foldable` type rather than once each for list/vector/vec
Therefore to me, it feels that if we fix these problems by naively transferring the proofs over to `Vector` we're simply generating more code we're going to need to deprecate in the future. This is therefore an alternative PR to #1078 which simply suppresses the warnings for the mean time, and we can tackle the problem more completely in `v1.4`.
@gallais thoughts?
=> Suppress warnings from `Algebra.Properties.CommutativeMonoid`

CHANGELOG.md, src/Data/Product/Relation/Binary/Lex/NonStrict.agda, src/Data/Product/Relation/Binary/Lex/Strict.agda, src/Induction/WellFounded.agda
The existing proof defined it's own custom relation which was used nowhere else in the library and so was virtually useless. It's now deprecated, and the proof has been transferred across to the relation defined in `Data.Product.Relation.Binary.Lex.Strict` instead.
=> Deprecated `Induction.WellFounded.Lexicographic`

src/Category/Applicative.agda, src/Category/Applicative/Indexed.agda, src/Category/Applicative/Predicate.agda, src/Category/Comonad.agda, src/Category/Functor.agda, src/Category/Functor/Predicate.agda, src/Category/Monad.agda, src/Category/Monad/Continuation.agda, src/Category/Monad/Indexed.agda, src/Category/Monad/Partiality.agda, src/Category/Monad/Partiality/All.agda, src/Category/Monad/Predicate.agda, src/Category/Monad/Reader.agda, src/Category/Monad/State.agda
This PR simply updates all modules in the Category subdirectory to use generalized variables for universe levels and types, hopefully making the type signatures a bit easier to read.
=> Use generalized variables in Category subdirectory

CHANGELOG.md, src/Function/Base.agda
This adds the simple but useful function `it` that uses instance search to fill in an argument of the appropriate type.
=> Add `it` utility function

src/Data/List/Relation/Unary/Any/Properties.agda
I checked the standard library with the now working `-vprofile.definitions:10` and picked the top entry.
Saves about 5s for the price of a more verbose (but readable IMO) proof.
=> Get rid of slow 'rewrite'

CHANGELOG.md, src/Data/Integer/Properties.agda
Fixes the naming conventions used in two proofs added since v1.2.
=> Rename proofs relating < and <' in Data.Integer.Properties

src/Reflection/TypeChecking/MonadSyntax.agda, src/Tactic/MonoidSolver.agda
`Everything.agda` will not build at the moment.
The full stop is necessary for `generateEverything.hs` to realise the module is deprecated
=> finish deprecating MonadSyntax

CHANGELOG.md, src/Codata/Musical/Colist/Infinite-merge.agda, src/Data/Fin/Subset/Induction.agda, src/Data/Nat/Binary/Induction.agda, src/Induction/WellFounded.agda, src/Relation/Binary/Construct/On.agda
Partially addresses #819 for `on`. Changelog entry left until #1039 is merged in.
=> Moved well-founded proofs for `on` to `Relation.Binary.Construct.On`

src/Data/Fin/Base.agda
The comments for fromℕ< and fromℕ<″ still had ≤ in their names remaining from an older version.
=> Fixed function names in comments

CHANGELOG.md, src/Algebra/Bundles.agda
=> Fixed `commutativeSemigroup` re-exports in `Algebra.Bundles`

src/Function/Bijection.agda, src/Function/Equality.agda, src/Function/Equivalence.agda, src/Function/Injection.agda, src/Function/Inverse.agda, src/Function/LeftInverse.agda, src/Function/Surjection.agda
=> Added pseudo-deprecation warnings to old function infrastructure

.gitignore
This resolves issue: #1199 
The folder MAlonzo, and the file Haskell were generated by the build process (specificallly when running `make test` ). Therefore they do not need to be saved in source control management. So it makes sense to include them in the .gitignore file so that future contributors do not accidentally include them in a commit.
=> Update .gitignore (2 entries added)

CHANGELOG.md, src/Data/List/Base.agda, src/Data/List/NonEmpty.agda, src/Relation/Binary/Construct/StrictToNonStrict.agda
This commit partly resolves the issue with inconsistent use of apostrophe and primes: #995
It resolves it for three functions.
This pull request is related to pull request: #1167 . This pull request is simpler, and will therefore be easier to maintain.
I decided to deal with the functions that would have to be deprecated first. Other identifiers will have to be dealt with later. The hope is that this will make use of apostrophe's and primes consistent to the user of the library, which is probably most important. Later on we can make it consistent internally.
Deprecated:
Data.List.Base.InitLast._∷ʳ'_
Data.List.NonEmpty.SnocView._∷ʳ'_
Relation.Binary.Construct.StrictToNonStrict.decidable'
If this looks good, then I can work on making use of apostrophe and primes consistent for local …
=> (apostrophe to prime) Deprecate _∷ʳ'_ (both versions) and decidable' functions.

CHANGELOG.md, src/Algebra/Morphism/RingMonomorphism.agda, src/Data/Rational/Properties.agda
Tiny missing `+-*-isCommutativeRing` and `+-*-commutativeRing` structures from #1072, which were included for [`ℚᵘ` (`Data.Rational.Unnormalised`)](https://github.com/agda/agda-stdlib/pull/1072/files#diff-9b7cc0a9d4127a4b2f3940952508a60aR586) but [not for `ℚ`](https://github.com/agda/agda-stdlib/pull/1072/files#diff-4d7a7de4d2025327784740eb7436dbe8R847).
The reason it was omitted is probably that it was missing from `Algebra.Morphism.RingMonomorphism`, which I've added in the same manner as `isCommutativeMonoid` is done in `Algebra.Morphism.MonoidMonomorphism`.
=> Add `+-*-commutativeRing` structure to `Data.Rational` (ℚ) via ℚᵘ

src/Function/Base.agda
This makes things (like termination and positivity) not break if auto-inlining is no longer the default (agda/agda#4681).
=> INLINE function combinators

fix-whitespace.yaml
This PR updates the `fix-whitespace` config file to match the very slightly different path format required by the recently merged changes to the program. 
See https://github.com/agda/fix-whitespace/pull/5 for more information.
=> Update `fix-whitespace` config file to match new version

CHANGELOG.md, src/Function/Construct/Composition.agda, src/Function/Construct/IsEquivalence.agda, src/Function/Construct/Symmetry.agda, src/Function/Properties/Equivalence.agda, src/Function/Properties/Inverse.agda
Add `Function.Construct.Symmetry`, to go along with its `Identity` and `Composition` cousins.  Put all 3 together in `Function.Construct.IsEquivalence`.
This PR will be needed to continue the work of porting the  Algebra part of `TypeIsomorphisms` to the new-style `Inverse` (and friends).
=> Add Symmetry relations for Inverse (& friends) and IsEquivalence bundles

CHANGELOG.md, src/Data/Rational/Properties.agda
Super minor additional export for consistency. `CHANGELOG.md` updated.
These were technically already available by importing and then opening the exposed `+-*-isRing` bundle (transported from `ℚᵘ`). However this was inconsistent with the other properties (`*-identity`, `*-distrib-+`, etc.) which could be imported directly from `Data.Rational.Properties` as usual.
The definition of these properties is identical to the one created in the `+-*-isRing` structure and consistent with the other declarations.
=> Expose `*-zero`, `*-zeroˡ`, `*-zeroʳ` from `Data.Rational.Properties`

CHANGELOG.md, src/Relation/Binary/Construct/Composition.agda
Hi, I thought it would be useful to have composition of binary relations in Relation.Binary.Construct since I needed it in one of my projects. I also proved a few properties about composition (I tried to be consistent with the other Relation.Binary.Construct modules). Let me know what you think.
=> Add composition in Relation.Binary.Construct

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Properties.agda, src/Data/Vec/Functional.agda, src/Data/Vec/Functional/Properties.agda
I added a bunch of new functions in `Data.Vec.Functional` and also made a `Data.Vec.Functional.Properties` module. This is mostly stuff that I needed in one of my projects, but I'm happy to add more stuff if people are interested (either in this PR or a future one). 
I think `Data.Vec` and `Data.Vec.Functional` should ideally have the same functions, so people can swap one module for the other easily (like I needed to do in my project). However, some existing functions in `Data.Vec.Functional` have slightly different types compared to their analogues in `Data.Vec`. For example, the order of arguments of `remove` is different:
``` agda
-- Data.Vec.Base:
remove : ∀ {n} → Vec A (suc n) → Fin (suc n) → Vec A n
-- Data.Vec.Functional:
remove : ∀ {n} → Fin (suc n) → Vector A (suc n) → Vector A …
```
=> Data.Vec.Functional operations and properties

src/Data/Float/Base.agda
Without this, it's inconvenient to do calculations with multiple
operators.
=> Set precedences for Float arithmetic operators.

CHANGELOG.md, src/Data/Vec/Properties.agda, src/Data/Vec/Relation/Unary/All/Properties.agda, src/Data/Vec/Relation/Unary/AllPairs.agda, src/Data/Vec/Relation/Unary/AllPairs/Core.agda, src/Data/Vec/Relation/Unary/AllPairs/Properties.agda, src/Data/Vec/Relation/Unary/Unique/Propositional.agda, src/Data/Vec/Relation/Unary/Unique/Propositional/Properties.agda, src/Data/Vec/Relation/Unary/Unique/Setoid.agda, src/Data/Vec/Relation/Unary/Unique/Setoid/Properties.agda
Mostly as taken from `Data.List.Relation.Unary.AllPairs`. I had to add a couple of proofs to `Data.Vec.Properties` and `Data.Vec.Relation.Unary.All.Properties`. The work on `Disjoint` is still missing (not sure how important that is). I believe `lookup-injective` is missing from the list counterpart, might be a useful addition.
=> WIP: Introduce AllPairs for vectors

.gitignore
Very minor annoyance fix.
I frequently notice untracked files in the `std-lib` submodule in `agda`. It's caused by the `GenerateEverything` binary being built, which isn't (and oughtn't be) checked in.
This adds it to the `.gitignore` file.
Additionall, this sorts the `.gitignore` file consistently as reqeusted in the comment, and adds an additional comment specifying the command to do so (using `sort -uf`, which means "unique and ignore case", and works the same for GNU/BSD/macOS).
=> Sort `.gitignore` and ignore `GenerateEverything`

CHANGELOG.md, src/Induction/WellFounded.agda
I found out I couldn't use Induction.WellFounded.FixPoint.unfold-wfRec on a type family defined by well-founded recursion on the natural numbers. It should be possible now.
=> Fix level for FixPoint in Induction.WellFounded

stack-8.0.2.yaml, stack-8.10.1.yaml, stack-8.2.2.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml
Added stack.yaml files for the same GHC versions Agda supports:
- stack-8.0.2.yaml
- stack-8.2.2.yaml
- stack-8.4.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.10.1.yaml
=> Added stack.yaml files to match agda/agda

CHANGELOG.md, src/Reflection/DeBruijn.agda, src/Reflection/Traversal.agda
Using it to implement weakening, strengthening and free variable check.
Targeting `experimental` since the reflected term syntax has changed. Once we're happy I can backport to master.
=> Generic traversals of reflected terms

.travis.yml, AllNonAsciiChars.hs, CHANGELOG.md, GenerateEverything.hs, agda-stdlib-utils.cabal, lib.cabal
Happy to split this into multiple PRs, let me know. This contains three small changes:
* Renames the package `lib.cabal` to `agda-stdlib-utils.cabal`, since that is `cabal install`ed and not a good global package name.
* Fixed some tiny hlint suggestions in `GenerateEverything.hs` and `AllNonAsciiChars.hs`
* Fixed `AllNonAsciiChars`, which was failing with "too many open files" on macOS. Some light research indicated this was caused by the lazy IO and that the easiest fix was to use the strict IO from `Data.Text`. I've verified that now works.
=> Tiny build utils enhancements

CHANGELOG.md, notes/release-guide.txt, standard-library.agda-lib
Since Agda supports [library versioning](https://agda.readthedocs.io/en/v2.6.1.1/tools/package-system.html#version-numbers), I suggest the standard-library should make use of it.
=> Add version to library name

CHANGELOG.md, src/Data/List/Properties.agda
I was looking for these when trying to prove that `List` is a `Monad` for `categories-examples`.
We might desire a property similar to `concat-[-]` with type `concat ∘ [_] ≗ id` but that turns out to be `++-identityʳ`.
=> Add some properties relating to List.concat

CHANGELOG.md, src/Data/Vec/Properties.agda
Adds a few properties for `take`, `drop`, and `zipWith`:
- `take-distr-zipWith`: proof that `take` can be distributed over `zipWith`. 
- `take-distr-map`:  proof that `take` can be distributed over `map`. 
- `drop-distr-zipWith`: proof that `drop` can be distributed over `zipWith`. 
- `drop-distr-map`:  proof that `drop` can be distributed over `map`. 
- `take-drop-id`: proof of `take m v ++ drop m v ≡ v`
- `zipWith-replicate`: similar to existing zipWith-replicate₁ but where both arguments are `replicate` vectors. `zipWith _⊕_ (replicate x) (replicate y) ≡ replicate (x ⊕ y)`
=> Data.Vec.Properties: Add take/drop proofs, zipWith-replicate

CHANGELOG.md, src/Data/Vec/Relation/Binary/Pointwise/Extensional.agda, src/Induction/WellFounded.agda, src/Relation/Binary/Construct/Closure/Equivalence.agda, src/Relation/Binary/Construct/Closure/Reflexive.agda, src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda, src/Relation/Binary/Construct/Closure/Reflexive/Properties/WithK.agda, src/Relation/Binary/Construct/Closure/Symmetric.agda, src/Relation/Binary/Construct/Closure/Transitive.agda
Some tidying:
- use variables
- standardise closure names to `XClosure`
- add additional proofs for `TransClosure` including well-foundedness
- deprecate `Induction.WellFounded.TransitiveClosure` (fixes #819 fixes #1310)
=> Tidying up in `Relation.Binary.Construct.Closure`

CHANGELOG.md, GenerateEverything.hs, src/Reflection/Annotated.agda, src/Reflection/Annotated/Free.agda, src/Reflection/Universe.agda
On top of #1324.
Defines annotated reflected syntax and functions for computing and traversing it.
Use case: free variable annotations.
Note: not compatible with `--without-K`
=> Annotated reflected syntax

CHANGELOG.md, src/Algebra/Bundles.agda, src/Relation/Binary/Bundles.agda
=> Fix precedence of _≉_ and re-export it via algebraic bundles

src/Data/Vec/Base.agda
Fixes #1338. Note that `zipWith` is already defined as
```agda
zipWith : ∀ {n} → (A → B → C) → Vec A n → Vec B n → Vec C n
zipWith f []       []       = []
zipWith f (x ∷ xs) (y ∷ ys) = f x y ∷ zipWith f xs ys
```
so we're only making things consistent here.
=> [ fix agda#1338 ] Made Data.Vec._⊛_ stricter

CHANGELOG.md, src/Algebra/Morphism.agda, src/Function/Endomorphism/Propositional.agda, src/Function/Endomorphism/Setoid.agda, src/Relation/Binary/Morphism/Construct/Composition.agda, src/Relation/Binary/Morphism/Construct/Constant.agda, src/Relation/Binary/Morphism/Construct/Identity.agda, src/Relation/Binary/Morphism/Structures.agda, src/Relation/Binary/OrderMorphism.agda
Fixes #1301 by adding some missing constructions and then deprecating the last of the old morphism-related code.
=> Add constructions over binary morphisms and deprecated old morphism code

CHANGELOG.md, src/Codata/Thunk.agda, src/Relation/Unary/Sized.agda, src/Size.agda
One proposal in continuation of #1326: remove `_⇒_` and `∀[_]` on `SizedType`
See discussion around https://github.com/agda/agda-stdlib/pull/1326#discussion_r511751993.
The nested module is not in style with the `std-lib`, and exporting these short definitions on top-level creates unpleasant clashes with `Relation.Unary`.
Thus, one solution is to remove the offending definitions and wait whether they will grow back naturally.
@MatthewDaggitt suggested instead:
> I think a better solution is to mimic the normal module hierarchy underneath `Size` just as we do elsewhere in the library. For example we would put `∀[_]` in `Size.Relation.Unary` and `_⇒_` in `Size.Function`. That would make it so much easier to expand these later on if we found it necessary.
=> Bikeshedding #1326: what to do about _⇒_ and ∀[_] on SizedType

CHANGELOG.md, GenerateEverything.hs, src/Foreign/Haskell/Coerce.agda, src/IO.agda, src/System/Environment.agda, src/System/Environment/Primitive.agda
I am not convinced gallais/agda-sizedIO will be ready any time soon.
So we may as well add the bindings needed to write some very basic
programs for the current IO we have.
This adds the much-needed `getArgs` and every other safe function in
`System.Environment`.
=> [ new ] bindings for System.Environment

README/Foreign/Haskell.agda, src/Data/String/Base.agda
I added uncons in https://github.com/agda/agda/pull/4494 but somehow forgot to come here to re-export it.
=> [ fix ] re-export uncons and cleanup `Data.String.Base`

CHANGELOG.md, src/Algebra/Operations/CommutativeMonoid.agda, src/Algebra/Operations/Semiring.agda, src/Algebra/Properties/CommutativeMonoid.agda, src/Algebra/Properties/CommutativeMonoid/Summation.agda, src/Algebra/Properties/Monoid/Multiplication.agda, src/Algebra/Properties/Monoid/Summation.agda, src/Data/Vec/Functional.agda, src/Data/Vec/Functional/Relation/Binary/Equality/Setoid.agda
This is the first stage of deprecating the `Algebra.Operations.X` modules (where `X` is some bundle) which currently scale poorly as more operations are added and are implemented very inconsistently:
- some contain operation definitions, some also contain proofs. 
- some are parameterised by the raw bundle, some by a standard bundle.
The new design is `Algebra.Properties.X.Y` (where `X` is some bundle and `Y` is some operation). This separates individual operations out, improving modularity and inheritance of properties from different bundles in the hierarchy.
This initial PR handles the `CommutativeMonoid` bundle. As well as implementing the changes described above, it also switches over to using `Data.Vec.Functional` for summations instead of the deprecated `Data.Table`, which should go …
=> Deprecate `Algebra.Operations.CommutativeMonoid`

CHANGELOG.md, src/Data/List/Relation/Binary/BagAndSetEquality.agda, src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda, src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda, src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda, src/Data/List/Relation/Binary/Subset/Setoid.agda, src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
- Updated names to match current conventions
- Added a bunch of new properties
Some small problems with `BagAndSetEquality` causing cyclic imports, as it fails to follow the conventions of the other binary relations in this part of the library. That module has needed sorting out for many years, and I _almost_ had the willpower to do it this time.... however, in the end I took the easy route out and contained it's craziness by moving `↭⇒∼bag` and `∼bag⇒↭` from
`Data.List.Relation.Binary.Permutation.Setoid.Properties` to `Data.List.Relation.Binary.BagAndSetEquality`
=> Revamp of `Data.List.Relation.Binary.Subset`

CHANGELOG.md, README/Foreign/Haskell.agda, README/IO.agda, src/Data/String/Base.agda, src/IO.agda
Once again: given that sized IO is not around the corner, we may as
well make the best of what we have. This means making it easier to
use `do`-notations when we don't actually need to rely on guardedness.
=> [ refactor ] IO module

CHANGELOG.md, src/Algebra/Operations/Semiring.agda, src/Algebra/Properties/Monoid/Multiplication.agda, src/Algebra/Properties/Semiring/Exponentiation.agda, src/Algebra/Properties/Semiring/Multiplication.agda, src/Algebra/Solver/Ring.agda, src/Algebra/Solver/Ring/NaturalCoefficients.agda, src/Algebra/Solver/Ring/NaturalCoefficients/Default.agda
Continuing what #1351 started by deprecating `Algebra.Operations.Semiring` in favour of `Algebra.Properties.Semiring.Multiplication` and `Algebra.Properties.Semiring.Exponentation`.
=> Deprecate `Algebra.Operations.Semiring`

fix-whitespace.yaml, notes/style-guide.md, src/Data/List/Relation/Unary/All.agda, src/Data/List/Relation/Unary/All/Properties.agda, src/Data/List/Relation/Unary/Any.agda, src/Data/List/Relation/Unary/Any/Properties.agda
This PR updates the standard library's policy for using the `variable` keyword in the style guide as per the discussion in #1325. I've tried it out on `Data.List.Relation.Unary.(Any/All)` and I think I'm happy that the result improves readability without harming understandability too much. Comments welcome obviously!
=> Update variable policy in style guide

CHANGELOG.md, src/Data/Fin/Properties.agda
This is another useful piece of showing that finite types are a skeleton of the semiring of types. I've needed it independently too.
=> add property Fin0↔⊥

src/Data/Nat/DivMod.agda
I've proven the one lemma that we were using the ring solver for by hand.
=> Remove dependy on Data.Nat.Tactic.RingSolver in Data.Nat.DivMod

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Properties.agda
See also #1422 
There has been discussion about whether the type of `combine` should be altered to match the multiplication and the return type. Currently it matches the type of `quotRem`. I'm not certain how to resolve this.
=> Add Data.Fin.combine as inverse of quotRem, and properties thereof

README.md
The `low-hanging-fruit` tag doesn't have the prefix `status:` anymore, so the link in the `README.md` was broken. This PR fixes that.
=> Fix broken link to the "low-hanging-fruit" tag

src/IO/Finite.agda
It looks like it was made `putStr` by mistake
=> IO.Finite.putStrLn: actually do putStrLn

.travis.yml, CHANGELOG.md, src/Reflection/Annotated.agda, src/Reflection/Show.agda, src/Reflection/Term.agda, src/Reflection/Traversal.agda, travis/index.agda, travis/index.sh
This PR makes the necessary changes to add the three new constructors of the `Sort` datatype in the reflected syntax which are added to Agda itself in https://github.com/agda/agda/pull/5289.
=> Adapt to https://github.com/agda/agda/pull/5289

CHANGELOG.md, src/Data/Rational/Unnormalised/Properties.agda, src/Relation/Binary/Consequences.agda, src/Relation/Binary/Morphism.agda, src/Relation/Binary/Morphism/Bundles.agda, src/Relation/Binary/Morphism/Construct/Composition.agda, src/Relation/Binary/Morphism/Construct/Constant.agda, src/Relation/Binary/Morphism/Construct/Identity.agda, src/Relation/Binary/Properties/Poset.agda
Fixes #1407. 
Pinging @JacquesCarette and @sstucki to let you know that this can be used to undo some of the ugliness I introduced in https://github.com/agda/agda-categories/pull/243 when `v1.6` releases.
Unfortunately I had to remove the module-level arguments in the files I introduced last release, but I think it's unlikely anyone has got round to using them seriously yet!
=> Add bundles for morphisms over binary relations

CHANGELOG.md, src/Data/List/Relation/Unary/First/Properties.agda
`first?` works on `First P (∁ P)` but it seems there is no equivalent for `First (∁ P) P`.
So I added `first?′` which is a swapped variant of `first?`.
I'll request better name for `first?′`, by the way.
=> add variant of `first?`

README.agda, src/IO/Primitive.agda, src/IO/Primitive/Finite.agda, src/IO/Primitive/Infinite.agda
Fixes #1473 by documenting in the `.Primitive` modules that they shouldn't be imported directly. I've also updated and moved the documentation in the README file to a more prominent position.
=> Improve documentation in `.Primitive` modules

CHANGELOG.md, src/Data/Digit.agda, src/Data/Nat/GCD.agda
Also bumping this to `v1.6`. In @bobatkey's example code, we've gone from the `n = 2` case taking ~1 second to compute 3 digit approximations, to the `n = 14` case taking ~1 second to compute ~200 digit approximations, so this really is a _major_ performance boost.
=> [ fix #1476 ] improve performance of rational numbers

src/Data/Nat/Properties.agda
[ fixed #1484 ] prove m<n⇒m≤1+n by composition ≤-step ∘ <⇒≤
The pattern matching proof is a bit awkward (as the property is, which
combines two steps of information loss).
=> [ fixed #1484 ] prove m<n⇒m≤1+n by composition ≤-step ∘ <⇒≤

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Induction.agda, src/Data/Nat/Induction.agda, src/Induction/Nat.agda
At the moment, if you want to prove something by induction that the termination checker doesn't agree is terminating you are forced to pollute the type of your proof with an `Acc` predicate. These new proofs internalise the `Acc` predicate which often makes them much easier and shorter to use, in particular the `Fin` variants which often require a lot of messing around with `inject` and `lower`.
I've left the predicate arguments explicit (to help readability?) but let me know if you think they should be implicit.
=> Added weak-induction schemes for `Data.Fin` and `Data.Nat`

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Properties.agda
During the process of implementing https://github.com/agda/agda-categories/pull/274, @JacquesCarette pointed out that one of the functions I implemented existed in the stdlib under the name `punchIn`. However, this injective function has a surjective counterpart that seems to be missing. This PR adds this function under the name `pinch`, and proves some simple properties about it.
I'm not 100% attached to the name, perhaps `pinchIn` would be more appropriate to highlight the connection to `punchIn`. There are also a handful of identities that we can prove relating `pinch` to `punchIn` (See https://en.wikipedia.org/wiki/Simplicial_set#Face_and_degeneracy_maps and https://github.com/agda/agda-categories/pull/274/files#diff-d758c95623d24b748cbba2280dcde56f96e72c64c271bab9afdc4e068efe8117R114) …
=> Define 'pinch' as a counterpart to 'punchIn'

GenerateEverything.hs, agda-stdlib-utils.cabal
Solidifying the fix of #1510.  Just don't use `error` for reporting errors to the user.
The discussion at https://gitlab.haskell.org/ghc/ghc/-/issues/19917 strongly discouraged me from ever considering `error` as a means to report errors to the user.  I already knew it was bad style, but now I know that it is not guaranteed to deliver the correct message at all.
=> [ Improved fix #1510 ] Get rid of `error`, use `throwError` and `die`.

.github/workflows/ci-ubuntu.yml
This is a fix building on #1516. It should be merged prior to anything else to
preserve the docs for the old versions & `experimental`.
=> [ actions ] preserves old HTML doc

CHANGELOG.md, src/Data/Rational/Base.agda, src/Data/Rational/Properties.agda
Starting off addressing v2.0 issues with a nice and easy one. Fixes #747.
=> Stop `Data.Rational.Base` exporting `+0` and `+[1+_]`

CHANGELOG.md, src/Algebra/Morphism/Construct/Composition.agda, src/Algebra/Morphism/Construct/Identity.agda, src/Algebra/Morphism/RingMonomorphism.agda, src/Algebra/Morphism/Structures.agda, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda
This redefines NearSemiring, Semiring, and Ring homomorphisms so that
they each build up by adding a single new property to a smaller
structure. This ensures there's only one proof that they're a Rel
homomorphism. For the same reason, Lattice homomorphisms are defined
directly rather than showing it's two magma homomorphisms.
I've tried to make it so that each of these structures provides any
smaller structure at its top level, so if we have a RingMonomorphism we
can easily say that it's a MagmaHomomorphism by multiplication or
whatever, but I might have missed one or two.
Closes #1539
=> Remove redundancy in ring morphisms etc

CHANGELOG.md, src/Codata/Cofin.agda, src/Codata/Conat/Properties.agda, src/Codata/Covec.agda, src/Codata/Covec/Properties.agda, src/Codata/Delay/Properties.agda, src/Codata/M/Bisimilarity.agda, src/Codata/M/Properties.agda, src/Codata/Musical/Cofin.agda, src/Codata/Musical/M/Indexed.agda, src/Codata/Stream/Categorical.agda, src/Codata/Stream/Properties.agda, src/Function.agda, src/Function/Base.agda, src/Function/Core.agda, src/Function/Strict.agda, src/Strict.agda, src/Text/Format/Generic.agda, src/Text/Printf.agda
In response to #1486. Haven't yet cut the dependency of `Function.Base` on `Function.Strict` in order to preserve backwards compatibility.
=> Move `Strict` to `Function.Strict` and move `_$!_` there

CHANGELOG.md, src/Data/Vec/Base.agda, src/Data/Vec/Categorical.agda, src/Data/Vec/Properties.agda, src/Data/Vec/Relation/Unary/Any/Properties.agda
I added some function and properties about `Vec`.
The `diagonal` function is a join for monad instance of `Vec` (that is compatible for zip applicative instance of `Vec`), so I added it to `Data.Vec.Categorical`
Though it seems correct monad instance, I couldn't proof that `diagonal` satisfies associative law for monad in agda yet.
=> add `diagonal` and some properties about `Vec`

CHANGELOG.md, src/Algebra/Construct/DirectProduct.agda, src/Algebra/Morphism/Structures.agda, src/Data/Nat/Properties.agda
This is the project of adding to `src/Algebra/Construct/DirectProduct.agda` 
the following instances for the direct product of two (semi)rings:
``(Semi)Ring, Commutative(Semi)Ring``.
Currently it has  ``rawSemiring, semiringWithoutAnnihilatingZero, semiring, commutativeSemiring``.   
If and after it is accepted, the `(Commutative)Ring` instance could be added there.
changed:      CHANGELOG.md
changed:      src/Algebra/Construct/DirectProduct.agda
changed:      src/Algebra/Morphism/Structures.agda
=> (Semi)Ring instances for DirectProduct 

CHANGELOG.md, README/Data.agda, README/Data/Default.agda, src/Data/Default.agda
Essentially:
```agda
-- `inc` increments its argument by the value `step`, defaulting to 1
inc : {{step : WithDefault 1}} → Nat → Nat
inc {{step}} n = step .value + n
-- and indeed incrementing 2 gives you 3
_ : inc 2 ≡ 3
_ = refl
-- but you can also insist that you want to use a bigger increment by
-- passing the `step` argument explicitly
_ : inc {{10 !}} 2 ≡ 12
_ = refl
```
=> [ new ] Data.Default

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Properties.agda
Fixes #1440. They can now be used to relate terms of types `Fin m` and `Fin n` rather than just types `Fin n` and `Fin n`
=> Generalised ordering relations in `Fin`

GenerateEverything.hs
When `Everything.agda` is used to build the entire contents of the library, we want to include the deprecated modules too, as they are still a usable part of the library. In particular, currently the nixpkgs version of agda-stdlib leaves deprecated modules unusable.
=> [ new ] GenerateEverything --include-deprecated flag

CHANGELOG.md, src/Data/Rational/Base.agda, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Base.agda, src/Data/Rational/Unnormalised/Properties.agda
Finishes off the first pass through of using instance arguments for `NonZero` proofs started in #1538. No major design issues reared their head, although a couple of the `gcd` related proofs are not quite as slick as they could be due to what I think is probably a bug in Agda which I've reported via https://github.com/agda/agda/issues/5494.
=> Use `NonZero` instance arguments through `Data.Rational`

CHANGELOG.md, src/Data/Digit.agda, src/Data/Integer/Base.agda, src/Data/Integer/Divisibility.agda, src/Data/Integer/Divisibility/Signed.agda, src/Data/Integer/Properties.agda, src/Data/Nat/Binary/Properties.agda, src/Data/Nat/Coprimality.agda, src/Data/Nat/DivMod.agda, src/Data/Nat/Divisibility.agda, src/Data/Nat/GCD.agda, src/Data/Nat/Properties.agda, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda
I've gone through all of `Data.Nat` and `Data.Integer` folders looking for proofs which use the old way of ensuring something was `NonZero` (by taking an argument `n` and only using it in the form `suc n`),  and adapted them to use the new `NonZero` instance argument approach.
This has eliminated a lot of places where we were using these proofs and having to use `suc (pred x)` instead of `x` merely to manipulate into the form `suc _`.
=> Adapted proofs in `Data.Nat` and `Data.Integer` that used the old `suc` trick to use `NonZero`

CHANGELOG.md, src/Data/Integer/Base.agda, src/Data/Integer/DivMod.agda, src/Data/Integer/Properties.agda, src/Data/Nat/Base.agda, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda
This plays the same game with `Positive`/`Negative`/`NonPositive`/`NonNegative` as https://github.com/agda/agda-stdlib/pull/1538 did with `NonZero`. We get all the same benefits as the `NonZero` case. Will post something about on Zulip and the mailing list tomorrow.
=> Switch `Positive/Negative/etc.` to use irrelevant instance arguments

CHANGELOG.md, HACKING.md, src/Data/Fin/Base.agda, src/Data/Fin/Properties.agda, src/Data/Vec/Functional.agda, src/Data/Vec/Functional/Properties.agda, src/Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda, src/Data/Vec/Functional/Relation/Unary/All/Properties.agda, src/Data/Vec/Properties.agda
New names in `Data.Fin.Base` , as discussed.
Knock-on consequences for `Data.Fin.*` `Data.Vec.*`, as discussed. 
Passes fix-whitespace and GenerateEverything tests. 
Old definitions *not* deleted, only deprecated. 
Deprecate warning notices added. 
CHANGELOG.md updated.
=> committed changes as per Issue #1589

CHANGELOG.md, src/Relation/Binary/PropositionalEquality/Properties.agda
Needed `J` to be universe-polymorphic, surprised it wasn't.
Would it be considered a breaking change in the changelog?
=> Make J universe-polymorphic on A

CHANGELOG.md, src/Data/Vec/Relation/Binary/Equality/Setoid.agda
Unclear, why it was not there. But it is provable.
=> associativity for vectors

CHANGELOG.md, src/Data/Nat/DivMod.agda
In `+-distrib-/-∣ʳ`,  `m` should be explicit and `n` should be implicit.
=> Fix implicit arguments in +-distrib-/-∣ʳ

CHANGELOG.md, src/Data/List/Relation/Binary/Lex/Strict.agda
Proof `xs≮[] : ∀ xs → ¬ xs < []` added as per discussion. 
CHANGELOG.md suitably updated. 
Old proof of `¬[]<[] : ¬ [] < []` now defined to be`xs≮[] []` (and definitionally equal to previous definition)
=> Resolve Issue #602:new lemma added

CHANGELOG.md, README/Tactic/RingSolver.agda, src/Reflection/AlphaEquality.agda, src/Reflection/Term.agda, src/Tactic/RingSolver.agda, src/Tactic/RingSolver/Core/AlmostCommutativeRing.agda
Unsure whether to call the alpha equality operator `_=α=_` or `_==α_` or `_==ₐ_`. Thoughts?
Also note that I've exposed the alpha equality operator `_=α=_` via instance arguments. I've recently been working on my first major Haskell project and now understand instance arguments way better (better late than never I guess!). This can be taken as a declaration of intent that `v2.0` of the library is actually going to make use of them in a non-trivial way. Hopefully more appearing on this soon.
=> Add alpha equality over reflected terms and used it to support `_-_` in `Tactic.RingSolver`

CHANGELOG.md, README/Tactic/Rewrite.agda, src/Reflection/AlphaEquality.agda, src/Reflection/Literal.agda, src/Reflection/Meta.agda, src/Reflection/Name.agda, src/Tactic/Rewrite.agda
This PR adds a new tactic`rw`, which is a simple equality rewriting tactic, intended to be used in equational reasoning blocks.
When performing large equational reasoning proofs, it's extremely common to find yourself constructing sophisticated lambdas to pass into `cong`. This is extremely tedious, and can bog down large proofs in piles of verbose boilerplate. Normally one would use `rewrite` to avoid having to write out these complicated `cong` expressions, but this can obscure the proof, and is often impossible (IE: when using `Relation.Binary.Reasoning.Preorder`).
We solve this problem by introducing a new tactic, `rw`, that gives us a similar level succinctness as `rewrite`, but without it's restrictions. It operates by inferring the type of the goal, anti-unifying both ends of the …
=> Rewriting Tactic

CHANGELOG.md, README/Tactic/Rewrite.agda, src/Data/Fin/Properties.agda, src/Data/Fin/Subset/Properties.agda, src/Data/List/Countdown.agda, src/Data/List/Fresh/Relation/Unary/Any.agda, src/Data/List/Relation/Binary/Lex.agda, src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda, src/Data/Maybe/Relation/Binary/Connected.agda, src/Data/Maybe/Relation/Binary/Pointwise.agda, src/Data/Maybe/Relation/Unary/All.agda, src/Data/Maybe/Relation/Unary/Any.agda, src/Data/Nat/Divisibility.agda, src/Data/Nat/Properties.agda, src/Data/Vec/Relation/Binary/Lex/Core.agda, src/Data/Vec/Relation/Binary/Pointwise/Extensional.agda, src/Data/Vec/Relation/Binary/Pointwise/Inductive.agda, src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda, src/Relation/Binary/Construct/Closure/Transitive.agda, src/Relation/Nullary/Decidable.agda, src/Tactic/Rewrite.agda
I was annoyed that `Data.Fin.Properties` depended on both the old and the new hierarchy, and pulled the thread.
Part of #759
=> Switch to new function hiearchy in several places

CHANGELOG.md, src/Relation/Unary.agda
Adds `_∖_  : Pred A ℓ₁ → Pred A ℓ₂ → Pred A _` in
`Relation.Unary`. The operator is implemented directly as a function on
elements rather than in terms of `∁` and `_∩_` in order to
*  be consistent with how the other operators on predicates in
`Relation.Unary` are implemented; and
*  express the meaning of the operator as clearly as possible.
=> Add a difference operator for predicates

CHANGELOG.md, src/Data/Nat/Coprimality.agda, src/Data/Nat/Divisibility.agda, src/Data/Nat/GCD.agda, src/Data/Nat/Primality.agda, src/Data/Nat/Properties.agda
This is something that'll be very useful for number theory proofs involving prime numbers.
There's two reasons I'm not quite happy with this addition:
* The proof is a little messy in parts
* The proof depends on Bézout's lemma, and `Data.Nat.GCD` is a heavy dependency to add to the `Data.Nat.Primality` module.
I'd like to discuss these a bit to see if they can be resolved or mitigated.
=> Improve definition of `Prime` and add Euclid's lemma

CHANGELOG.md, src/Relation/Unary/Algebra.agda, src/Relation/Unary/Polymorphic/Properties.agda, src/Relation/Unary/Properties.agda, src/Relation/Unary/Relation/Binary/Equality.agda, src/Relation/Unary/Relation/Binary/Subset.agda
These include:
- setoid bundles for `_≐_` and `_≐′_`;
- properties about the subset relations `_⊆_`, `_⊂_`, `_⊆′_`, `_⊂′_`;
- the analogues of the properties about the predicates `∅` and `U` of level `0ℓ` for the level-polymorphic predicates `∅` and `U` from `Relation.Unary.Polymorphic`;
- algebraic properties about `_∩_` and `_∪_`. Here I have used the level-polymorphic `∅` and `U`;
- order structures and bundles for the subset relations, e.g. `_⊆_` is a partial order and `_⊂_` a strict partial order.
I have made the following choices:
- I have only added proofs for the combinations `_⊆_`, `_⊂_` and `_≐_` and `_⊆′_`, `_⊂′_` and `_≐′_`;
- for the structures, I have used implicit arguments and for the bundles explicit arguments `A` and `ℓ`. I don’t know what is best practice here.
=> Add properties about unary predicates

CHANGELOG.md, src/Data/Vec/Base.agda, src/Data/Vec/Properties.agda
While working on #1668 with @jamesmckinna I noticed that some of the code in `Data.Vec(.Properties)` is pretty ancient by the library standards. I've tried to modernise the code by:
- introducing variables for sizes/elements/vectors as now allowed by the style guide
- importing `Relation.Binary.PropositionalEquality` unqualified
- using new combinators in propositional reasoning
- reorganising the file slightly to match the layout of `Base`
Should be a very nearly a no-op, modulo the movement of a couple of implicit arguments due to variables, a breakage which is acceptable in v2.0 I think.
=> Modernise `Data.Vec(.Properties)`

CHANGELOG.md, src/Algebra/Core.agda, src/Algebra/Module.agda, src/Algebra/Module/Bundles.agda, src/Algebra/Module/Consequences.agda, src/Algebra/Module/Core.agda, src/Algebra/Module/Definitions.agda, src/Algebra/Module/Definitions/Bi.agda, src/Algebra/Module/Definitions/Left.agda, src/Algebra/Module/Definitions/Right.agda, src/Algebra/Module/Morphism/Definitions.agda, src/Algebra/Module/Structures.agda, src/Algebra/Module/Structures/Biased.agda
Based on discussion in #1676.
I don't know how to represent this in the changelog.
=> Move definitions from Algebra.Core to Algebra.Module.Core

CHANGELOG.md, src/Algebra/Construct/DirectProduct.agda, src/Algebra/Construct/Subst/Equality.agda, src/Algebra/Lattice/Properties/BooleanAlgebra.agda, src/Algebra/Morphism/RingMonomorphism.agda, src/Algebra/Structures.agda, src/Algebra/Structures/Biased.agda, src/Data/Bool/Properties.agda, src/Data/Integer/Properties.agda, src/Data/Nat/Binary/Properties.agda, src/Data/Nat/Properties.agda, src/Data/Product/Algebra.agda, src/Data/Rational/Unnormalised/Properties.agda, src/Relation/Unary/Algebra.agda
Closes #1617 
Currently various ring-like structures carry two different proofs that their underlying equivalence relation is an equivalence relation, because they're built out of a group for + and a monoid for * or similar. This changes the definitions so that they're only defined in terms of the + structure, with the * properties as extra laws. This makes their structure more linear and prevents the two isEquivalence proofs
=> Remove duplication in Ring-like structures

CHANGELOG.md, src/Algebra/Bundles.agda, src/Algebra/Structures.agda
Define Rng as mentioned in #1687 
Should we call it RingWithoutOne or Rng?
=> Define Rng

src/Algebra/Bundles.agda, src/Algebra/Structures.agda
Should the binary operations be congruent? Like: 
> record IsQuasigroup (∙ \\ // : Op₂ A) : Set (a ⊔ ℓ) where
field
isEquivalence :  IsEquivalence _≈_
∙-cong        : Congruent₂ ∙
\\\\-cong        : Congruent₂ \\\\
//-cong        : Congruent₂ //
leftDivides  :  LeftDivides ∙ \\\\
rightDivides :  RightDivides ∙ //
=> Add missing instance to quasigroup and loop.

src/Algebra/Bundles.agda, src/Algebra/Structures.agda
I am sorry for missing this. But this change is essential when we try to define direct product for the quasigroup.
=> Minor fixes to quasigroup

src/Induction.agda
Just pointing documentation in Induction.agda to the right place: Induction.Nat -> Data.Nat.Induction; the former doesn't exist (anymore?) AFAICT.
=> [ re #1380 ] small doc correction in Induction.agda

CHANGELOG.md, src/Data/Fin/Properties.agda
I needed a proof for the injectivity of lower₁ in Data.Fin, but the standard library did not contain such a proof. After writing it I realized that I might as well contribute it back upstream as it seems useful enough, so I cleaned it up to (hopefully) comply with the style guidelines.
=> Add injectivity proof for Data.Fin.lower₁

CHANGELOG.md, src/Data/Fin/Substitution.agda, src/Data/Fin/Substitution/Example.agda, src/Data/Fin/Substitution/Lemmas.agda, src/Data/Integer/Base.agda, src/Data/Integer/DivMod.agda, src/Data/Nat/Base.agda, src/Data/Nat/DivMod.agda, src/Data/Rational/Base.agda, src/Data/Rational/Unnormalised/Base.agda, src/Data/Rational/Unnormalised/Properties.agda
The dependency graph of `Data.Rational.Unnormalised.Base` was pretty huge, as it requires importing `Data.Nat.DivMod` which in turn imports `Data.Nat.Properties`.
This PR fixes the problem by moving the definitions of `_/_` and `_%_` to `Data.Nat.Base` (and similarly for `Data.Integer.Base` for the integer variants).
This is backwards compatible, and feels like absolutely the right thing to do, but opens up a whole thorny set of questions about library design such as should we move more definitions into `Data.Nat.Base`, e.g. `_|_` from `Data.Nat.Divisibility.Core` (a horrible module to exist)?, or `Prime` from `Data.Nat.Primality`?
But we unfortunately can't move _all_ function or predicate definitions in there, as e.g. the implementation of `gcd` or `!_` relies on well-foundedness and …
=> Moved `_/_` and `_%_` to `Base` modules

CHANGELOG.md, src/Codata/Guarded/Stream.agda, src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda, src/Codata/Guarded/Stream/Relation/Unary/All.agda, src/Codata/Guarded/Stream/Relation/Unary/Any.agda
I'm using this for a bunch of personal projects so I'd like to get it in stdlib. However, it's nowhere near ready, really.
I'm only defining Streams for now because they have a regular structure, I don't need to worry about Maybes like I would with Colists or Conats defined this way.
I don't know how far I want to take various relations and properties. "All the way" might be the right answer for this.
I tried to be at least as complete as the other two definitions of streams, but I couldn't figure out how to implement some things, such as `interleave⁺ : List⁺ (Stream A) → Stream A`
=> Codata streams by coinductive records

CHANGELOG.md, src/Codata/Guarded/Stream.agda, src/Codata/Guarded/Stream/Properties.agda, src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda, src/Codata/Sized/Stream/Properties.agda, src/Data/Nat/GeneralisedArithmetic.agda, src/Data/Vec/Base.agda
Following #1693, a bunch of properties.
I renamed some of the functions in `Codata.Guarded.Stream.Relation.Binary.Pointwise`
to match the definitions in `Codata.Sized.Stream.Bisimilarity`. This highlights an issue:
`Relation.Binary.Pointwise` vs. `Bisimilarity`. We should probably settle on one naming
scheme and use it throughout.
=> [ new ] Codata.Guarded.Stream.Properties

CHANGELOG.md, src/Data/List/Base.agda, src/Data/List/Relation/Unary/Unique/DecSetoid/Properties.agda, src/Data/Product.agda, src/Data/String.agda, src/Data/String/Base.agda, src/Data/Vec/Base.agda
Fixes https://github.com/agda/agda-stdlib/issues/920. For each function that took a decidable predicate as an argument, adds a new boolean valued version of it, and redefines the existing predicate version in terms of it.
Bikeshedding about the naming convention welcome!
=> Added boolean versions of List/Vec functions that use predicates

CHANGELOG.md, src/Data/Sum/Properties.agda
Recently I found myself wanting to write this function
```agda
splitPermute↔ : (m : ℕ) {n : ℕ} → 𝔽 (m + n) ↔ 𝔽 (n + m)
splitPermute↔ m {n} = +↔⊎ {m} {n} ∘-↔ (swap↔ ∘-↔ flip +↔⊎)
```
where `flip` is defined as
```agda
flip : ∀ {a b} {A : Set a} {B : Set b} → A ↔ B → B ↔ A
flip A↔B =
record { f = f⁻¹ A↔B
; f⁻¹ = f A↔B
; cong₁ = cong₂ A↔B
; cong₂ = cong₁ A↔B
; inverse = ×-swap (inverse A↔B) }
where
open import Data.Product using () renaming (swap to ×-swap)
```
`swap↔` wasn't available so I've added it in module `Data.Sum.Properties`. It's similar to `+↔⊎` in `Data.Fin.Properties`. 
I would also be very interested in suggestions about whether you think there is a need for the `flip` function somewhere in the Standard Library. Or perhaps there is already a function which does the same thing?
=> Add an Inverse for `swap` in module `Data.Sum.Properties`

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Permutation/Components.agda, src/Data/Fin/Properties.agda
Goes through the files using variables where possible to clean up the type signatures. Also a minor bit of refactoring to ensure the more recent additions to the file obey the conventions in the style guide. The breaking change is the moving of the argument of `opposite-suc` from implicit to explicit.
=> Use variables in `Data.Fin` and `Data.Fin.Properties`

CHANGELOG.md, src/Data/List/NonEmpty.agda, src/Data/List/NonEmpty/Base.agda, src/Data/List/NonEmpty/Properties.agda, src/Data/List/NonEmpty/Relation/Unary/All.agda
Reasons for this change:
1. Should live in `Data.List.NonEmpty.Base` but because they mixed computation and proofs they could not.
2. The names weren't very descriptive of what they did. N.B. I'm open to shortening them to `groupSeqs` and `ungroupSeqs` if people would prefer.
3. They were blocking the deprecation of the inspect idiom in https://github.com/agda/agda-stdlib/pull/1630
=> Reimplement `split` and `flatten` in `Data.List.NonEmpty`

CHANGELOG.md, src/Data/Empty.agda, src/Data/Erased.agda, src/Data/Fin/Permutation.agda, src/Data/Irrelevant.agda, src/Data/Refinement.agda, src/Relation/Binary/PropositionalEquality.agda, src/Relation/Nullary/Decidable/Core.agda, src/Relation/Unary/Properties.agda, src/Text/Pretty/Core.agda
Shall I also rename `Data.Erased` to `Data.Irrelevant`? I remember people complaining that
it's not the correct name for it. `Data.Erased` should instead be:
```agda
record Erased (A : Set a) where
field @0 erased : A
```
=> [ fix #645 ] Irrelevant Data.Empty

CHANGELOG.md, src/Data/List/Countdown.agda, src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda, src/Data/List/Relation/Unary/Grouped/Properties.agda, src/Data/Product/Algebra.agda, src/Data/Sum/Algebra.agda, src/Data/Vec/Relation/Binary/Pointwise/Extensional.agda, src/Function/Bundles.agda, src/Function/Construct/Composition.agda, src/Function/Construct/Identity.agda, src/Function/Construct/Symmetry.agda, src/Function/Properties.agda, src/Function/Properties/Bijection.agda, src/Function/Properties/Inverse.agda, src/Function/Properties/RightInverse.agda, src/Function/Properties/Surjection.agda, src/Function/Related.agda, src/Function/Related/Propositional.agda, src/Function/Structures.agda, src/Relation/Nullary/Decidable.agda
Fixes https://github.com/agda/agda-stdlib/issues/1493. Changes the names of the fields in the records of the new function hierarchy from `f`, `g`, `cong₁`, `cong₂` to `to`, `from`, `to-cong`, `from-cong`.
Haven't yet implemented @andreasabel's request for the old `_<$>_` notation. I guess it could be added as an intern definition in `Func` ... Thoughts?
=> Change field names in new function hierarchy

CHANGELOG.md, src/Algebra/Morphism/Construct/Composition.agda, src/Algebra/Morphism/Construct/Identity.agda, src/Data/Bool/Properties.agda, src/Data/Fin/Induction.agda, src/Data/Vec/Relation/Unary/Linked/Properties.agda, src/Relation/Binary/Properties/StrictPartialOrder.agda
This PR adds proofs that strict partial orders defined over `Data.Bool` and `Data.Fin` are well-founded.
For `Data.Bool`, the proof is just about the "canonical" strict partial order (`_<_`); for `Data.Fin` there is a proof that _any_ strict partial order defined over `Fin` is well-founded (and Noetherian). That proof is more substantial and requires some additions to `Relation.Binary.Properties.StrictPartialOrder` (to show that the induced strict partial order of the inverse of a partial order is again a strict partial order).
=> Show that strict orders over some datatypes are well-founded.

CHANGELOG.md, src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda
This PR adds the following property to `Data.List.Relation.Binary.Permutation.Propositional.Properties`, which I had need of in some of my own developments. I asked about it [on Zulip](https://agda.zulipchat.com/#narrow/stream/259644-newcomers/topic/Lemmas.20for.20permutations.20on.20indices.20in.20the.20stdlib.3F/near/277941007), and @MatthewDaggitt indicated it might be welcome in the stdlib.
```agda
∈-resp-↭[sym-σ∘σ] : {xs ys : List A} {x : A} →
(σ : xs ↭ ys) →
(ix : x ∈ xs) →
∈-resp-↭ (trans σ (↭-sym σ)) ix ≡ ix
```
To be honest, I have no idea what this ought to be called, or where in the file it should live. I'm very happy to call it whatever you all think makes the most sense 😅 It was originally called `σ-inv` in my developments, but I suspect that's far too ambiguous for the …
=> Show that permuting a list index forwards then backwards is the identity

CHANGELOG.md, src/Algebra/Construct/Flip/Op.agda, src/Codata/Guarded/M.agda
Concretely: add proofs that the basic structure of magmas, semigroups and monoids are preserved if we switch the arguments of their binary operation.
=> Add some very simple properties about algebraic structures.

notes/installation-guide.md
I noticed that the installation instructions still refer to version 1.7, so I updated the versions mentioned to what I think the current ones are.
=> [ doc ] update installation instructions to 1.7.1

CHANGELOG.md, src/Algebra/Ordered.agda, src/Algebra/Ordered/Bundles.agda, src/Algebra/Ordered/Structures.agda, src/Codata/Guarded/M.agda, src/Relation/Binary/Consequences.agda, src/Relation/Binary/Definitions.agda, src/Relation/Binary/Lattice/Properties/BoundedJoinSemilattice.agda, src/Relation/Binary/Lattice/Properties/JoinSemilattice.agda, src/Relation/Binary/Lattice/Properties/MeetSemilattice.agda
This is a starting point for addressing #1694 and eventually #481 (since we need promonoids for grading).
I implemented this a while ago but never got around to submitting a PR so I refactored it to fit current stdlib conventions as best I could, but please let me know if anything looks wrong. The PR is also missing a CHANGELOG patch, but I need some advice on what to put where there. (Is there a CHANGELOG guide somewhere?)
=> [ fix #1694 ] Add ordered algebraic structures.

CHANGELOG.md, src/Algebra/Construct/Add/Identity.agda, src/Data/Maybe/Properties.agda
Adds Monoid for Pointed and also adds an idempotent proof for `<∣>`.
Note: I don't know the standard library very well (nor much module-fu) so please feel free to make suggestions for improvements.
=> Add Monoid for Add Point (#845)

CHANGELOG.md, src/Data/Container/Combinator.agda, src/Data/Container/Combinator/Properties.agda
Exposed container combinator conversion functions from `Data.Container.Combinator.Properties` separate from their correctness proofs in `Data.Container.Combinator`. Functions are named same as combinators prefixed with `to-` (to combinator) and `from-` (from combinator). Explicit arguments (besides the last one - value being converted) correspond to combinators' arguments.
=> Fix issue #1778

CHANGELOG.md, src/Algebra/Properties/Ring.agda, src/Algebra/Properties/Semigroup.agda
In this PR following proofs are added 
`-1*x≈x : ∀ x → - 1# * x ≈ - x`
`alternative : Alternative _∙_`
=> Add proofs in Algebra.Properties.<Ring/Semigroup> 

README/Data/List/Membership.agda
The documentation reads
> For example if we want to reason about membership for `List ℕ`
> then you would use the `DecSetoidMembership` as we use ...
but then the passage later says:
> the module `DecPropMembership` should be opened as follows:
I am guessing that these are meant to both be `DecPropMembership`, as equality of `ℕ` is propositional and decidable.
=> Fix doc typo in README.Data.List.Membership

CHANGELOG.md, src/Function/Base.agda
Add a non-dependent version of `flip` to `Function.Base`
=> Add `flip′` to `Function.Base`

CHANGELOG.md
This corrects an error in the `CHANGELOG` for PR#1735, which left a dangling reference to the old `Category.*` hierarchy.
=> Update CHANGELOG.md to finally complete PR#1735

agda-stdlib-utils.cabal
I tried to fix #1829. I did not find anything in the changelogs related to similar changes to support GHC versions after 8.2.2, so I did not include anything in the changelog.
=> Support for GHC 9.4

CHANGELOG.md, src/Algebra/Consequences/Setoid.agda, src/Algebra/Definitions.agda, src/Algebra/Morphism/MagmaMonomorphism.agda, src/Algebra/Properties/CancellativeCommutativeSemiring.agda, src/Algebra/Properties/Group.agda, src/Algebra/Properties/Quasigroup.agda, src/Data/Fin/Properties.agda, src/Data/Integer/Properties.agda, src/Data/List/Properties.agda, src/Data/Nat/Binary/Properties.agda, src/Data/Nat/Binary/Subtraction.agda, src/Data/Nat/DivMod.agda, src/Data/Nat/DivMod/Core.agda, src/Data/Nat/Divisibility.agda, src/Data/Nat/GCD/Lemmas.agda, src/Data/Nat/Properties.agda, src/Data/Sign/Properties.agda, src/Relation/Binary/HeterogeneousEquality/Quotients/Examples.agda
Part of the work done for Issue #1436 . Making the PR now to get a CI run.
=> Make Cancellative be more consistent in whole library

CHANGELOG.md, src/Data/Integer/Coprimality.agda, src/Data/Integer/DivMod.agda, src/Data/Integer/Divisibility.agda, src/Data/Integer/Divisibility/Signed.agda, src/Data/Integer/Properties.agda, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda
More specifically:
- Deprecate `pos-distrib-*` in favour of `pos-*`
- Rename `abs-*-commute` to `abs-*` (and deprecate)
- Rename `pos-+-commute` to `pos-+` (and deprecate)
and push through the library.
=> Closes #501

src/Data/Rational/Base.agda
These pattern matches were making it much harder to use to use, and removing them doesn't make the normalizations significantly worse
=> Dont' do the pattern match in ℚ._-_ and _÷_

CHANGELOG.md, src/Data/Nat/Base.agda, src/Data/Nat/Binary/Properties.agda, src/Data/Nat/Properties.agda
EDITED: Removed duplicate bundles, so should be fixed now. 
DONE: update CHANGELOG to record new bundles added
=> [fix] added raw bundles to `Data.Nat.Base`

standard-library.agda-lib
I [plan to](https://github.com/agda/agda/issues/5577) change Agda so that the `NoEquivWhenSplitting` warning is emitted when `--cubical-compatible` is used. To avoid getting lots of noise from the standard library I first want to turn off the warning for the standard library.
=> Turned off the NoEquivWhenSplitting warning

CHANGELOG.md, src/Data/List/Base.agda, src/Data/List/Properties.agda
Also adds raw bundles in Data.List.Base. Closes #1857
=> Length is a monoid homomorphism

CHANGELOG.md, src/Data/Integer/Base.agda, src/Data/Integer/Properties.agda
Suggest also fixing #1755 for `Data.Integer` as part of this PR.
=> [fix] issue #1844

CHANGELOG.md, src/Algebra/Construct/DirectProduct.agda, src/Algebra/Properties/KleeneAlgebra.agda
In this PR add direct product for  leftBolLoop, rightBolLoop, middleBolLoop and moufangLoop 
Prove  0⋆≈1 in Kleene Algebra
=> Add missing direct products and proof 0⋆≈1 in Kleene Algebra

src/Algebra/Properties/KleeneAlgebra.agda
In this PR prove
-  ∀ x → 1# + x ⋆ ≈ x ⋆
-  ∀ x → x ⋆ + x * x ⋆ ≈ x ⋆ 
-  ∀ x → x ⋆ + x ⋆ * x ≈ x ⋆ 
-  ∀ x → x + x ⋆ ≈ x ⋆ 
-  ∀ x → 1# + x + x ⋆ ≈ x ⋆
-  ∀ x → 0# + x + x ⋆ ≈ x ⋆
-  ∀ x → x ⋆ * x ⋆ ≈ x ⋆
-  ∀ x → 1# + x ⋆ * x ⋆ ≈ x ⋆
-  ∀ x → (x ⋆) ⋆ ≈ x ⋆
- 1# + 1# * 1# ≈ 1#
- 1# ⋆ ≈ 1#
- ∀ x y → x ≈  y → 1# + x * y ⋆ ≈ y ⋆
- ∀ x y → x ≈ y → x ⋆ ≈ y ⋆
- ∀ x a b → a * x ≈ x * b → x + a * (x * b ⋆) ≈ x * b ⋆
- ∀ x a b → a * x ≈ x * b → a ⋆ * x ≈ x * b ⋆
- ∀ x y → (x * y) ⋆ * x ≈ x * (y * x) ⋆
=> Add proofs to Kleene Algebra

CHANGELOG.md, src/Effect/Monad/Error/Transformer.agda, src/Effect/Monad/IO.agda, src/Effect/Monad/IO/Instances.agda, src/Effect/Monad/Reader/Instances.agda, src/Effect/Monad/Reader/Transformer.agda, src/Effect/Monad/State/Instances.agda, src/Effect/Monad/State/Transformer.agda, src/Effect/Monad/Writer.agda, src/Effect/Monad/Writer/Indexed.agda, src/Effect/Monad/Writer/Instances.agda, src/Effect/Monad/Writer/Transformer.agda, src/Effect/Monad/Writer/Transformer/Base.agda
I'm aware of `Data.Sum.Effectful.*` but it didn't help me much, I have no idea how to properly organize all the stuff about ExceptT reusing those modules.
I'm also asking for tips about improving the current code. First of all I couldn't come up with a really indexed construction for ExceptT because short-circuiting computations mess with the indices. Exceptions can be modeled with `Effect.Monad.Continuation` but is it a good definition for stdlib? Also there's no standard definition of categories in this library so indexed writer as in Bob Atkey's paper is out of reach.
=> [resolves #1333] writer transformer

CHANGELOG.md, src/Data/List/Relation/Unary/Sufficient.agda, src/Data/List/Sufficient.agda
A structurally inductive view of lists
=> 'Sufficient' lists

agda-stdlib-utils.cabal
@MatthewDaggitt, I couldn't test the `release-v1.7.2` branch with Agda 2.6.3 (see [error](https://github.com/agda/agda/actions/runs/3991533650/jobs/6846675894)). This PR fixes the problem.
=> Fixed "installation" with GHC 9.4.4.

CHANGELOG.md, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda
Fixes https://github.com/agda/agda-stdlib/issues/1437
=> fixes #1437, supersedes #1836

CHANGELOG/v1.7.2.md, src/Data/List/Membership/Setoid/Properties.agda
I think these must have been introduced in 1.7.2?
=> two whitespace violations

CHANGELOG.md, src/Algebra/Construct/Flip/Op.agda
incorporates all the previous review comments on #1900, now invalidated
DONE/TODO:
Since this PR is a 'clean' duplicate of the previous one, suggest that I try to complete it by finishing those intermediate structures before merging...
EDITED: all now done, barring the `Loop`s, which I propose not to do with this PR.
=> opposite of a `Ring` [clean version of pr #1900]

CHANGELOG.md, src/Algebra/Construct/Initial.agda, src/Algebra/Construct/Terminal.agda, src/Algebra/Construct/Zero.agda, src/Algebra/Module/Construct/Zero.agda, src/Data/Unit.agda, src/Data/Unit/Base.agda
Refactored `Algebra.Construct.Zero` into
and fixed up the public (re-)imports of the second into `Algebra.Construct.Zero` (for backwards compatibility), while deprecating the occurrences of the non-initial terminal algebras in favour of their counterparts in `Algebra.Construct.Terminal`. 
Also: amended `Algebra.Module.Construct.Zero` with commented-out hooks for the various `Raw` bundles associated with module-like algebras, pending the resolution of issue #1828 
One wrinkle: I wanted to abstract out all the common structure, so i did that in each module via an additional private module, that nevertheless is `open`ed into order to make the definitions (transparently) visible. But I may have got my `private`/`public` modifiers a bit mixed up. My concern is whether by making the internal …
=> initial+terminal algebras

CHANGELOG.md, src/Algebra/Consequences/Base.agda, src/Algebra/Consequences/Setoid.agda, src/Algebra/Definitions.agda, src/Data/Parity/Properties.agda, src/Data/Sign/Properties.agda
Reviewing my contribution of `Data.Parity` and friends, I found myself annoyed about repeated proofs of properties of the self-inverse functions `_⁻¹` and corresponding `opposite` on `Data.Sign`...
... and was surprised that being `SelfInverse` didn't seem to be in either the `Function` or `Algebra` hierarchies. 
Now, with this PR, I've chosen to put these things in the `Algebra` hierarchy, because that is where `Involutive` is defined, and self-inverse operations are involutive in the presence of reflexivity (one of the properties I needed/used/defined). 
But it seems that I could have put these definitions under `Function`, and certainly some of the `Consequences.Setoid` for self-inverse operations are really about their behaviour as `Function`s... so some advice on where these …
=> `SelfInverse` operations on `Algebra`s and their properties

CHANGELOG.md, src/Data/Vec/Relation/Binary/Lex/Strict.agda
This is a draft as `foo` and `bar` are not very good names for helpers functions.
It will also close issue #1738
=> Wellfounded proof for vec lexicographic order

CHANGELOG.md, src/Algebra/Properties/Monoid/Mult.agda, src/Algebra/Properties/Monoid/Sum.agda, src/Algebra/Properties/Semiring/Exp.agda, src/Algebra/Properties/Semiring/Mult.agda
... on the way to a full proof of the Binomial Theorem PR #1287 / #1928 
Plus a proof of the `sumₜ-init` lemma of the old PR, updated, renamed, and moved to `Algebra.Properties.Monoid.Sum`. 
Plus the proofs of the lemmas concerning the `n ×_` operation in `Algebra.Properties.Semiring.Mult`. 
Plus proof of some useful cosmetic congruence lemmas in `Algebra.Properties.Monoid.Mult` and `Algebra.Properties.Semiring.Exp`
=> binomial lemmas for *-commuting elements in a `Semiring`

src/Algebra/Consequences/Base.agda, src/Data/List/Properties.agda
cf. issue #1937
UPDATED: these are several of the more egregious 'gratuitous' uses of `with` in stdlib. I haven't (and won't, on this iteration) attempted to be systematic in replacing use of `with` on a Boolean argument in favour of `if_then_else_`, ~~nor those where they are used essentially as `let`-bindings,~~ but now I have where (at the bare minimum) an irrefutable pattern with a variable would be more (cognitively) efficient. 
The one 'noteworthy' instance here concerns `scanr`, where a reordering of the (nested) with patterns permitted elimination of the dead branch completely in favour of an irrefutable `_∷_` pattern. 
No `CHANGELOG`: only the proofs of existing lemmas have been modified.
=> removed redundant use of `with`

CITATION.cff, notes/release-guide.txt
Fixes #1952. Adds a `Cite this repository` button on the left hand side of the main Github page (as can be seen [here](https://github.com/agda/agda-stdlib/tree/citation)). Any comments by anyone?
=> Add citation file to repo

CHANGELOG.md, src/Data/Nat/Base.agda, src/Data/Nat/Properties.agda
Surprised that these properties are not already there; they *may* induce downstream a number of simplification to proofs of properties of monus. But not for this PR!
Separately, in view of the right->left direction of the adjunction: monus is defined as a *total* function `_-_` in `Agda.Builtin.Nat`, and reimported as `_∸_`... why don't we define an alternative function `n ∸ m` only on those arguments satisfying `m ≤ n` (by an easy recursion on the inductive definition of that relation; alternatively with an irrelevant instance argument of that type, and then simply definitionally equal to `Agda.Builtin.Nat._-_`) and then prove the two definitions extensionally equal? The fact that `_-_`  has certain properties provable outright, without further ordering assumptions here or there, seems …
=> Monus `_∸_` is right adjoint to addition `_+_` across usual `_≤_` preorder

CHANGELOG.md, src/Relation/Binary/Reasoning/Base/Apartness.agda
Added apartness reasoning, so it would be possible to do this:
```agda
_ : a # d
_ = begin-apartness
a ≈⟨ a≈b ⟩
b #⟨ b#c ⟩
c ≈⟨ c≈d ⟩
d ∎
```
=> Apartness reasoning

CHANGELOG.md, src/Algebra/Consequences/Propositional.agda, src/Algebra/Consequences/Setoid.agda, src/Algebra/Definitions.agda
```agda
_MiddleFourExchange_ : Op₂ A → Op₂ A → Set _
_*_ MiddleFourExchange _+_ =  ∀ w x y z → ((w + x) * (y + z)) ≈ ((w + y) * (x + z))
```
UPDATED: hmmm... naming conventions between `Algebra.Consequences.Setoid` and  `Algebra.Consequences.Propositional`: may wish to remove `cong+` prefixes? DONE.
=> middle four exchange law in a `Setoid`: definition and consequences

src/Algebra/Definitions.agda, src/Data/Nat/Show.agda
Closes #1993
See https://github.com/agda/agda-stdlib/issues/1993#issuecomment-1595352224 and https://github.com/agda/agda-stdlib/issues/1993#issuecomment-1595356776
- redundant deps : `Function.HalfAdjointEquivalence`, `Data.Product.Function.Dependent.Propositional`
- replaced `Data.String` import with `Data.String.Base` in `Data.Nat.Show`
=> Get rid of redundant deps in `System.Console.ANSI`

CHANGELOG.md
In CHANGELOG.md, changed the location of `take-[]` and `drop-[]` to their appropriate place in section _Other minor changes  /_  _Add new proofs in Data.List.Properties_
=> Update CHANGELOG.md move 2 functions to section Data.List.Properties

CHANGELOG.md, src/Algebra/Definitions.agda, src/Codata/Guarded/Stream.agda, src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda, src/Codata/Musical/Colist.agda, src/Codata/Musical/Colist/Bisimilarity.agda, src/Codata/Musical/Colist/Relation/Unary/All.agda, src/Codata/Musical/Conat.agda, src/Codata/Sized/Colist.agda, src/Codata/Sized/Colist/Bisimilarity.agda, src/Codata/Sized/Conat/Properties.agda, src/Codata/Sized/Covec.agda, src/Codata/Sized/Covec/Bisimilarity.agda, src/Codata/Sized/Cowriter.agda, src/Codata/Sized/Cowriter/Bisimilarity.agda, src/Codata/Sized/Stream.agda, src/Codata/Sized/Stream/Bisimilarity.agda, src/Data/Container/Core.agda, src/Data/Container/FreeMonad.agda, src/Data/Container/Indexed.agda, src/Data/Float/Base.agda, src/Data/Nat/Base.agda, src/Data/Nat/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda, src/Data/Tree/AVL/Map/Membership/Propositional.agda, src/Induction/WellFounded.agda
Related to #207 
More fixities 😅
=> Fixities for `Data` and `Codata`

CHANGELOG.md, src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda, src/Data/List/Relation/Unary/Sorted/TotalOrder/Properties.agda
Proofs that both lists involved in a merge are sublists of the result of the merge.
=> New property merge-is-superlist

CHANGELOG.md, src/Data/List/Properties.agda
Added new function take all to stdl Data.List.Properties and declare the change in CHANGELOG.md
=> added new function `take-all` to stdl 

.gitignore
The `_build` folder is not actually ignored by `git` right now (because of the initial `.`, I think), rather, most of the files inside the `_build` folder are ignored by the following patterns -
https://github.com/agda/agda-stdlib/blob/078d57f98d8c5934de7683e9c70b48b0c74cd678/.gitignore#L3-L6
These patterns are almost always sufficient (hence, the broken ignore was never detected) but cases like `graph.sh` generating a dot file in the `_build` directory breaks this and git ends up not ignoring the dot file.
=> gitignore `_build` correctly

CHANGELOG.md, src/Data/Star/Decoration.agda, src/Data/Star/Pointer.agda, src/Reflection/AnnotatedAST.agda
Base #2028 on `master` instead of on outdated `experimental`.
@plt-amy writes:
To fix https://github.com/agda/agda/issues/6654, we've decided that large indices will no longer be allowed by default. 
There is an infective flag `--large-indices` to bring them back, but none of the uses of large indices in the standard library were essential: to avoid complicated mutually-recursive PRs across repos, I adjusted the levels to check with `--no-large-indices` instead of adding the flag to the modules that used them.
=> Put indexed data types in the right universes

src/Data/Fin/Show.agda, src/Data/Integer.agda, src/System/Clock.agda, src/System/Console/ANSI.agda, src/Test/Golden.agda, src/Text/Printf.agda
Precision of the function used when importing `Data.Nat.Show`. 
Nevertheless, this doesn't help to lighten dependencies.
=> refine import of Data.Nat.Show

CHANGELOG.md, src/Data/Nat/Coprimality.agda, src/Data/Nat/DivMod.agda, src/Data/Nat/Divisibility.agda, src/Data/Nat/Divisibility/Core.agda, src/Data/Nat/GCD.agda, src/Data/Nat/Primality.agda
See the discussion on issue #1919. 
~~Two~~ Three parts to this:
Proposal: merge the low-hanging fruit one now, and keep this branch, and the above checkboxes, open for a subsequent independent PR. In the meantime, a chance to think about the pro/contra proposals regarding how to reconcile the various definitions...
=> Reconciling `Data.Nat.Divisibility.Core._∣_` and `Algebra.Definitions.RawMagma._∣_`

src/Data/List/Relation/Binary/Pointwise.agda, src/Data/List/Relation/Unary/All/Properties.agda, src/Data/Vec/Properties.agda, src/Data/Vec/Recursive/Properties.agda
Make a tiny bit of progress on #759 . Further progress is either blocked on #1895 or spins out of control and starts affecting a huge number of files.
=> move just a few more things over to new Function hierarchy.

src/Data/List/NonEmpty/Base.agda
=> removed redundant `import`s from `Data.Bool.Base` in `Data.List.NonEmpty.Base`

src/Data/String.agda
No `CHANGELOG` entry required.
=> tidying up `Data.String` 

CHANGELOG.md
Various typos having crept in... so we might eventually might want to develop a local dictionary for `emacs`, and make spell-checking a pre-commit hook?
=> spellchecked `CHANGELOG`

CHANGELOG.md, src/Data/Product/Relation/Binary/Lex/Strict.agda, src/Data/Vec/Relation/Binary/Lex/Strict.agda, src/Induction/WellFounded.agda
This addresses a minimal fragment of Johannes Waldmann's issue #2075 . There may be useful/desirable further consequences of this re-factoring, but they have not been pursued here. [UPDATED: but see also #2082 #2083 #2084]
This is NOT a breaking change, so there are no deprecation warnings, as changes are only to proofs added in the v2.0 development cycle...
No remaining knock-on consequences for `stdlib` dependent modules; external v2.0-compatible client code may break, but that will force the desired/desirable change to remove a redundant assumption at such call-sites.
=> addresses #2075: removes symmetry assumption from lexicographic well-foundedness

CHANGELOG.md, src/Data/List/Effectful.agda, src/Data/Maybe/Effectful.agda, src/Data/Sum/Effectful/Left.agda, src/Data/Sum/Effectful/Right.agda, src/Data/Vec.agda, src/Data/Vec/Base.agda, src/Data/Vec/Effectful.agda, src/Data/Vec/Effectful/Transformer.agda, src/Effect/Monad.agda, src/Effect/Monad/Identity.agda, src/Effect/Monad/Partiality.agda, src/Effect/Monad/Reader.agda, src/Effect/Monad/State.agda, src/Effect/Monad/Writer.agda
In the style of #2065, which this would close. 
UPDATED: @gallais 's suggestion leads to a better design, with a uniform naming scheme, and no pesky additional `record` definition...
[Moved questions about design to the issue as well]
=> Monadic join

CHANGELOG.md, src/Relation/Binary/Construct/Closure/Transitive.agda
This PR adds the following new proofs [UPDATED]:
which are instances of the corresponding proofs for ` module ∼⊆∼⁺ = Subrelation {_<₂_ = _∼⁺_} [_]`, together with
which then permits refactoring the old proof `Relation.Binary.Construct.Closure.Transitive.wellFounded`, to streamline it using `accessible` (and removing unnecessary detours via the shadow reimplementation `downwardsClosed` of `Induction.WellFounded.acc-inverse`).
~~Possible candidate deprecation opportunity: to deprecate the old name in favour of `wellFounded⁺`, for the sake of uniformity of the above naming scheme, which is, of course, up for discussion/debate (an alternative uniformity might be to call `accessible⁺` simply `accessible`, for example)~~
=> `WellFounded` proofs for transitive closure

CHANGELOG.md, src/Data/Fin/Base.agda, src/Data/Fin/Properties.agda, src/Data/Vec/Base.agda, src/Data/Vec/Properties.agda
~~Most of the way there, but I would like to introduce a definition of~~
Refactored to take advantage of:
```agda
truncate : (m≤n : m ≤ n) (xs : Vec A n) → Vec A m
```
and add: ~~a version of (itself refactored by this PR... ;-))~~
```agda
lookup-take-inject≤ : lookup (take m xs) i ≡ lookup xs (Fin.inject≤ i (m≤m+n m n))
```
~~which then makes use of it. But currently in `cast` hell... cf. #2057~~
UPDATED: Ugh! RTFL... The follies of ignorance... and there being rather scant properties of the function `truncate` already defined in `Data.Vec.Base`. 
Moving to draft status while I sort out the signal from the noise... NOW DONE. And with no plans to add to this PR further.
=> Refactor some lookup and truncation lemmas

notes/style-guide.md
=> Add style-guide note about local suffix

CHANGELOG.md, src/Data/List/Relation/Unary/All/Properties.agda, src/Data/List/Relation/Unary/Grouped/Properties.agda
Fixes https://github.com/agda/agda-stdlib/issues/1189
=> Weakened pre-conditions of grouped map lemmas

CHANGELOG.md, src/Relation/Binary/PropositionalEquality.agda
As per https://github.com/agda/agda-stdlib/issues/1580, we're not deprecating it for v2.0 as `with ... in` is not a perfect replacement.
=> Un-deprecate inspect idiom

CHANGELOG.md, src/Codata/Musical/Colist.agda, src/Data/Nat/InfinitelyOften.agda, src/Relation/Nullary/Decidable.agda, src/Relation/Nullary/Decidable/Core.agda, src/Relation/Nullary/Negation.agda, src/Relation/Nullary/Negation/Core.agda, src/Relation/Nullary/Reflects.agda, src/Relation/Nullary/Universe.agda
Last stage of https://github.com/agda/agda-stdlib/issues/1229.
Gone through and made the variable and type naming conventions consistent a) between `Relation.Nullary` modules and b) with the rest of the library.
Closes #1229
=> Modernise `Relation.Nullary` code

src/Algebra/Bundles.agda, src/Algebra/Structures.agda
What I don't understand is why/how this solution is to be preferred over others (such as?), or whether this may break anything subsequently... nor how this problem came about in the first place... nor what, if any, `CHANGELOG` entry might be suitable to account for the fix.
=> Adds `setoid` export to `Algebra.Bundles.SemiringWithoutOne` (possible solution to #1917)

CHANGELOG.md, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda, src/Data/Tree/AVL/Indexed/WithK.agda, src/Data/Tree/AVL/NonEmpty/Propositional.agda, src/Relation/Binary/Bundles.agda, src/Relation/Binary/Definitions.agda, src/Relation/Binary/Structures.agda
Tackles the last point of issue #453 : NB extends `StrictTotalOrder` to `DenseLinearOrder`, so lays the ground work for subsequent renaming/refactoring in the spirit of #453... and proposes it be part of `v2.0` because of that issue.
~~OUTSTANDING problem: trying to open the sub-bundle built out of the `IsStrictTotalOrder` field causes a name clash, for some reason. Don't really understand why, so `Algebra.*` experts please advise!~~ FIXED: thanks @MatthewDaggitt !
=> Ob #453: added `Dense` relations and `DenseLinearOrder`

CHANGELOG.md, README.agda, README/Data.agda, README/Data/Vec/Relation/Binary/Equality/Cast.agda, src/Data/Vec/Base.agda, src/Data/Vec/Properties.agda, src/Data/Vec/Relation/Binary/Equality/Cast.agda, src/Data/Vec/Relation/Binary/Reasoning/Propositional.agda
This pull request adds a set of combinators for equational reasoning about vector equality of the form `cast eq xs ≡ ys` and a few properties demonstrating its application. In particular, the new combinators deal with the threading of index equality proofs, greatly reducing the boilerplate that manipulates `cast`s to make writing equational proofs about vectors more or less feasible.
~~(Sorry for the piles of PR and the mess of the commit history. I promise this is the last one I have in hand. The first commit is the content of #2041 and #2045. After these two PRs get in, I'll rebase to remove the first commit. To see the code of this PR, please check <https://github.com/agda/agda-stdlib/commit/f8971193dce2620cdabf4c7f1d8319c2aa8fb0ed>.)~~
Index arithmetic is notably troublesome when it …
=> Add (propositional) equational reasoning combinators for vectors

src/Data/Integer/Base.agda, src/Data/Rational/Base.agda, src/Data/Rational/Test.agda, src/Data/Rational/Unnormalised/Base.agda
=> Re-export numeric subclass instances

CHANGELOG.md, src/Algebra/Properties/Monoid/Sum.agda, src/Algebra/Solver/CommutativeMonoid.agda, src/Algebra/Solver/IdempotentCommutativeMonoid.agda, src/Codata/Guarded/Stream/Properties.agda, src/Codata/Sized/Stream/Properties.agda, src/Data/Fin/Subset.agda, src/Data/String.agda, src/Data/Vec/Base.agda, src/Data/Vec/Bounded/Base.agda, src/Data/Vec/Effectful.agda, src/Data/Vec/Effectful/Transformer.agda, src/Data/Vec/Functional.agda, src/Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda, src/Data/Vec/Functional/Relation/Unary/All/Properties.agda, src/Data/Vec/Properties.agda, src/Data/Vec/Recursive.agda, src/Data/Vec/Relation/Binary/Equality/Setoid.agda
Fixes #2097. Lots of implicits being passed explicitly removed, so it looks like it was the right idea :tada:
=> Make size parameter on 'replicate' explicit

README.agda, README/Inspect.agda
See #2127.
Current status: fixes the actual `import` bug.
PUSHED commits: fixing the undeprecation of `README.Inspect`, and restoring it to `README`.
=> [fixes #2127] Fixes #1930 `import` bug

CHANGELOG.md, src/Data/Bool/Properties.agda, src/Data/Char/Properties.agda, src/Data/Fin/Properties.agda, src/Data/Integer/Properties.agda, src/Data/List/Relation/Binary/Lex/Strict.agda, src/Data/Nat/Binary/Properties.agda, src/Data/Nat/Properties.agda, src/Data/Product/Relation/Binary/Lex/Strict.agda, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda, src/Data/Sum/Relation/Binary/LeftOrder.agda, src/Data/Vec/Relation/Binary/Lex/Strict.agda, src/Induction/WellFounded.agda, src/Relation/Binary.agda, src/Relation/Binary/Bundles.agda, src/Relation/Binary/Construct/Add/Infimum/Strict.agda, src/Relation/Binary/Construct/Add/Supremum/Strict.agda, src/Relation/Binary/Construct/Flip/EqAndOrd.agda, src/Relation/Binary/Construct/Flip/Ord.agda, src/Relation/Binary/Construct/NonStrictToStrict.agda, src/Relation/Binary/Construct/On.agda, src/Relation/Binary/Morphism/OrderMonomorphism.agda, src/Relation/Binary/Structures.agda, src/Relation/Binary/Structures/Biased.agda
Fixes https://github.com/agda/agda-stdlib/issues/2135 by defining `IsStrictTotalOrder` in terms of `IsStrictPartialOrder`
=> Change definition of `IsStrictTotalOrder`

CHANGELOG.md, src/Function/Bundles.agda
Fixes https://github.com/agda/agda-stdlib/issues/1736
=> Add `_⟨$⟩_` operator for Function bundle

travis/landing.sh
With the previous script we were sorting entries of the form html/vX.Y.Z/index.html but the order is such that vX.Y/ < vX.Y.Z/ and so we were ending up with v1.7 coming after v1.7.3.
This fixes that by using sed to get rid of the html/ prefix and the /index.html suffix before the sorting phase.
=> [ admin ] fix sorting logic

src/Codata/Musical/Colist.agda, src/Data/Integer/Divisibility/Signed.agda, src/Data/List/Relation/Binary/BagAndSetEquality.agda, src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda, src/Data/Nat/Divisibility.agda, src/Data/Rational/Properties.agda, src/Data/Rational/Unnormalised/Properties.agda, src/Function/Bundles.agda, src/Relation/Binary/Construct/Closure/ReflexiveTransitive/Properties.agda, src/Relation/Binary/Reasoning/Base/Double.agda, src/Relation/Binary/Reasoning/Syntax.agda
=> Rename preorder ~ relation reasoning combinators

CHANGELOG.md, src/Codata/Guarded/Stream/Properties.agda, src/Codata/Musical/Colist/Infinite-merge.agda, src/Codata/Sized/Stream/Properties.agda, src/Data/Fin/Relation/Unary/Top.agda, src/Data/Fin/Substitution/Lemmas.agda, src/Data/List/Countdown.agda, src/Data/List/Relation/Binary/Sublist/Propositional/Example/UniqueBoundVariables.agda, src/Data/List/Relation/Ternary/Interleaving/Properties.agda, src/Data/List/Relation/Unary/Any/Properties.agda, src/Data/Nat/Coprimality.agda, src/Data/Nat/GCD.agda, src/Data/Nat/LCM.agda, src/Data/String/Unsafe.agda, src/Data/Vec/Bounded/Base.agda, src/Data/Vec/Recursive/Properties.agda, src/Data/Vec/Relation/Binary/Equality/Cast.agda, src/Effect/Applicative/Indexed.agda, src/Function/Related/TypeIsomorphisms.agda, src/Relation/Binary/PropositionalEquality/Core.agda, src/Relation/Binary/PropositionalEquality/Properties.agda, src/Relation/Binary/Reasoning/Syntax.agda
This follows up #2152 and implements `≡-Reasoning` using the new reasoning combinators. In order to do this it was necessary to move it from `Core` to `Properties` as the `Syntax` module imports `Core`.
This is a reasonable change to make as:
1. all other `Reasoning` modules live in `Properties` not `Base/Core`
2. users are told not to import `Core` modules anyway (have added the `breaking` tag anyway)
=> Move ≡-Reasoning from Core to Properties and implement using syntax

CHANGELOG.md, src/Data/Product/Function/Dependent/Setoid.agda, src/Function/Bijection.agda, src/Function/Construct/Constant.agda, src/Function/Equality.agda, src/Function/Equivalence.agda, src/Function/Injection.agda, src/Function/Inverse.agda, src/Function/LeftInverse.agda, src/Function/Properties/Equivalence.agda, src/Function/Properties/Injection.agda, src/Function/Properties/Surjection.agda, src/Function/Surjection.agda
Finally closes https://github.com/agda/agda-stdlib/issues/759 by adding individual deprecation warnings to all the components in the old function hierarchy.
The only ones I haven't done are covered by open issues https://github.com/agda/agda-stdlib/issues/1996 and https://github.com/agda/agda-stdlib/issues/1980
=> Add consistent deprecation warnings to old function hierarchy

CHANGELOG.md, src/Effect/Applicative.agda, src/IO/Primitive.agda
Fixes https://github.com/agda/agda-stdlib/issues/2124. 
@gallais is there anywhere else you're aware of it needs to go?
=> Restore 'return' as an alias for 'pure'

src/Data/List/Base.agda, src/Data/List/Relation/Unary/Unique/DecSetoid/Properties.agda, src/Data/String/Base.agda, src/Data/Vec/Base.agda
Fixes #2172 but as discussed in issue, unfortunately introduces an undesirable new dependency from a `Base` file on a `Properties` file.
Maybe the answer is to move `T?` to `Data.Nullary.Decidable.Core`?
=> Make decidable versions of sublist functions the default

CHANGELOG.md, src/Data/Fin/Properties.agda, src/Data/Product/Function/Dependent/Setoid.agda, src/Function/Consequences.agda, src/Function/Consequences/Propositional.agda, src/Function/Consequences/Setoid.agda, src/Function/Properties/Inverse.agda, src/Function/Structures.agda
Makes transforming between different function properties far far easier, when both the domain and codomain relations are setoids.
This in preparation for the change I discussed in the meeting of switching back to the old definitions in the `Function` structures and bundles.
=> Add `Function.Consequences.Setoid`

CHANGELOG.md, src/Relation/Binary/PropositionalEquality.agda
Fixes the first item in issue #2198 .
I'd be happy/happier to merge this without further ado, but I'm also conscious that it exposed/exposes the redundancy in the `import`s at the head of the module... so I'm electing to tidy that up as well.
=> Deprecating `Relation.Binary.PropositionalEquality.isPropositional`

CHANGELOG.md, src/Algebra/Consequences/Base.agda, src/Algebra/Consequences/Propositional.agda, src/Algebra/Consequences/Setoid.agda, src/Algebra/Lattice/Properties/BooleanAlgebra.agda, src/Algebra/Lattice/Structures/Biased.agda, src/Algebra/Structures.agda, src/Algebra/Structures/Biased.agda, src/Data/Integer/Properties.agda, src/Data/Nat/Binary/Properties.agda, src/Data/Nat/Binary/Subtraction.agda, src/Data/Nat/Properties.agda, src/Data/Parity/Properties.agda
Pure bureaucracy!
Only outstanding issue seems to be whether I have, in fact, got the `CHANGELOG` and deprecation warnings correct.
=> [fixes #2168] Change names in `Algebra.Consequences.*` to reflect `style-guide` conventions

CHANGELOG.md, src/Algebra/Structures/Biased.agda, src/Data/Product/Function/Dependent/Propositional.agda, src/Function.agda, src/Function/Construct/Symmetry.agda, src/Function/Structures.agda, src/Function/Structures/Biased.agda, src/Relation/Binary/PropositionalEquality.agda
Eases the conversion to the new strict versions. Also fixed a naming bug introduced in v2.0.
=> Add biased versions of Function structures

src/Algebra/Lattice/Properties/BooleanAlgebra/Expression.agda, src/Relation/Binary/Construct/Closure/ReflexiveTransitive.agda, src/Text/Pretty.agda
Only noteworthy items:
* finally finishes off (references to) the deprecated `Category.*` hierarchy (leftover in comments);
* exercises the discipline of #2201 in place of *ad hoc* `*Cat` naming scheme
* tagged as v2.0, for completion/completist(s)'s sake...
No `CHANGELOG`.
=> remove final references to `Category.*`

CHANGELOG.md, src/Algebra/Definitions/RawMagma.agda, src/Algebra/Properties/Magma/Divisibility.agda, src/Data/Nat/Base.agda
Fixes #2216. I've left the record names the same, so if we ever unify with the definition in `Data.Nat.Divisibility.Core` the change is less breaking.
=> Fix #2216 by making divisibility definitions records

.github/workflows/ci-ubuntu.yml, GenerateEverything.hs, src/Algebra/Operations/Semiring.agda, src/Algebra/Properties/BooleanAlgebra.agda, src/Algebra/Properties/DistributiveLattice.agda, src/Data/Fin/Substitution/Example.agda
I realise these modules are deprecated but it probably best that they still build. After these changes I can build an `Everything.agda` built with `runhaskell GenerateEverything.hs --include-deprecated` .
Not sure if I fixed them in the "correct" way.
=> Fix deprecated modules

.github/workflows/ci-ubuntu.yml, CHANGELOG.md, CITATION.cff, LICENCE, doc/installation-guide.md
Would appreciate someone giving a quick review so we can get this merged in and I can make the release tonight!
=> Final admin changes for v2.0 release

CHANGELOG.md, src/Data/Nat/Divisibility.agda, src/Data/Nat/Primality.agda
NB:
* no idea how this crept in: careless copy-paste and subsequent propagation of a name from somewhere during the final refactoring of #2182 ?
* `style-guide` already has an entry for the relevant symbol.
=> fixes issue #2237

src/Data/Vec/Bounded/Base.agda
Following up on #2216 / #2217 (and #2250 ) with a 'pure' refactoring PR (so: no `CHANGELOG` entry required at this stage) which localises all uses of the retained-for-backwards-compatibility `pattern` synonym `less-than-or-equal` to `Data.Nat.Base`, `Data.Nat.Properties`, `Data.Nat.Properties/WithK`.
Outstanding issues (maybe):
* deprecation of the pattern synonym (in `Data.Nat`? or elsewhere?), which would require a `CHANGELOG` entry;
* the fix-up of the various `Vec` lengths in `padRight`, `padBoth` etc. at present use `rewrite`, but it might be cleaner to use `Vec.cast` with the appropriate equality (shoutout to @JacquesCarette for this);
* the ubiquity (now) of the 'pattern' of definition
```agda
f : ... (as : Vec≤ A n) ... 
f ... as@record { length = m ; vec = vs ; bound = m≤n } ... …
```
=> Remove all external use of `less-than-or-equal` beyond `Data.Nat.*`

CHANGELOG.md, src/Algebra/Module/Morphism/Construct/Composition.agda, src/Algebra/Module/Morphism/Construct/Identity.agda, src/Algebra/Module/Morphism/ModuleHomomorphism.agda, src/Algebra/Module/Morphism/Structures.agda
Follow-on from #2263. These changes are breaking, although I think they're still important and worth it.
=> Parametrize module morphisms by raw bundles

CHANGELOG.md, src/Relation/Nullary/Decidable.agda
fixes #846 . Prompt to identify any other 'missing' such properties.
=> add lemma(s) about `Relation.Nullary.Decidable.Core.isYes`

doc/style-guide.md
Currently this is 'stub' content, allowing #803 to be closed. Added:
* section documenting pragmatics/programming idioms, incl.: para. on proofs of decidability, #803 ; para. on `with`, #1937 / #2123 ; 
* para. on qualified import names for modules; #2201
=> additions to `style-guide`

CHANGELOG.md, src/Algebra/Bundles.agda
What else is missing from your shopping list, @Taneb ?
And: should the additional export behaviour be implemented in `Algebra.Bundles`, `Algebra.Bundles.Raw` (and then re-exported in the corresponding place(s) in `Algebra.Bundles`), or both? (This last seems like a bad idea from a DRY point-of-view)
=> (Partial) fix for issue #1688

CHANGELOG.md, src/Relation/Binary/Definitions.agda, src/Relation/Nullary.agda, src/Relation/Unary.agda
Partial fix for #2091 
Outstanding:
* ~~`Maybe` exported publicly from `Relation.Nullary` as `WeaklyDecidable`; consider renaming the constructors also?~~
* what else?
=> Systematise relational definitions at all arities

CHANGELOG.md, src/Algebra/Properties/Monoid/Mult.agda, src/Algebra/Properties/Semiring/Binomial.agda, src/Algebra/Properties/Semiring/Mult.agda
This is a largely cosmetic PR, to lay the groundwork for more extensive additions related to #1363 / #2264 .
It adds:
* 'homomorphism' properties for  `0`/`0#` (I'd dithered over this one, because it holds by definition, but I've included it for the sake of uniformity, and fixed the resulting name-clash... ;-)) and `1`/`1#` to `Algebra.Properties.Monoid.Mult`;
* of which the property for `1` was previously, erroneously, placed in `Algebra.Properties.Semiring.Mult` as part of #1928 , so a deprecation is also issued for that;
* repairs the single use of that lemma in  `Algebra.Properties.Semiring.Binomial` in favour of the simpler `Monoid` property;
* the companion property `×-homo-0#` for `0` which *does* require `Semiring` structure (specifically: the `*-zero` property, …
=> lemmas about semiring structure induced by `_× x`

doc/README.agda, doc/README/Data/Fin/Substitution/UntypedLambda.agda
Fix import in `README.Data.Fin.Substitution.UntypedLambda`, add this module to `doc/README.agda`.
Closes #2278.
=> Fix import in `README.Data.Fin.Substitution.UntypedLambda`

src/Codata/Guarded/Stream/Relation/Binary/Pointwise.agda, src/Codata/Sized/Colist/Properties.agda, src/Data/Char/Properties.agda, src/Data/Digit/Properties.agda, src/Data/Fin/Induction.agda, src/Data/Fin/Substitution/Lemmas.agda, src/Data/Integer/Properties.agda, src/Data/List/Countdown.agda, src/Data/List/Fresh/Membership/Setoid/Properties.agda, src/Data/List/Membership/Propositional/Properties.agda, src/Data/List/Membership/Propositional/Properties/WithK.agda, src/Data/List/Membership/Setoid/Properties.agda, src/Data/List/Relation/Binary/BagAndSetEquality.agda, src/Data/List/Relation/Binary/Infix/Heterogeneous/Properties.agda, src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda, src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda, src/Data/List/Relation/Binary/Suffix/Heterogeneous/Properties.agda, src/Data/List/Relation/Ternary/Appending/Propositional.agda, src/Data/List/Relation/Ternary/Appending/Propositional/Properties.agda, src/Data/String/Properties.agda, src/Data/Tree/Rose/Properties.agda, src/Data/Vec/Properties.agda, src/Data/Vec/Relation/Unary/All/Properties.agda, src/Data/Vec/Relation/Unary/AllPairs/Properties.agda, src/Data/Vec/Relation/Unary/Linked/Properties.agda, src/Data/Vec/Relation/Unary/Unique/Setoid/Properties.agda, src/System/Clock.agda, src/Text/Pretty/Core.agda, src/Text/Regex/String.agda, src/Text/Tabular/List.agda
Outstanding issues:
* disambiguation problem wrt `Permutation` in `Data.List.Relation.Binary.Subset.Setoid.Properties`;
* ditto. in `Data.Tree.AVL.Map.Membership.Propositional.Properties` wrt `IAny`
* use of `Pw` (etc.) vs. `Pointwise` for the qualified name of `Pointwise` modules? 
* ... ditto: `Membership`, `Subset`, `Sublist`, `Setoid`, `All`, `Any`, ...under `Data.List.Relation.*`
* not being able to use the datatype root name in some cases, esp. `List` for those above
Intermittent fixing of `U` to `Unary`, `B` to `Binary` ahead of tackling that task more systematically downstream
=> Qualified import of `Properties` modules fixing #2280

src/Data/Bool/Solver.agda, src/Data/Integer/Solver.agda, src/Data/Integer/Tactic/RingSolver.agda, src/Data/Nat/Solver.agda
Anent @gallais 's #1380 : a purely manual fix, so doesn't close the issue ... 
... because, as with the recent #2278 / #2279 we still need to observe a 'better' discipline about (checking the) linking to `README`s on the one hand, and ensuring that new `README.*` are in fact imported by `doc/README`.
Nevertheless, the dead links seem (at the time of writing) only to arise from the historical move from the 'simple' `*.Solver.solve`s to the more sophisticated `*.Tactic.RingSolver.solve-∀`, so this is a 'stable' fix:
* `Data/Bool/Solver.agda`:-- See README.~~Nat~~.Data.Nat for examples of how to use similar solvers
* `Data/Integer/Solver.agda`:-- See README.~~Integer~~.Data.Integer ...
* `Data/Integer/Tactic/RingSolver.agda`:-- See README.~~Integer~~Tactic.Ringsolver ...
* …
=> `README.Data.*` manual fix for #1380

doc/README/Data/Tree/Binary.agda
Corrects another orphan module under `doc/README`: use of `--sized-types` is no longer `--safe` ... cf. #2278 #1380
=> Fix `sized-types` error in `README.Data.Tree.Binary`

src/Codata/Sized/Delay.agda, src/Data/Container/Combinator.agda, src/Data/Container/Combinator/Properties.agda
Follows the proposal in the issue: `as Sum`, but the 'datatype name as root module name' heuristic suggests `⊎` instead, cf. my comment on #2280 / #2284 concerning `Product`...
Also: rectifies `Data.Container.Combinator.Properties` to 'standardise' on `as S`, `as P` for disambiguation wrt `Sum` and `Product`, and also`PropositionalEquality as ≡` #2282
=> Qualified import of `Data.Sum.Base` fixing #2280

CHANGELOG.md, src/Relation/Binary/Construct/Composition.agda, src/Relation/Binary/Properties/Setoid.agda
```quote
I would be _strongly_ tempted to refactor these proofs, either in this PR, or subsequently, in terms of properties of general binary relations:
* any reflexive relation `R` (of the correct type) satisfies `S ⇒ R ; S` and `T ⇒ T ; R`;
* any transitive relation `T` satisfies `T ; T ⇒ T`;
* `Setoid`/`IsEquivalence`, `Preorder`/`IsPreorder` satisfy reflexivity and transitivity: QED
Specialising to `Setoid` here seems ... a missed opportunity.
```
_Originally posted by @jamesmckinna in https://github.com/agda/agda-stdlib/pull/2023#discussion_r1501798611_
For the cost of only one more lemma in `Relation.Binary.Construct.Composition`, the second of the above ...
Outstanding issue: what's the Agda input sequence for `_;_`: the character "\;" (backslash-;) seems not quite right? …
=> Refactor proofs from #2023

CHANGELOG.md, doc/README/Data/Integer.agda, src/Data/Integer/Divisibility.agda, src/Data/Integer/Divisibility/Signed.agda, src/Data/Integer/GCD.agda, src/Data/Integer/LCM.agda
This PR (re-)visits the corner case of #2280 , to hopefully avoid the wrinkles:
* makes `Data.Nat.Divisibility` a 'standard' qualified import;
* refactors the appeals to its contents via the qualified name;
* avoids the previous `public` re-export of the constructor `divides` in favour of a pattern synonym;
* knock-on changes to `Data.Integer.*` to reflect the refactoring.
The pattern synonym is perhaps the only awkward bit wrt any potential clients (`stdlib` seems OK), so comments welcome. 
UPDATED: added the `breaking` label to reflect the discussion below.
=> Qualified imports in `Data.Integer.Divisibility` fixing #2280

doc/style-guide.md
It should be documented in the style guide.
_Originally posted by @JacquesCarette in https://github.com/agda/agda-stdlib/issues/2282#issuecomment-1934868139_
=> Style guide: guideline for `-Reasoning` module imports cf #2282

doc/style-guide.md
This is a sequel to #2294 mopping up the `style-guide` recommendation.
=> Style guide: avoid `renaming` on qualified import cf. #2294

src/Data/Product/Effectful/Left.agda, src/Data/Product/Effectful/Right.agda, src/Effect/Applicative.agda, src/Effect/Monad.agda, src/Reflection/AST/DeBruijn.agda
A simple change. I've run `make test` and everything type checks.
=> make `mkRawMonad` and `mkRawApplicative` universe-polymorphic

doc/README/Data/Container/FreeMonad.agda, doc/README/Data/List/Membership.agda, doc/README/Data/List/Relation/Binary/Equality.agda, doc/README/Data/Tree/AVL.agda, doc/README/Data/Trie/NonDependent.agda, doc/README/Data/Vec/Relation/Binary/Equality/Cast.agda, doc/README/Function/Reasoning.agda, doc/README/Tactic/Cong.agda, doc/README/Tactic/MonoidSolver.agda
Brings the qualified imports into line with the emerging style-guidelines in line with #2280 .
Exceptions:
* `README.Data.List.Relation.Binary.Equality` (which leaves holes open, moreover!?)
* `README.Data.List.Membership` (not clear how best to rename the qualified import names)
* `README.Text.Tabular`
=> Tidy up `README` imports #2280

CHANGELOG.md, src/Algebra/Properties/AbelianGroup.agda, src/Algebra/Properties/Group.agda, src/Algebra/Properties/Loop.agda, src/Algebra/Properties/Quasigroup.agda, src/Algebra/Structures.agda
Tackles second item of #2247 .
Issues:
* deprecation of `_-_` in `IsGroup`?
* adding operations to `Algebra.Bundles.Raw.RawGroup`?
Knock-on changes (potentially):
* Instances of `_-_` defined in, and hence would clash with any opening of the `RawGroup`|`IsGroup` instance:
* Instances of `_-_` not defined in, but would be by opening the `RawGroup`|`IsGroup` instance:
=> Add new operations (cf. `RawQuasigroup`) to `IsGroup`

src/Data/List/Relation/Binary/BagAndSetEquality.agda
Cherry-picked from #2317 :
* (cosmetic) rewrote the proof of `lemma` at the end to make it more readable (to me... ;-));
* (better abstraction) rewrote the proof of `↭⇒∼bag` to exploit existing lemmas in `Data.List.Relation.Binary.Permutation.Propositional.Properties`;
* (cosmetic) use of irrefutable `with` in `∼bag⇒↭`
No `CHANGELOG` required.
=> Refactor `Data.List.Relation.Binary.BagAndSetEquality`

CHANGELOG.md, src/Data/Vec/Functional/Relation/Binary/Permutation.agda, src/Data/Vec/Functional/Relation/Binary/Permutation/Properties.agda
This is a largely cosmetic coda to #2066 : 
* Completes the `Properties` by adding structure and bundle (NB transitivity has horrible indexed inference mess)
* Sorts out alignment, standardises `variable` names
* Cleans up `CHANGELOG`
Apologies to all for not catching this earlier in review/comments on the earlier PR.
=> Tidy up functional vector permutation #2066

CHANGELOG.md, doc/README/Tactic/Cong.agda, src/Tactic/Cong.agda
Hello there.
It's known that the  `cong!` tactic's anti-unification is a tad too granular for some use cases. In the following, for example, it descends past the application of `_+_` in `b + c` and `c + b`, so that the following definition doesn't type-check.
```
proof : ∀ a b c → a + (b + c) ≡ a + (c + b)
proof a b c =
a + (b + c) ≡⟨ cong! (+-comm b c) ⟩
a + (c + b) ∎
```
Note, however, that the following does type-check. (Note the added application of `id` to `b + c`.)
```
proof : ∀ a b c → a + (b + c) ≡ a + (c + b)
proof a b c =
a + id (b + c) ≡⟨ cong! (+-comm b c) ⟩
a + (c + b)    ∎
```
It works, because the `cong!` tactic inhibits normalisation, the application of `id` isn't reduced, anti-unification finds that `id (b + c)` is different from `(c + b)` (because `id` is different from …
=> A tweak for the cong! tactic

src/Data/List/Membership/Propositional/Properties/Core.agda, src/Data/List/Relation/Unary/Any/Properties.agda
This is a very small PR, which does ~~two~~ three things:
* simplifies the proof `reverseAcc⁻`, removing a couple of detours, and crucially
* removes the dependency on the single import (of `ʳ++-defn`) from `Data.List.Properties`
* cleans up a module long name in the opening comment
The second point is much more interesting than the first (but that's a cosmetic/aesthetic improvement, notwithstanding), because it may open the way to further simplification of the dependency graph under `Data.List`. 
No `CHANGELOG`.
=> Simplify `Data.List.Relation.Unary.Any.Properties`: remove dependency on `List.Properties`

CHANGELOG.md, src/Data/Integer/Divisibility.agda, src/Data/Integer/Divisibility/Signed.agda, src/Data/Integer/Properties.agda
This is a sequel to #2294 mopping up the refactoring of `Data.Integer.Divisibility.Signed` suggested there.
NB. 
* `Data.Integer.Divisibility` is still a 'minimal' collection of properties based on the underlying `Data.Nat.Divisibility`, so this latter module has still to be imported in `Data.Integer.Divisibility.Signed`, rather than providing a 'clean' API via `Data.Integer.Divisibility`...
* Additions to `Data.Integer.Properties` also expose at least one deprecation/refactoring opportunity, between `abs-*` and `∣i*j∣≡∣i∣*∣j∣`, preferring the former over the latter, but not as yet doing the deprecation, in the interests of minimal impact (separate PR?)...
* Possibility to refactor `◃-distrib-*`?
* Removes one use of `renaming` on `import`, but `style-guide` recommendation in separate PR …
=> Refactor `Data.Integer.Divisibility.Signed`

CHANGELOG.md, CHANGELOG/v2.0.md, HACKING.md, fix-whitespace.yaml, src/Algebra/Module/Bundles/Raw.agda, src/Algebra/Morphism/Construct/Initial.agda, src/Data/List/Relation/Ternary/Appending/Setoid/Properties.agda, src/Data/Nat/Primality/Factorisation.agda
As prompted by @andreasabel. There's no reason for the CHANGELOG not to be under whitespace fixes.
=> Include CHANGELOG in fix-whitespace and whitespace fixes

standard-library.agda-lib
I accidentially introduce a modification in `standard-library.agda-lib` which I revert here.
=> Fix standard-library.agda-lib

src/Relation/Nullary/Decidable/Core.agda
- Use `Data.Unit.Polymorphic` instead of an explicit `Lift` in a couple of places
- Use `contradiction` instead of explicit `⊥-elim` in one place (other can't because of irrelevance)
- Tighten imports a bit
No need for CHANGELOG as these are all internal changes with no external effects.
=> [refactor] Relation.Nulllary.Decidable.Core

src/Algebra/Properties/Monoid/Sum.agda, src/Data/List/Effectful.agda, src/Data/List/Membership/Propositional/Properties.agda, src/Data/List/Relation/Unary/All/Properties.agda, src/Data/Product/Properties.agda, src/Relation/Binary/PropositionalEquality.agda, src/Relation/Binary/PropositionalEquality/Core.agda
Closes #2331.
Also makes a few changes of imports that are related. Many of the places which look like this improvement might also help use other things from `Relation.Binary.PropositionalEquality` that should *not* be moved to `.Core`. (But it might make sense to split them off into their own lighter weight module.)
=> Move pointwise equality to `.Core` module

src/Algebra/Definitions/RawMagma.agda, src/Algebra/Structures.agda, src/Data/List/Relation/Unary/AllPairs.agda, src/Data/Maybe/Base.agda, src/Data/Product/Properties.agda, src/Function/Indexed/Relation/Binary/Equality.agda, src/Relation/Binary/Bundles.agda, src/Relation/Binary/PropositionalEquality/Algebra.agda, src/Relation/Binary/Reasoning/Setoid.agda, src/Relation/Binary/Reasoning/Syntax.agda
I started from `Data.List.Fresh` and looked at the dependency graph (thanks for that nice script @gallais !) and tightened up  imports to make the dependency graph seem more 'natural' from a conceptual dependency point of view. While I was looking at various files, I also added some explicit `using` when it seemed to make sense.
This should be a pure clean-up with no visible consequences externally, other than making the dependency graph less convoluted. (So if anything else has slipped-in by mistake, it should be taken out!)
=> Tighten imports

doc/README/Effect/Monad/Partiality.agda, src/Algebra/Module/Construct/Idealization.agda, src/Algebra/Properties/CommutativeMonoid.agda, src/Data/Container/Core.agda, src/Data/Container/Indexed.agda, src/Data/Container/Indexed/Relation/Binary/Pointwise.agda, src/Data/List/Properties.agda, src/Data/List/Relation/Ternary/Appending/Setoid/Properties.agda, src/Data/List/Relation/Unary/First/Properties.agda, src/Data/Nat/Primality/Factorisation.agda, src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda, src/Data/Rational/Unnormalised/Base.agda, src/Data/Sum/Algebra.agda, src/Data/Sum/Function/Propositional.agda, src/Data/Unit/Polymorphic/Properties.agda, src/Effect/Monad/Partiality.agda, src/Function/Properties/Inverse/HalfAdjointEquivalence.agda, src/Function/Related/TypeIsomorphisms.agda, src/Relation/Binary/Reasoning/Base/Apartness.agda, src/Relation/Binary/Reasoning/Base/Double.agda, src/Relation/Binary/Reasoning/Base/Partial.agda, src/Relation/Binary/Reasoning/Base/Triple.agda
A few files used very basic bits of `Data.Product` and `Function` that could instead use `.Base`. 
While in those files, fix up other things. Some files couldn't go to `.Base` after all, but other things could be fixed, so they were.
In one case, `Effect.Monad.Partiality` was using all of `Data.Nat` for a private example -- I moved that to `README.Effect.Monad.Partiality` instead.
=> Tighten imports some more

CHANGELOG.md, src/Algebra/Structures.agda
=> Add a consequence of definition straight to IsCancellativeCommutativeSemiring

CHANGELOG.md, GenerateEverything.hs, src/Data/Float/Base.agda, src/Data/List/Show.agda, src/Data/String/Base.agda, src/Data/Vec/Bounded/Show.agda, src/Data/Vec/Show.agda, src/Data/Word/Base.agda, src/System/Random.agda, src/System/Random/Primitive.agda, tests/runtests.agda, tests/system/random/.gitignore, tests/system/random/Main.agda, tests/system/random/random.agda-lib, tests/system/random/run
Following a discussion on zulip
=> [ new ] System.Random bindings

CHANGELOG.md, doc/README/Tactic/Cong.agda, src/Reflection/TCM/Utilities.agda, src/Tactic/Cong.agda
Hello there.
I do a lot of equational reasoning with `_/_` and `_%_`. This means `NonZero` instance arguments on both sides of my equalities. Sometimes, when `cong!` runs, the metas for the instance arguments are already resolved. But sometimes they aren't. Or one of them is, but the other isn't. It depends on how things fall into place during type-checking.
When there are such unresolved metas, `cong!` fails. For example, even an identical instance argument gets a different meta on the LHS vs. the RHS. So, anti-unification considers them a difference and places a phi. Same for an unresolved meta on one side and a resolved meta on the other.
The solution that I would like to propose is to wait for the meta variables to be resolved, before doing anti-unification. However, checking the goal …
=> Another tweak to cong!

src/Data/List/Base.agda
NB There are *no* lemmas about this in `Data.List.Properties`!?
=> Improve `Data.List.Base.unfold` (#2359; deprecate use of `with` #2123)

CHANGELOG.md, src/Algebra/Structures/Biased.agda
Also: tweak v2.0 deprecation warnings (I think correctly...)
=> [fix #2253] Deprecate `Algebra.Structures.Biased.IsRing*`

CHANGELOG.md, src/Data/List/Properties.agda
Hi! This is my first PR, apologies if I'm missing something.
This adds a series of proofs to `Data.List.Properties` that I consider general enough to be in the stdlib, and in most cases already exist for other list operations. This proves, in order:
- interaction with `map`, for list operations where it makes sense and was missing
- congruence for higher order operations, where missing (except for those acting on `Decidable`s, which I am still working on, and `unsnoc` which is challenging because of the indexed datatype)
- for `alignWith` / `align`, `zipWith` / `zip` and `unzipWith` / `unzip`:
- effect of swapping function arguments / inputs
- equivalence of swapping function arguments if function is commutative
- interaction of `take` with itself and with `drop`
- `unzipWith` + `zipWith` …
=> Add proofs to Data.List.Properties

CHANGELOG.md, src/IO/Primitive/Core.agda
This has to be in scope for desugaring `do` blocks that don't bind intermediate results.
=> Add `_>>_` for `IO.Primitive.Core`

CHANGELOG.md, src/Data/List/Membership/Setoid/Properties.agda, src/Data/List/Properties.agda, src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
This is a partial fix to #2353 but organised slightly differently, for consistency with existing uses of `reverse⁺` and `reverse⁻`, via a self-adjointness property of independent interest itself generalising the corresponding self-inverse property for `List.reverse`. 
Not done: extension to `Data.List.Relation.Binary.Sublist.Setoid._⊆_` (nor its `Heterogeneous` generalisation), which seems a *lot* more fiddly to achieve.
=> `Data.List.Base.reverse` is self adjoint wrt `Data.List.Relation.Binary.Subset.Setoid._⊆_`

CHANGELOG.md, src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda
NB *contra* @mechvel I have left `f` *implicitly* bound, on the prototype of `Data.List.Relation.Binary.Sublist.Setoid.Properties.map⁺`
=> fixes #2375

CHANGELOG.md, src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda, src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
Fixes #816 
Includes some tidying up refactoring wrt `variable`s (leading to a lot of redundant `module _ where` declarations...) and `import`s.
UPDATED: rectification for consistency with existing proofs in `Data.List.Relation.Binary.Sublist.Propositional`:
* names of lemmas? DONE
* orientation of `⊆-assoc`? DONE
Possible TODO:
* pull proofs back to `Heterogeneous`? (not done; downstream PR?)
=> Add `Data.List.Relation.Binary.Sublist.Setoid` categorical properties

CHANGELOG.md, src/Algebra/Construct/Pointwise.agda
NB:
* missing structures/bundles (I got bored)
* `isEquivalence` might already be defined somewhere else, but defined in-place here for the time being
=> Pointwise `Algebra`

doc/README/Design/Fixity.agda, doc/style-guide.md, src/Algebra/Bundles.agda, src/Algebra/Definitions.agda, src/Algebra/Definitions/RawMagma.agda, src/Algebra/Module/Bundles.agda, src/Algebra/Module/Definitions/Left.agda, src/Algebra/Module/Definitions/Right.agda, src/Algebra/Properties/Monoid/Divisibility.agda, src/Algebra/Properties/Semiring/Divisibility.agda, src/Algebra/Solver/Ring/AlmostCommutativeRing.agda
One more step towards #207 .   Also add to style guide.
=> Algebra fixity

.github/workflows/ci-ubuntu.yml, .github/workflows/haskell-ci.yml, agda-stdlib-utils.cabal
- **Haskell CI (for GenerateEverything) and dependencies bumped to GHC 9.10.1**
- **CI: bump some versions, satisfy some shellcheck complaints**
=> CI bumps: ghc 9.10, action versions, Agda to 2.6.4.3

doc/style-guide.md
Fixes #2390.
NB. The aim of the PR is to document what we (mostly) currently do, rather than fix in stone what we want to be able to do... the text is always changeable, and adherence to the guidelines a matter of manual review/checking!
=> `style-guide` rule for initial `private` block in modules

CHANGELOG.md, src/Data/Product/Relation/Binary/Pointwise/NonDependent.agda, src/Data/Vec/Functional/Relation/Binary/Pointwise/Properties.agda
=> Generalise `Data.Product.Relation.Binary.Pointwise.NonDependent.Pointwise`

CHANGELOG.md, src/Data/List/Properties.agda, src/Data/List/Relation/Binary/Permutation/Propositional/Properties.agda, src/Data/List/Relation/Binary/Permutation/Setoid/Properties.agda, src/Data/List/Relation/Binary/Permutation/Setoid/Properties/Maybe.agda
- Follow-up to PR #2361
- Ported from my [formal-prelude](https://github.com/omelkonian/formal-prelude/tree/c10fe94876a7378088f2e4cf68d9b18858dcc256)
=> More list properties about `catMaybes/mapMaybe`

src/Data/List/Base.agda
Refactor towards `if_then_else_`:
* `wordsBy`
* `linesBy`
=> Improve `Data.List.Base` (fix #2359; deprecate use of with #2123)

CHANGELOG.md, src/Algebra/Bundles.agda, src/Algebra/Lattice/Bundles.agda, src/Algebra/Lattice/Construct/Subst/Equality.agda, src/Algebra/Lattice/Structures.agda, src/Algebra/Structures.agda
UPDATED Fixes #2138 (and a bit more!)
* Introduces the new `Algebra.Structures` and `Algebra.Bundles`
* Redefines `Algebra.Lattice.Structures.IsSemilattice` and `Algebra.Lattice.Structures.IsBoundedSemilattice` as aliases for them, and fixes the knock-on dependency issues arising for `Algebra.Lattice.Bundles`,  `Algebra.Lattice.Construct.*`
* Adds more manifest fields for substructures arising from this in eg `IsIdempotentSemiring`
NB: (possible downstream PRs?)
* no `Biased` smart constructors (neither under `Algebra.Structures`, nor `Algebra.Lattice.Structures`)
* no `Consequences` (ditto.) to reflect the new arrangements
* no concrete example implementations in `Data.*.Properties` as per #2138 
* no deprecations of the (nevertheless now-redundant?) `Lattice` aliases.
=> Add `IsIdempotentMonoid` and `IsCommutativeBand` to `Algebra.Structures`

CHANGELOG.md, src/Data/List/Fresh/Relation/Unary/Any.agda, src/Data/List/Relation/Unary/Any.agda, src/Data/List/Relation/Unary/First/Properties.agda, src/Data/Sum.agda, src/Data/Vec/Relation/Unary/Any.agda, src/Relation/Binary/Construct/Closure/Reflexive/Properties.agda, src/Relation/Nullary/Decidable/Core.agda
Fixes #2059 on the model of #2330 / #2336
UPDATED Added `CHANGELOG` : badged as v2.1 but could easily be v2.2?
=> Refactor `Data.Sum.{to|from}Dec` via move+deprecate in `Relation.Nullary.Decidable.Core`

CHANGELOG.md, src/Data/List/Base.agda, src/Data/List/NonEmpty/Base.agda
NB. I haven't tried doing this with local named module defining an auxiliary function cf. #2411 because the scoping of such modules means that I end up having to write:
```agda
inits : List A → List (List A)
inits {A = A} = ([] ∷_) ∘ tail
module Inits where
tail : List A → List (List A)
tail []       = []
tail (x ∷ xs) = [ x ] ∷ map (x ∷_) (tail xs)
tails : List A → List (List A)
tails {A = A} = λ (xs : List A) → xs ∷ tail xs
module Tails where
tail : List A → List (List A)
tail []       = []
tail (_ ∷ xs) = xs ∷ tail xs
```
which isn't obviously more readable/intelligible because of the artificiality of introducing an explicit `λ ...` on the RHS?
UPDATED: have gone with (a cleaned-up version of) this style now!
=> fixes #2411

src/Function/Endo/Setoid.agda, src/Function/Relation/Binary/Setoid/Equality.agda
Breaks #2240 but as that was added in v2.1 suggest we merge this to supersede the definition there.
~~TODO~~ DONE: Knock-on effect on #2299 
NB no `CHANGELOG` required?
=> [v2.1-rc1] fixes #2400: use explicit quantification instead

src/Data/List/Base.agda, src/Data/List/Properties.agda
Fixes #2415 (I hope! @mechvel can you confirm that this reversion fixes the problem with `filter` you raised there?)
This reverts commit 438f9ed4c30751be35718297bbe0c8ec7d3fb669.
"Improve `Data.List.Base` (fix #2359; deprecate use of `with` #2123) (#2365)"
Specifically, it restores `with`-based definitions of the `Decidable`-definable functions on `List`s, incl. `filter` 
NB. We should agree what, if anything, *else* should be pushed (or: salvaged from #2365 ) to fix up v2.1-rc1, but this is a (*the*) minimal fix I could come up with. Eg can we incorporate @Taneb 's tests into the golden suite? How do we tackle the corresponding (failing!) cases for eg `partition`...?
=> Fix v2.1-rc1 by reverting (some) changes to `Data.List.*`

src/Algebra/Construct/Pointwise.agda
Consistency with #2400 / #2429 
No `CHANGELOG` required.
=> [v2.1-rc1] Change quantification from implicit to explicit in `Algebra.Construct.Pointwise.liftRel`

src/Data/Nat/Base.agda
Extracted from the discussion on [this Zulip thread](https://agda.zulipchat.com/#narrow/stream/259644-newcomers/topic/What.20is.20going.20on.20with.20this.20proof.20normalization.20performance.3F)
NB:
* no `CHANGELOG`: only a potential performance improvement
* should become redundant if we manage to deprecate these relations entirely
=> Make `_<″_`/`_≤″_` inversions more lazy

CHANGELOG.md, src/Data/Vec/Relation/Binary/Equality/DecPropositional.agda
Adds an 'obvious' missing property to make the API uniform with that for `Data.List.Relation.Binary.Equality.DecPropositional`.
NB.
* It seems as though these are each of these lemmas are redundant recodings of `Data.{List|Vec}.Properties.≡-dec`, so an alternative PR would be to *remove* the version for `List` instead of adding the one for `Vec`.
* On balance, I think the addition is preferable?
=> Reconciles `Data.Vec.Relation.Binary.Equality.DecPropositional` with `List`

doc/README/Data/Tree/AVL.agda
I had trouble understanding `MkValue` in the example `Tree` definition.  The proposed addition after the `Tree` definition briefly summarize what I learned (for future readers with ignorance like mine), without going into what I thought might be unnecessary detail.
I also added a suggestion and note about `Data.Tree.AVL.Map` in the "Further reading" section at the end.  I feel that `AVL.Map` satisfies the simplest use cases for the `Data.Tree.AVL`, so it's worth mentioning here.
(Sorry about the two commits with the same message.  I think I did something wrong when I tried to rebase them into one commit.  If it bothers anyone, I'll figure out how to fix it.)
=> Added AVL.Map suggestion, explanation of MkValue args.

CHANGELOG.md, src/Data/Nat/Properties.agda
I'm reluctant to add yet more to `Data.Nat.Properties`, but these lemmas seemed missing, and offered a sweet-spot in an application I've been working on, and as a by-product the left-to-right direction permits a possibly useful refactoring of `≤-pred`.
=> Proof that `pred` is right adjoint to `suc` on `ℕ._≤_`

.github/workflows/ci-ubuntu.yml
So I can test for the release of v2.1.1 for compatibility with Agda 2.7.0
=> Run CI tests on release branches as well

CHANGELOG.md, src/Data/List/Properties.agda, src/Data/Nat/Primality.agda, src/Data/Nat/Properties.agda
These are a couple of lemmas I found useful when trying to formalize Euclid's proof of the infinitude of primes.
- the product of non-zero naturals is non-zero
-  any element of a list of non-zero naturals is less-or-equal to the product of the list
Hopefully I didn't just miss these somewhere else, but the divisibility result above this was about the only theorem I could find about `product`.
=> Add a couple lemmas about product in Data.List.Properties

CHANGELOG.md, src/Data/Maybe/Properties.agda
This is part of upstreaming properties that seem generally useful.
=> Add a property relating `maybe` to composition

CHANGELOG.md, src/Data/List/Membership/Setoid/Properties.agda, src/Data/List/Relation/Unary/All/Properties.agda, src/Data/List/Relation/Unary/All/Properties/Core.agda
Fixes #2463 
Breaks dependency cycle by introducing new `Data.List.Relation.Unary.All.Properties.Core` module.
=> Add two lemmas to `Data.List.Membership.Setoid.Properties` 

src/Data/List/Relation/Unary/Unique/Propositional.agda, src/Data/List/Relation/Unary/Unique/Setoid.agda
=> Simplify definitions/exports in `Data.List.Relation.Unary.Unique.*`

CHANGELOG.md, src/Data/List/Base.agda, src/Data/List/Membership/Propositional/Properties.agda, src/Data/List/Membership/Propositional/Properties/Core.agda, src/Data/List/Membership/Propositional/Properties/WithK.agda, src/Data/List/Membership/Setoid/Properties.agda, src/Data/List/Properties.agda, src/Data/List/Relation/Binary/Disjoint/Propositional/Properties.agda, src/Data/List/Relation/Binary/Disjoint/Setoid/Properties.agda, src/Data/List/Relation/Binary/Permutation/Propositional/Properties/WithK.agda, src/Data/List/Relation/Binary/Sublist/Heterogeneous/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda, src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda, src/Data/List/Relation/Binary/Subset/Setoid/Properties.agda, src/Data/List/Relation/Unary/Any/Properties.agda, src/Data/List/Relation/Unary/Unique/Propositional/Properties.agda, src/Data/List/Relation/Unary/Unique/Setoid/Properties.agda
Porting useful list properties that we needed in the [Cardano ledger project](https://github.com/IntersectMBO/formal-ledger-specifications), several of which are themselves ported from my [personal prelude](https://github.com/omelkonian/formal-prelude/).
I am totally fine with some of those not being merged due to the 'Fairbairn threshold' or just because it is too niche of a utility to be included in the standard library; I'll let the reviewer(s) decide.
NB: each commit is somewhat independent, so reviews can proceed in a per-commit fashion (unless a change is requested globally, e.g. cosmetic changes w.r.t. to the style guide).
=> Lists: porting several lemmas from other libraries

CHANGELOG.md, src/Relation/Binary/Construct/Interior/Symmetric.agda
First steps towards #2353 , but of independent interest/utility, I hope.
NB. Issue:
* we don't seem to have `IsDecPreorder`/`DecPreorder` defined in `Relation.Binary.Structures`/`Relation.Binary.Bundles`? now raised as #2482 so move discussion there.
=> Add properties/structures/bundles related to decidability for `Relation.Binary.Construct.Interior.Symmetric`

CHANGELOG.md, src/Data/List/Membership/Setoid/Properties.agda
NB.:
* enabled by the refactoring in #2463 in terms of `Data.List.Relation.Unary.All.Properties.Core`
* easy refactoring of the `private` lemma
* Fairbairn threshold? The additions are (specialised) versions of imported lemmas.
=> fixes #2466: add equivalence proofs

CHANGELOG.md, src/Data/List/Membership/Propositional/Properties.agda
This refactors the (very!) recent additions to `Data.List.Membership.Propositional.Properties` for nested lists in favour of delegation to existing functionality.
NB:
* I should have seen this during my review of #2479 , but ... l'esprit de l'escalier, I guess ;-)
* the deprecation of `map∷-decomp` is possibly redundant/excessive, given how recently introduced was that name/definition
* the newly introduced replacement name/definition `map∷⁻` is likewise arguably redundant, in favour of inlining its definition, but useful perhaps for its type which enforces the `variable = complex` refinement of our existing heuristic for writing library rewrite lemmas in the form `complex = simpler`
* I have only done a back-of-the-envelope analysis to conjecture that the refactored definitions have the …
=> [DRY] refactor #2479

src/Data/List/Relation/Binary/Equality/DecSetoid.agda, src/Data/List/Relation/Binary/Equality/Setoid.agda, src/Data/List/Relation/Binary/Subset/DecSetoid.agda
Addresses the two examples of the general issue #2391 , but leaving that open for further downstream instances to be tackled.
NB.:
* no `CHANGELOG` required, as a 'pure' refactoring
=> [DRY] Refactor `Data.List.Relation.Binary.Equality.Setoid` exports

CHANGELOG.md, src/Relation/Binary/Bundles.agda, src/Relation/Binary/Construct/Interior/Symmetric.agda, src/Relation/Binary/Structures.agda
Fixes #2482 (I hope).
UPDATED: DONE knock-on consequences for #2481 ... which prompted these additions in the first place!
=> Add `(Is)DecPreorder` to `Relation.Binary.*`

CHANGELOG.md, src/Data/Rational/Properties.agda
This is pulled out from my branch for real numbers
A discovered annoyance (bug?) is that `*-monoˡ-≤-nonNeg` corresponds to `*-monoʳ-<-pos`, _not_ `*-monoˡ-<-pos` as one may expect. But I don't want to fix that in this PR
=> Lemmas for Positive, Negative, etc. and _+_ and _*_ for rationals

CHANGELOG.md, src/Data/Refinement.agda, src/Data/Refinement/Base.agda, src/Data/Refinement/Properties.agda
NB.
* could be folded into `Data.Refinement` directly?
* Fairbairn threshold? is this injectivity proof not *immediate*?
=> Add properties of `Data.Refinement` and refactor module structure

CHANGELOG.md, src/Data/List/Relation/Unary/First/Properties.agda
This PR adds a `¬Any⇒All¬` counterpart for `First`:
```agda
¬First⇒All : ∁ Q ⊆ P → ∀ xs → ∁ (First P Q) xs → All P xs
-- cf.
-- In Data.List.Relation.Unary.All.Properties.Core
¬Any⇒All¬ : ∀ xs → ¬ Any P xs → All (¬_ ∘ P) xs
```
Issues
- Should `xs` be an explicit argument or implicit?
- Explicit for consistency with `¬Any⇒All¬` for now
- Is`∁ (First P Q) xs` preferable over `¬ First P Q xs`?
=> add `¬First⇒All` lemma to `Data.List.Relation.Unary.First.Properties`

CHANGELOG.md, src/Data/Product/Function/Dependent/Propositional.agda, src/Function/Related/TypeIsomorphisms.agda
Upstreaming some functions that I've used to prove things about sets (not the Agda kind).
=> Add some type relations and isomorphisms

CHANGELOG.md, src/Data/Tree/AVL/Indexed/Relation/Unary/Any/Properties.agda, src/Data/Tree/AVL/Map/Membership/Propositional.agda, src/Data/Tree/AVL/Map/Membership/Propositional/Properties.agda, src/Relation/Binary/Bundles.agda, src/Relation/Binary/Bundles/Raw.agda, src/Relation/Binary/Properties/Poset.agda
This addresses the `Relation.Binary.Bundles.Raw` [part of #2274](https://github.com/agda/agda-stdlib/issues/2274#issuecomment-2112489369) ahead of any subsequent refactoring of the `Algebra` hierarchy in earnest, to exploit the standardisation of vocabulary/fixity envisaged there. 
Adds:
* `RawX` bundles systematically to mirror those in `Relation.Binary.Bundles.X`
* `rawX` manifest fields to each of those in `Relation.Binary.Bundles.X`
NB. Possible issues:
* By contrast with the main `Relation.Bundles` definitions, this introduces `rawSetoid` fields at the top level to each `RawX` bundle, in order to also introduce the negated equality symbol `_≉_` uniformly.
* The `DecX` hierarchy is not mirrored with a parallel `RawDecX` hierarchy... which might otherwise violate the proposed …
=> Add `Raw` bundles to `Relation.Binary.*` hierarchy

doc/installation-guide.md
=> Update installation instructions

CHANGELOG.md, src/Data/List/Relation/Unary/All/Properties.agda
Fixes #2509
NB. Tweaks the `import`s in order to have clean separation of `Sublist._⊆_` and its properties from `Subset._⊆_`.
=> Add `all⊆concat`

CHANGELOG.md, src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda
All the knock on effects seem to be internal to the module only. Cross fingers will pass CI.
=> Remove implicit parameters from Sublist.Propositional.Properties

CHANGELOG.md, src/Algebra/Structures.agda
It was missing several and had some duplicated, which was causing problems when trying to use those names
I don't know how to changelog this
=> Mess around with IsSemiringWithoutOne reexports

CHANGELOG.md, src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda
This implements the lemma requested by @mechvel on [zulip](https://agda.zulipchat.com/#narrow/channel/264623-stdlib/topic/.60.60_.E2.8A.86.E2.82.80_.20.E2.87.92.20_.E2.8A.86.E2.82.97_.60.60.20for.20sublist.20by.20propositional.20vs.20by.20Setoid)
[DELETED]
UPDATED:
* lemma in `Propositional.Properties`
* reduces to a triviality involving `Setoid.map`
* Fairbairn threshold?
=> [ add ] lemma relating `Propositional` and `Setoid` versions of `Sublist`

CHANGELOG.md, src/Data/List/Relation/Unary/All/Properties.agda
Fixes #2520 with implementations using `Relation.Nullary.Decidable.dec-true` to simplify the case analysis.
NB only the first two lemmas suggested in the issue.
=> [ add ] Lemmas about `takeWhile` and `dropWhile` to `Data.List.Unary.All.Properties`

CHANGELOG.md, src/Data/Nat/Base.agda, src/Data/Nat/Properties.agda
Fixes #2504 , following the discussion there and on #2503 , which this also refactors.
Tagged as `breaking`, although the only known use of this relation in the wild is from the OP of #2503 , and the `CHANGELOG` documents the only possible (?) source of `breaking` behaviour, namely supplying implicit arguments to the new pattern synonym for the former non-linear constructor `≤‴-refl`. Hence v2.2, not v3.0... but I'm happy to row back on that.
=> [ refactor ] Change definition of `Data.Nat.Base._≤‴_`

CHANGELOG.md, src/Data/Nat/Base.agda, src/Data/Nat/Properties.agda
This is exactly analogous to #2504 ,  in line with #2519 .
Potentially `breaking`, but all tests pass on `stdlib` without changes.
Possible downstream improvement for tackling #2442 ?
=> [ refactor ] Change definition of `Data.Nat.Base._≤′_`

CHANGELOG.md, src/Data/List/Properties.agda, src/Data/List/Sort/MergeSort.agda
I'm persuaded by the [discussion on Zulip](https://agda.zulipchat.com/#narrow/channel/264623-stdlib/topic/.60concat-single.60.20.3F) (and my own thoughtlessness in responding there) that this is a simple worthwhile addition, with its potential downstream use in #2524 (and elsewhere). Thanks to @ncfavier for clarifying the triangle laws for the `List` monad!
Possible issue(s):
* naming (as ever); alternatives `concat∘[_]≗id`? (or some prefix version?)
* use of mixfix notation; but here it seems to chime well with `[_]` as an operator?
* rename existing `concat-[-]` to eg. `concat∘map[_]≗id`? (or some more informative prefix version?)
=> [ add ] `concat [ xs ] ≡  xs`

CHANGELOG.md, src/Data/List/Relation/Unary/All/Properties.agda
This is a coda to #2520 / #2521 : the type of `takeWhile⁻` is insufficiently general, and generalising it makes the proof trivially delegate to that of `all-takeWhile`; another instance of 'non-linear bindings considered harmful' ...
NB. UPDATED: following @MatthewDaggitt 's suggestions below, can now ignore first three items here
* not sure how to record this in `CHANGELOG`: under `Minor improvements`? 
* possible deprecation of `takeWhile⁻` now possible? or else of `all-takeWhile`? 
* not `breaking`, but not clear whether the generalisation may lead to `unsolved metas` errors downstream?
* any other similar refactorings possible?
=> Deprecate `Data.List.Relation.Unary.All.Properties.takeWhile⁻`

CHANGELOG.md, src/Data/List/Relation/Binary/Sublist/Propositional/Properties.agda, src/Data/List/Relation/Binary/Sublist/Setoid/Properties.agda, src/Data/List/Relation/Unary/All/Properties.agda
Fixes #2517 following discussion there. 
Re-exports to `Data.List.Relation.Binary.Sublist.Propositional.Properties` automatically, so this strictly generalises #2513 as a solution to #2509 .
=> [ refactor ] Move `Data.List.Relation.Unary.All.Properties.all⊆concat` to `Data.List.Relation.Binary.Sublist.Setoid.Properties`

CHANGELOG.md, src/Algebra/Bundles/Raw.agda
This tackles the second part of #2274 as a followup to #2491 by replacing the in-place definition of negated equality in `Algebra.Bundles.Raw.*` with a delegation to its definition in the underlying `RawSetoid` bundle via an additional `rawSetoid` manifest field.
Outstanding issues:
* should the new field itself be publicly exported throughout, rather than simply the negated equality, as previously?
* does this addition give rise to similar problems as those recently fixed by #2499 ?
=> [ refactor ] add `rawSetoid` manifest fields to `Algebra.Bundles.Raw`

CHANGELOG.md, src/Data/List/Relation/Binary/Equality/Setoid.agda, src/Data/List/Relation/Binary/Pointwise.agda
This is a do-over of #2426 , which I think should be regarded as having introduced a bug, which this PR fixes, as well as the original issue #1131 . 
This also addresses the left/right issue discussed extensively on the original PR and in #2532 .
Fortunately the original PR was v2.2, so this is *not* breaking, indeed should be a 'silent' refactoring.
Outstanding issue: refactor further to make use of `LeftCongruent` and `RightCongruent` from `Algebra.Definitions`, which changes explicit quantification as now to implicit quantification... I'm inclined to do this, so feedback welcome!
=> [ refactor ] exchange left and right in `Data.List.Relation.Binary.Pointwise` etc. congruence rules for `_++_`

CHANGELOG.md, doc/README/Data/Vec/Relation/Binary/Equality/Cast.agda, src/Data/Vec/Properties.agda, src/Data/Vec/Relation/Binary/Equality/Cast.agda
This PR introduces the `≈-cong′` lemma:
``` agda
≈-cong′ : ∀ {f-len : ℕ → ℕ} (f : ∀ {n} → Vec A n → Vec B (f-len n))
{xs : Vec A m} {ys : Vec A n} .{eq} → xs ≈[ eq ] ys →
f xs ≈[ cong f-len eq ] f ys
≈-cong′ f {xs = []}     {ys = []}     refl = cast-is-id refl (f [])
≈-cong′ f {xs = x ∷ xs} {ys = y ∷ ys} refl = ≈-cong′ (f ∘ (x ∷_)) refl
```
This lemma does for `≈[_]` what `cong` does for `≡`: given `f` and `xs ≈[ _ ] ys` it proves `f xs ≈[ _ ] f ys`.
More specifically, it proves that any `Vec A n → Vec B m` function that is polymorphic in `n` must preserve `≈[_]`.
Compare this with the existing `≈-cong` lemma (introduced by @shhyou with #2067 along with the reasoning system):
``` agda
≈-cong : ∀ .{l≡o : l ≡ o} .{m≡n : m ≡ n} {xs : Vec A m} {ys zs} (f : Vec A o → Vec A n) →
xs ≈[ m≡n ] f …
```
=> Vec.Properties: introduce `≈-cong′`

CHANGELOG.md
On a side, nothing seems to be there after `with a more informative type (see below)`? 
https://github.com/agda/agda-stdlib/blob/d85cd7e5cc9d990c103be625e52331b6e7f125b9/CHANGELOG.md?plain=1#L85-L92
=> Fix the indentation of a few lines in CHANGELOG

src/Data/List/Membership/Propositional.agda, src/Data/List/Membership/Propositional/Properties/Core.agda
Cherry-picked by hand from #2545 . No `CHANGELOG` required.
=> [ refactor ] Remove use of `rewrite` from `Data.List.Membership.Propositional.Properties.Core`

src/Algebra/Construct/Initial.agda
Agda PR #7674 requires some implicit arguments explicitly in some record expression given since variance info got refined (invariant to non-variant) and hence solutions are no longer unique.
Fixing Agda to commit 2ffb002249ff99f1990cbcbca6bfa7636cf98a60 now in agda/agda#7674.
If this PR is rebased or **squashed** (rather than merged with merge commit) the commit hash there needs to be updated accordingly.
=> agda/agda#7674 eta-expand fields in record expression

CHANGELOG.md, doc/style-guide.md, src/Algebra/Definitions/RawMagma.agda, src/Algebra/Properties/Magma/Divisibility.agda, src/Algebra/Properties/Monoid/Divisibility.agda, src/Algebra/Properties/Semigroup/Divisibility.agda
=> [ refactor ] rename `∣∣` to `∥`, `∤∤` to `∦` throughout `Algebra.Definitions.RawMagma` and `Algebra.Properties.*.Divisibility`

src/Data/Nat/Properties.agda
One leftover from #2206 fixing #2168 (!)
No `CHANGELOG`.
=> [ bug ] Fix use of `+` in lemma preconditions in favour of `∧`

CHANGELOG.md, src/Data/Bool/ListAction.agda, src/Data/List/Base.agda, src/Data/List/Relation/Binary/Subset/Propositional/Properties.agda, src/Data/List/Relation/Unary/All/Properties.agda, src/Data/List/Relation/Unary/Any/Properties.agda
This is the `Bool` analogue of #2558; see discussion there and  on #2553 .
Issue:
* intended as a v2.3 compatibility stub module, ahead of a more thorough refactoring in terms of `Data.List.Effectful.Foldable.foldMap`?
=> [ refactor ] Add `Data.Bool.ListAction`

src/Axiom/DoubleNegationElimination.agda, src/Axiom/ExcludedMiddle.agda
Purely cosmetic; tightens `import`s. No `CHANGELOG`.
=> [ refactor ] `Axiom.ExcludedMiddle` and `Axiom.DoubleNegationElimination`

CHANGELOG.md, src/Data/Nat/Properties.agda
=> Implement ≤-total in terms of _≤?_

CHANGELOG.md, src/Algebra/Construct/NaturalChoice/MinMaxOp.agda, src/Algebra/Module/Consequences.agda, src/Algebra/Module/Structures/Biased.agda, src/Algebra/Properties/CancellativeCommutativeSemiring.agda, src/Data/Rational/Unnormalised/Properties.agda
More leftovers from #2168 / #2206 / #2564 . Hopefully these are the very last ones!
=> [ bug ] Fix use of `+` in lemma preconditions in favour of `∧` (bis) 

src/Data/List/Relation/Unary/Enumerates/Setoid/Properties.agda
Purely cosmetic; no `CHANGELOG`.
=> [ refactor ] `Data.List.Relation.Unary.Enumerates.Setoid.Properties` using tighter lemma from `Function.Consequences`

src/Data/Integer/Properties.agda, src/Data/Nat/Properties.agda
=> [ re #523 ] Refactorings using wlog

CHANGELOG.md, src/Algebra/Apartness/Properties/HeytingCommutativeRing.agda, src/Algebra/Apartness/Structures.agda
Currently in `IsHeytingCommutativeRing`, `sym` is overloaded as it is exported both from `IsCommutativeRing` and `IsApartnessRelation`. This PR renames the apartness sym to `#-sym`.
NOTE: `#-sym` is also removed from `Algebra.Apartness.Properties.HeytingCommutativeRing` as it is now redundant.
=> Rename overloaded sym in apartness

src/Algebra/Properties/Magma/Divisibility.agda, src/Algebra/Properties/Monoid/Divisibility.agda, src/Algebra/Properties/Semigroup/Divisibility.agda, src/Algebra/Properties/Semiring/Divisibility.agda, src/Algebra/Properties/Semiring/Primality.agda
Cosmetic (non-`breaking`): : simplifies `import`s and some proofs. Lifted out from #2573 
NB. Could go further (but then would be `breaking`):
* define `NonTrivial` to mean `1# ≉ 0#` (rather than `0# ≉ 1#` as used currently), and refactor to use `NonTrivial` as hypothesis (Blast! clashes with `Data.Nat.Base.NonTrivial` with a different semantics...)
* redefine mutual divisibility using `Relation.Binary.Construct.Interior.Symmetric`, and exploit the generic properties of such relations
* ...
=> [ refactor ] `Algebra.Properties.Semiring.Divisibility` and friends

CHANGELOG.md, src/Algebra/Definitions/RawMagma.agda, src/Relation/Binary/Construct/Interior/Symmetric.agda
Fixes the fixity bugs discussed in #2582 .
Hopefully there aren't any others!?
=> [ fix ] Add correct fixities for `constructor` uses of `_,_`

src/Algebra/Properties/CommutativeMagma/Divisibility.agda, src/Algebra/Properties/Magma/Divisibility.agda
Fixes:
* the inciting incident from #2629 
* an uncaught use of a deprecated name
=> [ refactor ] `Algebra.Properties.Magma.Divisibility`

CHANGELOG.md, src/Relation/Nullary/Decidable/Core.agda
Adds missing `Dec` values for unit type (nullary product type) and empty type (nullary sum type).
=> Add Dec for unit and empty types

CHANGELOG.md, src/Relation/Binary/Construct/Add/Infimum/Strict.agda
Fixes #2682 
NB:
* can this be streamlined further?
* corrects typo in opening comment
* tweaks proof of `<₋-transʳ` to make it slightly lazier in first clause, avoids dot-pattern
=> [ add ] wellfoundedness of `Relation.Binary.Construct.Add.Infimum.Strict`

CHANGELOG.md, src/Algebra/Lattice/Properties/BooleanAlgebra.agda
=> [ refactor ] Rename `Algebra.Lattice.Properties.BooleanAlgebra.{⊥≉⊤,⊤≉⊥}`

doc/README/Design/Hierarchies.agda
Fixes issue #2698, plus corrects naming convention for the two open lemmas under `Consequences` (cf. #2168 / #2206 ).
=> [ fix ] documentation of `Algebra.Bundles.Raw` in `README.Design.Hierarchies`

src/Function/Base.agda
=> [ fix ] attach fixity to the new declaration of `Function.Base.case_returning_of_`

src/Data/Fin/Base.agda
=> [ fix ] redundant import in `Data.Fin.Base`

CHANGELOG.md, src/Relation/Binary/Reasoning/Base/Partial.agda
Resolves #2677.
This one replaces the previous reasoning type for `PartialSetoid` with one properly supporting propositional equality steps.
=> [add] Update PartialSetoid reasoning

CHANGELOG.md, src/Relation/Nullary/Negation/Core.agda
Self-explanatory, but I'm open to:
* alternative suggestions for the name of this lemma
* suggestions that we don't even need this ;-)
=> [ add ] obvious lemma about self-contradiction to `Relation.Nullary.Negation.Core`

src/Relation/Binary/OrderMorphism.agda
Update the deprecation warning to correctly reference Relation.Binary.Morphism.Bundles instead of Relation.Binary.Reasoning.Morphism.
=> Fix bug in Relation.Binary.Morphism.Bundles usage

.github/workflows/haskell-ci.yml, agda-stdlib-utils.cabal
- **Bump Haskell CI to GHCs 9.12.2 9.10.2 9.6.7**
No review required.
=> ghc 9.12.2

CHANGELOG.md, src/Data/List/Relation/Binary/Permutation/Propositional.agda
One approach which fixes #2708. 
NB:
* v2.3 compatible
* bit clunky, esp. wrt naming
* `CHANGELOG` entry doesn't explicitly link `isEquivalence` argument with target relation
* fixes typo in subsequent entry
* v3.0 version might form part of ongoing (but stalled) refactoring project #1354 and associated PRs, with better choices of names in particular
=> [ refactor ] generalise inclusion between `Propositional` permutation, and arbitrary `Setoid`-based version on same carrier

CHANGELOG.md, src/Relation/Binary/Properties/PartialSetoid.agda
This adds the properties of PERs discussed in #2677 .
Issues:
* naming: `p-` prefix to signify 'partial'
* where to add: 
- `Properties` (as here)
- `Consequences` (contra: dependency on `PropositionalEquality`)
- or as manifest fields of `Relation.Binary.Structures.IsPartialEquivalence` (contra: every `IsEquivalence` gets bloated by the addition)
Downstream:
* potential refactoring of `Relation.Binary.Properties.Setoid` to inherit from this?
=> [ add ] `Relation.Binary.Properties.PartialSetoid`

CHANGELOG.md, src/Relation/Binary/Morphism/Construct/Product.agda
Lifts out the relevant constructions on `RawSetoid` from #2715 which is now marked blocking on this PR.
NB.
* constructions defined in named modules with explicit parametrisation, each as the relevant `IsRelHomomorphism`
* *then* defined for export in terms of the 'usual' expected names, with *implicit* parametrisation
* should the underlying `Pointwise` product of `RawSetoid`s be lifted out (trivially) to `Relation.Binary.Construct.Product`? (see discussion with/comments from @JacquesCarette below...)
=> [ add ] product structure on `RawSetoid`

CHANGELOG.md, src/Data/Fin/Permutation.agda, src/Relation/Nullary/Decidable.agda, src/Relation/Nullary/Decidable/Core.agda, src/Relation/Nullary/Recomputable.agda, src/Relation/Nullary/Recomputable/Core.agda
This PR sharpens the type of `Relation.Nullary.Decidable.dec-yes` by supplying an explicit existential witness:
* `dec-yes-recompute` weakens the hypothesis to allow *irrelevant* argument `.(a : A)`
* by witnessing the existential with `recompute a? a`
* `dec-yes` then follows immediately.
It introduces two new lemmas:
* `Relation.Nullary.Recomputable.recompute-irrelevant-id`: for propositionally irrelevant `A`, `recompute` is the identity
* `Relation.Nullary.Decidable.Core.recompute-irrelevant-id`, encapsulating the above
UPDATED:
* refactors `Relation.Nullary.Recomputable` to lift definitions and basic properties out into `Relation.Nullary.Recomputable.Core`.
=> [ add ] `Relation.Nullary.Decidable.dec-yes-recompute`

CHANGELOG.md, src/Data/Vec/Properties.agda, src/Data/Vec/Properties/WithK.agda
- Replace `Data.List.Base as List` and `Data.List.Properties as List` with shorter `L` aliases throughout the module for better readable proof 
- Add new utility lemma `toList-injective` that proves vector equality from list equality using heterogeneous equality
- Add new equation-free lemmas that leverage `toList-injective` for cleaner proofs:
- `fromList-reverse`: proves `fromList (L.reverse xs) ≈[ L.length-reverse xs ] reverse (fromList xs)`
- `++-ʳ++-eqFree`: proves associativity-like property for reverse-append without explicit equation parameter
- `ʳ++-ʳ++-eqFree`: proves composition property for reverse-append operations
- Update all `List.` references to `L.` in function types and implementations
- Import `Tactic.Cong` module to support the `cong!` tactic used in several proofs …
=> Refactor `Data.Vec.Properties` : Add toList-injective and new lemmas 

src/Data/Integer/Properties.agda, src/Induction/InfiniteDescent.agda
Detected by a new warning for superfluous rewrites: agda/agda#7973
Note: Agda `master` will soon warn about these, but 2.8.0 won't (unless maybe its release is further delayed).
Anyway, this PR can be merged immediately since it removes rewrite steps that are superfluous independent on the Agda version.
=> Cosmetics: delete 2 rewrite steps that do not fire

CHANGELOG.md, doc/README/Data/Fin/Relation/Unary/Top.agda, src/Algebra/Properties/Semiring/Binomial.agda, src/Data/Fin/Subset/Properties.agda, src/Data/Nat/Binary/Subtraction.agda, src/Data/Nat/Combinatorics.agda, src/Data/Nat/Properties.agda
~~These lemmata were~~This lemma was useful in inductive proofs involving `∸` ~~and `≤`~~ and it seems ~~these two lemmata are~~ this lemma is not yet part of the standard library.
=> [ add ] `∸-suc` lemma for natural numbers

CHANGELOG.md, src/Relation/Nullary/Negation/Core.agda
For justification, see `CHANGELOG`: this is really a consequence of #2199 and subsequent refactorings of `Relation.Nullary.Recomputable{.Properties}`. Cf. #2346 which might be worth re-opening?
Very little is affected, except that `contradiction` now needs to be eta-expanded because there is no subtyping between `A → B` and `.A → B`.
For candidate use, see the discussion in #2783 .
=> [ refactor ] weaken type of `Relation.Nullary.Negation.Core.contradiction-irr`

paper/paper.md
An affiliation index is off by one in the metadata.
=> Edit affiliation: 13 and two missed typos

CHANGELOG.md, src/Relation/Nullary/Negation.agda, src/Relation/Nullary/Negation/Core.agda
=> [ add ] flipped version of `Relation.Nullary.Negation.Core.contradiction`

src/Data/Fin/Properties.agda
UPDATED: 
* no `CHANGELOG` required! Only existing proofs have been refactored. 
* issue below resolved moderately successfully via @andreasabel 's trick with `flip contradiction` cf. #2784 
NB. I tried to simplify the proof of `injective⇒existsPivot` to use `<⇒notInjective` instead, but it causes a weird explicit/implicit type inference error when trying to obtain a contradiction from `f∘inject!-injective` and `<⇒notInjective`...:
```agda
injective⇒existsPivot {f = f} f-injective i
with any? (λ j → j ≤? i ×-dec i ≤? f j)
... | yes result = result
... | no ¬result = contradiction f∘inject!-injective (<⇒notInjective {f = f∘inject! } (ℕ.n<1+n (toℕ i)))
where
...
```
yields
```agda
/home/james/RESEARCH/Agda-stdlib-dev-v2.3/src/Data/Fin/Properties.agda:1077.55-104: error: [UnequalHiding] …
```
=> [ refactor ] `Data.Fin.Properties` following #2746

CHANGELOG.md, src/Algebra/Morphism/Construct/DirectProduct.agda
#2715 introduced a definition with a bug. This PR solves such bug.
=> [bug] replace wrong argument to projection in `Algebra.Morphism.Construct.DirectProduct`
